### ISSUE TITLE
Number guessing image is missing and is not showing

### ISSUE THREAD

**Issue by MrityunjaySingh09** [iamrahulmahato/master-web-development#101]
![image](https://github.com/user-attachments/assets/054e6ca2-1aa7-481f-a61c-09184af43938)
See here the image url is not right i guess and needs to be corrected  ..Please assign me under gsoc 24 extended

**Comment by iamrahulmahato** [comment]
Sorry, @MrityunjaySingh09. Someone already working on it raises another issue.
