### ISSUE TITLE
🧑‍💻 : add times of different zones/countries in Clock project

### ISSUE THREAD

**Issue by Riyachauhan11** [iamrahulmahato/master-web-development#1025]
:red_circle: **Title** : create an option to display live time from several countries/time zones. The project currently only displays time of india.
:red_circle: **Enhancement Aim** : add more functionality to project and increase user interactions
:red_circle: **Changes** : 
- aiming to create a dropdown menu using which user will be able to select timezones of different countries and display their respective time
- the page will start with displaying time in india

### Screenshots 📷

![image](https://github.com/user-attachments/assets/24677d0c-b294-49bf-84a8-3d7a2b965c99)
display time of different countries and display the country's name with the time

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Riya Chauhan
Participant Role : GSSOC, Hacktoberfest, Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by jashwanthbavandlapalli** [comment]
Hi @Riyachauhan11 , I noticed you’re assigned to this issue. I’m really interested in working on it too. If you’re unable to continue, I’d love to take over or assist you. I believe I can bring some valuable insights to this problem. Let me know what you think!

**Comment by Riyachauhan11** [comment]
> Hi @Riyachauhan11 , I noticed you’re assigned to this issue. I’m really interested in working on it too. If you’re unable to continue, I’d love to take over or assist you. I believe I can bring some valuable insights to this problem. Let me know what you think!

Hi! Thanks for reaching out. I’m planning to continue working on this issue and I’m confident I’ll be able to finish it. However, if for some reason I’m unable to complete it, I’ll definitely let you know and you can take over.
