### ISSUE TITLE
🐞 :  Scroll to top button is getting overlapped

### ISSUE THREAD

**Issue by Shariar-Hasan** [iamrahulmahato/master-web-development#1027]
:red_circle: Scroll to top button is getting overlapped :
:red_circle: **Bug** :
:red_circle: **Changes** :  i will change the z-index for this section

### Screenshots 📷
![image](https://github.com/user-attachments/assets/a8adefd8-2d4c-4460-bc02-28d1ce1009c4)

************************************************************

✅ Details to Include When Taking the Issue:
Name : Hacktoberfest
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
issue solved
