### ISSUE TITLE
Add 'Play with AI' Feature to Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by 13Sharad** [iamrahulmahato/master-web-development#1030]
The current Tic-Tac-Toe game only supports two human players. Adding an AI opponent option would enhance the user experience by allowing players to enjoy the game even when no second player is available.

Describe it in detail :- 

Introduce an AI opponent feature that players can choose to compete against. The AI should make decisions based on predefined strategies, such as blocking the player’s winning moves and trying to win. The difficulty level can be adjustable to provide a challenge for players of different skill levels.

Describe the solution you'd like :- 

Add an option to select "Play with AI" before starting the game.
The AI should take turns automatically after Player X's move, making intelligent decisions to either block Player X or try to win.
Ensure the game functions properly whether the player chooses human vs. human or human vs. AI mode.

Describe alternatives you've considered :-

Implement a basic random-move AI for easy level and a minimax algorithm for a more challenging level.
Instead of integrating AI, consider adding an online multiplayer option.

Additional context  :-

This feature will make the game more flexible, allowing single players to enjoy the game against a computer opponent. Adding different AI difficulty levels could make the game more engaging.

Please add hacktoberfest and GSSoC24 tag. You can assign me for this issue.

**Comment by jashwanthbavandlapalli** [comment]
Hi @13Sharad , I noticed you’re assigned to this issue. I’m really interested in working on it too. If you’re unable to continue, I’d love to take over or assist you. I believe I can bring some valuable insights to this problem. Let me know what you think!

**Comment by 13Sharad** [comment]
@iamrahulmahato please added level and Merged this pull request.

**Comment by 13Sharad** [comment]
@iamrahulmahato Merged this pull request
