### ISSUE TITLE
adding back to top feature

### ISSUE THREAD

**Issue by AswaniBolisetti** [iamrahulmahato/master-web-development#1036]
@iamrahulmahato 
I would like to work on this feature, could you please assign me this issue

**Comment by iamrahulmahato** [comment]
can you elaborate more with the function and UI?

**Comment by AswaniBolisetti** [comment]
when we click that option/arrow, it will redirect to the home page/ starting of the page,
![Uploading scrolltotop.jpg…]()

**Comment by iamrahulmahato** [comment]
ok make the arrow minimal and it should match with the Ui of the page
