### ISSUE TITLE
📃: QR Code and Bar Code Reader 

### ISSUE THREAD

**Issue by 09viv** [iamrahulmahato/master-web-development#1044]
🔴 Title : QR Code and Bar Code Reader
🔴 Tech stack : HTML, CSS, JavaScript, Python, Flask
🔴 Objective : To add feature of scanning QR Code and Bar Code
🔴 Summary : This project introduces a QR code and barcode scanner application using OpenCV and Python. The application can detect and decode QR codes and barcodes from images and video streams, providing a user-friendly interface for scanning.
📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Vivek Gazalwar
Participant Role : GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already present in project
