### ISSUE TITLE
🧑‍💻 :  Missing Name, Image, Description in Photo Gallery project

### ISSUE THREAD

**Issue by Rahul-AkaVector** [iamrahulmahato/master-web-development#1047]
:red_circle: **Title** : Missing Name, Image, Description in Photo Gallery Project  

:red_circle: **Enhancement Aim** : To enhance the user experience by adding the missing name, image, and description to the Photo Gallery project. 
 
:red_circle: **Changes** : 
- Add names to the respective images.
- Include relevant images where missing.
- Provide descriptive text for each image to give context.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/4f76eb1c-a8b6-4b1a-a67e-6693b14a1f57)

**********************************************************************
✅ Details to Include When Taking the Issue:  
Name : Rahul Aka Vector
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC , Hacktoberfest, Contributor, Level 1

**********************************************************************

**Comment by istutijn-algo24** [comment]
Name: Istuti Jain
Partcipant Role(GSSOC,Hacktoberfest,Contributor)

I would like to contribute in this . Please assign it to me.

**Comment by iamrahulmahato** [comment]
someone working on it
