### ISSUE TITLE
📃: Image File Size Reducer Tool

### ISSUE THREAD

**Issue by 09viv** [iamrahulmahato/master-web-development#1048]
🔴 Title : Image File Size Reducer Tool
🔴 Tech stack : HTML, CSS, JavaScript, Flask
🔴 Objective : To create a web tool to compress images by reducing their file size based on user-defined quality settings.
🔴 Summary : This project is a Flask-based tool that allows users to upload and compress images by adjusting the quality, reducing file size while maintaining acceptable resolution for storage or web use.

📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Vivek Gazalwar
Participant Role : GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
someone working on it
