### ISSUE TITLE
📃: Spotify Clone 

### ISSUE THREAD

**Issue by Bhumika-00** [iamrahulmahato/master-web-development#1052]
🔴 Title : Spotify Clone 
🔴 Tech stack : HTML CSS Javascript 
🔴 Objective : In our to teach how to make a clone when we cannot inspect the website 
🔴 Summary :It will be a clone of Spotify in a well desired manner.
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name BHUMIKA 
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the are deployment issue so we are no longer accepting any  clone
