### ISSUE TITLE
📃: Typing Speed Test

### ISSUE THREAD

**Issue by Mdraza78** [iamrahulmahato/master-web-development#1053]
**Overview:**
This issue is about creating a new mini project called "Typing Speed Test" using HTML, CSS, and JavaScript. The project will allow users to test their typing speed by typing a given paragraph and providing metrics like words per minute (WPM), accuracy, and mistakes.

**Features to Implement:**

- Random Paragraph: Display a random paragraph for the user to type.

- Typing Area: Provide an input box where the user can type the paragraph.

- Timer: Start a timer as soon as the user begins typing and display the elapsed time.

- Words Per Minute (WPM) Calculation: Calculate the WPM based on how many words the user types correctly and the time taken.

- Live Accuracy Calculation: Calculate typing accuracy by comparing the user’s input with the given paragraph.

- Mistake Count: Show the number of incorrect characters or words typed.

- Restart Option: Provide an option to restart the test with a new random paragraph.

- Responsive Design: Ensure the app works well on different screen sizes using CSS.

**Technology Stack:**

- HTML: To create the structure of the project.

- CSS: To style the input field, timer, and result display areas.

- JavaScript: To handle the logic for the timer, WPM calculation, accuracy, and mistakes.

**Expected Outcome:**

A functional, visually appealing Typing Speed Test app.
Accurate calculations for WPM, accuracy, and mistakes.
User-friendly interface with a responsive design.

**Additional Notes:**

Focus on making the interface clean and easy to use.
Consider adding animations or highlighting the current word being typed to enhance user experience.

**Comment by iamrahulmahato** [comment]
already present in project
