### ISSUE TITLE
🧑‍💻 : ISSUE : WANT TO ADD STONE PAPER SCISSORS GAME

### ISSUE THREAD

**Issue by HarshVardhanSalve** [iamrahulmahato/master-web-development#1054]
:red_circle: **NEW GAME** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : 

### Screenshots 📷

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :HARSHVARDHAN SALVE
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already present in project
