### ISSUE TITLE
🧑‍💻 : Rather than using buttons to navigate user can directly click the card as well

### ISSUE THREAD

**Issue by Anurag519Narula** [iamrahulmahato/master-web-development#1056]
:red_circle: **Title** : Rather than using buttons to navigate user can directly click the card as well
:red_circle: **Enhancement Aim** : Good user interaction
:red_circle: **Changes** : User when clicking the card can access the project rather than manually navigating to it.

### Screenshots 📷
 
![Screenshot (186)](https://github.com/user-attachments/assets/532ace38-d138-4771-a1e6-f10e4837832d)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Anurag Narula
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Anurag519Narula** [comment]
@iamrahulmahato can i take up this issue, please mark this as hacktoberfest as well. Thanks!

**Comment by iamrahulmahato** [comment]
someone working on it
