### ISSUE TITLE
📃: A beautiful travel website 

### ISSUE THREAD

**Issue by Ashish-Patnaik** [iamrahulmahato/master-web-development#1057]
🔴 Title : Destination Delights
🔴 Tech stack : HTML AND CSS
🔴 Objective :To help users to find best destination and hotels according to their budget 
📸 Screenshots
NA

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Ashish Patnaik
Contributer in GSSOC and Hacktoberfest  

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already present in project
