### ISSUE TITLE
📃: Spin the wheel

### ISSUE THREAD

**Issue by infrunamilacym** [iamrahulmahato/master-web-development#1063]
🔴 Title:
Spin the Wheel

🔴 Tech Stack:
HTML
CSS
JavaScript
🔴 Objective:
To create a virtual spinning wheel that randomly selects a result when the user spins the wheel.

🔴 Summary:
The "Spin the Wheel" project provides a fun and interactive way for users to engage with a wheel of fortune. Upon clicking a "Spin" button, the wheel rotates, slowing down until it stops at a random position, displaying the selected outcome. This project demonstrates how randomness, animations, and user input can be used to create an engaging and interactive web experience.

📸 Screenshots:
N/A

✅ Details to Include When Taking the Issue:
Name: Hariom Mandal
Participant Role: Contributor, GSSoC - EXTD, Hacktoberfest

**Comment by sunidhi3** [comment]
@infrunamilacym please assign this to me I will start working on this project as soon as you assign me
