### ISSUE TITLE
🐞 :  Theme Toggler icon button is always showing default option as switch to dark mode where its already in dark mode

### ISSUE THREAD

**Issue by Shariar-Hasan** [iamrahulmahato/master-web-development#1065]
:red_circle: **Title** : Theme Toggler icon button is always showing default option as switch to dark mode where its already in dark mode
:red_circle: **Bug** : always showing default option as switch to dark mode where its already in dark mode
:red_circle: **Changes** :  conditionally change the theme in every reload

### Screenshots 📷
![image](https://github.com/user-attachments/assets/8186857c-a6a8-44a1-853f-3f17fe2f8f64)

************************************************************

✅ Details to Include When Taking the Issue:
Name : Hacktoberfest
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
issue solved

**Comment by Shariar-Hasan** [comment]
hello @iamrahulmahato, is this issue already solved by someone else or just me getting denied to solve the issue?
i am creating issues to solve, so that i can complete my hacktoberfest tasks.
i created another issue, which was also closed. #1027 
dont mind, i am just curious.
