### ISSUE TITLE
📃: Random Quote Generator

### ISSUE THREAD

**Issue by AnanteshG** [iamrahulmahato/master-web-development#1066]
🔴 Title : Random Quote Generator
🔴 Tech stack : HTML, CSS, JS
🔴 Objective : Generates Random Quotes and have the features to copy, share on twitter and also text to speech.
🔴 Summary :
📸 Screenshots

![{078D6660-655D-4198-9A5D-8C5B63DD78AA}](https://github.com/user-attachments/assets/c61c7b1f-f8b5-4325-89e2-f9757328608c)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Anantesh G
Participant Role : GSSoC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by AnanteshG** [comment]
> you can assign this task to me..

This is a PR to add my Code Editor project. Please create your own issue and make a PR if you have a project to be added here.

**Comment by iamrahulmahato** [comment]
already present in project
