### ISSUE TITLE
📃: Music Player 

### ISSUE THREAD

**Issue by saurabh-dev-vns** [iamrahulmahato/master-web-development#1078]
🔴 Title : Music Player 
🔴 Tech stack : HTML , CSS , Javascript 
🔴 Objective : A music player with the following functionalities:
- Play, pause, next, and previous track controls
- Shuffle and repeat modes
- Music slider for tracking progress and controlling playback
- Ability to play specific songs one by one
- A playlist for selecting tracks

🔴 Summary :
📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :  Saurabh Sahani
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by saurabh-dev-vns** [comment]
@iamrahulmahato, please assign this project to me.

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by saurabh-dev-vns** [comment]
@iamrahulmahato, please assign this project to me.

**Comment by iamrahulmahato** [comment]
the project is already present so i am closing the issue, Do not get demotivated and raise new issue
