### ISSUE TITLE
📃: Random fact generator 

### ISSUE THREAD

**Issue by Subashree-selvaraj** [iamrahulmahato/master-web-development#1086]
🔴 Title :Random fact generator
🔴 Tech stack :JavaScript, HTML, CSS
🔴 Objective :Create an application that shows random interesting facts every time a button is clicked.

🔴 Summary :The application will fetch random facts from an API and display them on the screen. Users can click a button to get a new fact.
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Subashree S
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC ext'24
***********************************************************************

Kindly assign it to me under gssoc ext

**Comment by poojapatil34** [comment]
I would like to work on this project .Please assign it to me

**Comment by Subashree-selvaraj** [comment]
The issue was raised by me . kindly assign it to me

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by Subashree-selvaraj** [comment]
@iamrahulmahato Could you please add gssoc ext and level label

**Comment by Subashree-selvaraj** [comment]
@iamrahulmahato Raised PR! Kindly check it
