### ISSUE TITLE
📃: Adding "Rock, Paper, Scissors"

### ISSUE THREAD

**Issue by Bhoomidhanu12** [iamrahulmahato/master-web-development#1092]
🔴 Title :"Rock, Paper, Scissors"
🔴 Tech stack :Html,Css,js
🔴 Objective :Adding new game to this project
🔴 Summary :Players choose rock, paper, or scissors to compete against the computer's random choice.
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Dharani Neelapuram 
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):Gssoc extd

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎
@iamrahulmahato  kindly assign this to me

**Comment by Iampratyush004** [comment]
Kindly reach the project admin for assigning the issue
PA : @iamrahulmahato

**Comment by iamrahulmahato** [comment]
the project is already present so i am closing the issue, Do not get demotivated and raise new issue
