### ISSUE TITLE
🧑‍💻 : Adding a search bar in header

### ISSUE THREAD

**Issue by shubha0503** [iamrahulmahato/master-web-development#1094]
:red_circle: **Title** : Adding a search bar in header
:red_circle: **Enhancement Aim** : Make it easily accessible for user to search for game of their choice
:red_circle: **Changes** : Will be adding search bar in header for easy accessibility

### Screenshots 📷
NA
**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Shubha Singh
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
someone already working on it
