### ISSUE TITLE
📃: Guess the flag game

### ISSUE THREAD

**Issue by Riyachauhan11** [iamrahulmahato/master-web-development#1107]
🔴 Title : Guess the flag game
🔴 Tech stack : html,css,js
🔴 Objective : To guess the country corresponding to the displayed flag image by typing the country name into an input field and submitting the guess.
🔴 Summary :The "Guess the Flag" game presents players with a random flag image from various countries. Players must input their guess for the country name and submit it. The game provides immediate feedback, indicating whether the guess was correct or incorrect. Players can then proceed to the next flag by clicking a button. This interactive game helps users learn about world flags and geography in a fun and engaging way.
📸 Screenshots

N/A
***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Riya Chauhan
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC, Hacktoberfest, Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project is already present so i am closing the issue, Do not get demotivated and raise new issue
