### ISSUE TITLE
📃: Crossy road game 

### ISSUE THREAD

**Issue by ADITYASINGH0175** [iamrahulmahato/master-web-development#1116]
🔴 Title :crossy road game
🔴 Tech stack :html , css , javascript
🔴 Objective : to create a crossy road game
🔴 Summary :a game where we make a chicken cross a road
📸 Screenshots
![image](https://github.com/user-attachments/assets/6e126274-442f-4971-9b28-f2635b9c7d5f)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Aditya Singh
Participant Role : GSSOC , Hactoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project is already present so i am closing the issue, Do not get demotivated and raise new issue
