### ISSUE TITLE
📃: tic tac toe game..

### ISSUE THREAD

**Issue by SaanyaGarg5** [iamrahulmahato/master-web-development#1125]
🔴 Title :tic tac toe
🔴 Tech stack :
🔴 Objective :
🔴 Summary :
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Saanya Garg
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
level 3
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Prathameshzad** [comment]
Please Assign this to me

**Comment by iamrahulmahato** [comment]
the project is already present so i am closing the issue, Do not get demotivated and raise new issue
