### ISSUE TITLE
📃: weather forecasting ..

### ISSUE THREAD

**Issue by SaanyaGarg5** [iamrahulmahato/master-web-development#1126]
🔴 Title :
🔴 Tech stack :
🔴 Objective :
🔴 Summary :
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project is already present so i am closing the issue, Do not get demotivated and raise new issue
