### ISSUE TITLE
📃: ADDING PROFFESSIONAL TYPING SPEED TESTER

### ISSUE THREAD

**Issue by dnyanesh99borse** [iamrahulmahato/master-web-development#1130]
🔴 **Title :** Typing speed tester
🔴 **Tech stack :** html, css and javascript.
🔴 **Objective :** The objective of a typing speed tester is to measure users' typing speed in WPM (words per minute) and accuracy 
                               by 
                        comparing their input with a given text. It should provide real-time feedback, display results, and offer a user-friendly, 
                        customizable interface.
🔴 **Summary :** The Typing Speed Tester is a web application built using HTML, CSS, and JavaScript. It allows users to test and 
                               improve 
                        their typing speed by typing a given text within a set time limit. The application calculates the user's Words Per Minute 
                        (WPM) and typing accuracy by comparing their input to the provided text. Real-time feedback is given to help users 
                        track their progress, highlighting errors and showing live stats. The interface is designed to be user-friendly, providing 
                        customizable test durations and a variety of text samples to choose from. Upon completion, users receive a detailed 
                        summary of their performance, including their typing speed, accuracy percentage, and the number of errors.
📸 **Screenshots**
![image](https://github.com/user-attachments/assets/a904fdea-0ddb-4b99-8e51-ace352314703)
***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Dnyaneshwar Sambhaji Borse.
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC,HACTOBERFEST.

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by dnyanesh99borse** [comment]
SIR AS A WELL DONE AND EXPERIENCED WEB DEVELOPER OR FRONTEND DEVELOPER I AM HUMBLY REQUESTING YOU TO PLEASE ASSIGN THIS ISSUE TO ME . BELEIVE ME I WILL TAKE IT TO THE NEXT LEVEL. @iamrahulmahato

**Comment by dnyanesh99borse** [comment]
SIR I AM REQUESTING YOU TO PLEASE ASSIGN THIS TASK TO ME I AM REQUESTING YOU , I CAN RESOLVE THIS ISSUE EFFECTIVELY

**Comment by iamrahulmahato** [comment]
the project is already present so i am closing the issue, Do not get demotivated and raise new issue

**Comment by dnyanesh99borse** [comment]
OK thankyou
