### ISSUE TITLE
🐞 : Fix and Enhance Game Project Card UI and Footer

### ISSUE THREAD

**Issue by AnushkaChouhan25** [iamrahulmahato/master-web-development#1137]
:red_circle: **Title** : Footer UI and card enhancement 
:red_circle: **Bug** : Improper UI on bottom of the page
:red_circle: **Changes** : The footer and game project card UI are improperly aligned, and the footer lacks a copyright section. Propose improving the layout and design to enhance appearance and add a proper copyright section.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/b9a2e9cb-f486-404c-8b48-a45ea2a5cabe)

************************************************************

✅ Details to Include When Taking the Issue:
Name : Anushka Chouhan
Participant Role : gssoc-extd, hacktoberfest, hacktoberfest-accepted

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
someone working on it,Do not get demotivated and raise new issue

**Comment by AnushkaChouhan25** [comment]
@iamrahulmahato Thank you for your kind words and encouragement.
