### ISSUE TITLE
📃: adding chess game

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [iamrahulmahato/master-web-development#1139]
i want to add a chess game , @iamrahulmahato can i add this.

<img width="577" alt="Screenshot 2024-10-13 at 5 09 06 PM" src="https://github.com/user-attachments/assets/b8dcd155-8401-466a-90cd-1d8d695bbd4f">

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project is already present so i am closing the issue, Do not get demotivated and raise new issue
