### ISSUE TITLE
🐞 : duplicate game

### ISSUE THREAD

**Issue by Anushaburnwal** [iamrahulmahato/master-web-development#1140]
:red_circle: **title** :among us and connect4(two player)
:red_circle: **enhancement** : remove one of the game so that the application would look better 

### Screenshots 📷
![SS](https://github.com/user-attachments/assets/004537a5-5050-48d6-b664-2c671d729a9a)
![SS](https://github.com/user-attachments/assets/53b013b9-f079-4103-9dc7-0dbf5b317a7b)

************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC-extd2024,hactoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
someone working on it,Do not get demotivated and raise new issue
