### ISSUE TITLE
📃: Adding Pomodoro Timer Project

### ISSUE THREAD

**Issue by TanviGandhotra** [iamrahulmahato/master-web-development#1141]
🔴 Title : Adding Pomodoro Timer Project
🔴 Tech stack :html,css,js

The goal of this project is to design a Pomodoro timer with a countdown clock and three buttons: start, stop, and reset. The timer starts at 25 minutes when the start button is clicked, can be paused with the stop button, and resumed with start. The reset button brings the timer back to 25 minutes. An alert notifies the user when the timer reaches zero, helping improve focus and productivity. This is achieved using CSS for styling, event listeners for button actions, and JavaScript's setInterval for the countdown functionality.

Plzz assign me this issue  @iamrahulmahato so i can contribute
Name : Tanvi
Participant Role (hacktoberfest,GSSOC-ext24):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project is already present so i am closing the issue, Do not get demotivated and raise new issue
