### ISSUE TITLE
🧑‍💻 : Dark Mode Not Persisting After Page Refresh

### ISSUE THREAD

**Issue by TyagiManshi** [iamrahulmahato/master-web-development#1145]
:red_circle: **Title** : Dark Mode Not Persisting After Page Refresh
:red_circle: **Enhancement Aim** : Currently, the dark mode setting is lost upon refreshing the page, reverting to the default light mode.
:red_circle: **Changes** : The dark mode setting should persist even after the page is refreshed, maintaining the user's preference for the duration of their session.

### Screenshots 📷

https://github.com/user-attachments/assets/e0acda5a-65e1-41c8-bb64-117d0ce9006c

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Manshi Tyagi | Contributor

Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by TyagiManshi** [comment]
Can you please assign this issue to me

**Comment by Rajanjha12** [comment]
Please assign me this issue my last contribution in shiksha samagam

**Comment by Rajanjha12** [comment]
bhai tum ladki ko deta ho kya assign meri project contribution dekhna eak bar
