### ISSUE TITLE
Styling Color of the vertical scrollbar .

### ISSUE THREAD

**Issue by Tanushree084** [iamrahulmahato/master-web-development#1146]
Hey @iamrahulmahato ,
I want to change the color of the scrollbar as it is not looking proper.
<img width="29" alt="image" src="https://github.com/user-attachments/assets/2c0920d9-3a9b-4818-81b4-2faa4d534c0c">
 can you please assign me this issue?

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :Tanushree Bagde
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):GSSOC CONTRIBUTOR

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by sunidhi3** [comment]
@Tanushree084 please assign this to me I will start working on this project as soon as you assign me
