### ISSUE TITLE
📃: Memory Block Game

### ISSUE THREAD

**Issue by RahulScripted** [iamrahulmahato/master-web-development#1147]
🔴 Title: Memory block game
🔴 Tech stack: HTML, CSS, JS
🔴 Objective: In this game, observe and memorize patterns on blocks, then tap and match them in the correct order to advance through levels. The patterns become more complex as we progress. 
🔴 Summary : 
📸 Screenshots:  Here is a preview of my work

![Screenshot 2024-10-13 100555](https://github.com/user-attachments/assets/27342b21-bd0a-4c8a-a966-c8d779f11bc8)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name: Rahul Goswami
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC, gsoc-extd, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project is already present so i am closing the issue, Do not get demotivated and raise new issue

**Comment by RahulScripted** [comment]
> the project is already present so i am closing the issue, Do not get demotivated and raise new issue

@iamrahulmahato the game is already there I know I raised the issue foe better UI experience
