### ISSUE TITLE
🧑‍💻 : Adding Footer to Website

### ISSUE THREAD

**Issue by satyamra1** [iamrahulmahato/master-web-development#1149]
:red_circle: **Title** : Adding footer 
:red_circle: **Enhancement Aim** : Their will a footer at the end of the page , which contains social links with feedback option.
:red_circle: **Changes** : Adding footer which matches the theme of website.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/44caa024-dc8a-4368-a46e-7980b3a1dc79)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Satyam rai
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC 
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
someone working on it,Do not get demotivated and raise new issue
