### ISSUE TITLE
🧑‍💻 : Add qwerty Keyboard to Hangman Game

### ISSUE THREAD

**Issue by istanujbhatia** [iamrahulmahato/master-web-development#1152]
🔴 Title: Add qwerty Keyboard to Hangman Game

🔴 Bug : Enhancement Aim:
Currently, the Hangman game allows players to input using a "abcdef on the screen keyboard" which is now much user friendly. This enhancement aims to improve the user experience by adding qwerty keyboard functionality, enabling players to type their guesses easily.

🔴 Changes :

Implement qwerty keyboard to detect user input.
Map the keyboard letters to the existing letter selection functionality.
Ensure that both keyboard input and on-screen clicking work seamlessly together.
Update any relevant UI prompts to inform the player of the new input option.
Screenshots 📷
N/A

✅ Details to Include When Taking the Issue:
Name : Tanuj Bhatia (istanujbhatia)
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC Extd, Hacktoberfest

Happy Contributing! 🚀

Feel free to adjust any details to fit your specific approach!

**Comment by iamrahulmahato** [comment]
someone working on it,Do not get demotivated and raise new issue
