### ISSUE TITLE
🧑‍💻 : Add red color on wrong and green for right input

### ISSUE THREAD

**Issue by istanujbhatia** [iamrahulmahato/master-web-development#1153]
🔴 Title: Add red color on wrong and green for right input 

🔴 Bug : Enhancement Aim:
Currently, the Hangman game just disables the button with a light green color either the input is wrong or right  which is now much user friendly. This enhancement aims to improve the user experience .

🔴 Changes :

Just a little color css enhancement 

Screenshots 📷
N/A

✅ Details to Include When Taking the Issue:
Name : Tanuj Bhatia (istanujbhatia)
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC Extd, Hacktoberfest

Happy Contributing! 🚀

Feel free to adjust any details to fit your specific approach!

**Comment by iamrahulmahato** [comment]
someone working on it,Do not get demotivated and raise new issue
