### ISSUE TITLE
📃: Rock Paper Scissors #1154

### ISSUE THREAD

**Issue by Prathameshzad** [iamrahulmahato/master-web-development#1154]
🔴 Title: Rock Paper Scissors
🔴 Tech stack: HTML, CSS, and Javascript
🔴 Objective: Rock-Paper-Scissors aims to choose an option that defeats the opponent's choice according to these 
                       rules: rock beats scissors, scissors beat paper, and paper beats rock.
🔴 Summary: Rock-Paper-Scissors is a simple hand game played between two people. Each player simultaneously forms one of three 
                       shapes: rock, paper, or scissors. The rules determine the winner: rock crushes scissors, scissors cut paper, and 
                        paper covers rock. If both players choose the same shape, the game is a tie. The game is often used for decision-- 
                      making, as a playful contest, or to settle disputes.

📸 Screenshots
![Screenshot 2024-10-13 215353](https://github.com/user-attachments/assets/dd72e8c7-4e27-4e5c-a309-f2c2ce6b70ad)
![Screenshot 2024-10-13 215612](https://github.com/user-attachments/assets/84e0a299-0590-42b0-96f1-f48f9ea03ca5)
![Screenshot 2024-10-13 215353](https://github.com/user-attachments/assets/1af96f20-0850-4345-91d6-bb6a645a9004

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Prathamesh Zad
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC-extd2024

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open-source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project is already present so i am closing the issue, Do not get demotivated and raise new issue
