### ISSUE TITLE
🐞 : Enhance the current UI of the footer

### ISSUE THREAD

**Issue by T-Fathima** [iamrahulmahato/master-web-development#1156]
:red_circle: **Title** : Enhance the current UI of the footer
:red_circle: **Bug** : Not looking interactive 
:red_circle: **Changes** :  
I would like to propose to redesign the footer section by organizing for better readability

### Screenshots 📷

![image](https://github.com/user-attachments/assets/144e904a-84a2-40f7-86a6-3a3410682312)

************************************************************

✅ Details to Include When Taking the Issue:
Name : Tatheer Fathima
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC. Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
someone working on it,Do not get demotivated and raise new issue
