### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by Kajalmehta29** [iamrahulmahato/master-web-development#1161]
<img width="579" alt="Screenshot 2024-10-13 at 11 50 53 PM" src="https://github.com/user-attachments/assets/98b10b65-e74b-4e62-81f2-aea106dde1cb">

It should be "Air Balloon". I want to fix this issue.

Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by VanshGarg06** [comment]
Hi! I am eager to contribute anyhow. Please assign this issue to me.

**Comment by Kajalmehta29** [comment]
@iamrahulmahato Hey, I have done this task. Please merge it.
