### ISSUE TITLE
I want to correct the dimensions of air balloon img dimensions to correct UI

### ISSUE THREAD

**Issue by ananydev** [iamrahulmahato/master-web-development#1164]
I want to correct the dimensions of air balloon img dimensions to correct UI.

Enhancement Aim : I would correct the overlaping part of img.

I would love to work on this project . can you assign it to me 

![image](https://github.com/user-attachments/assets/0696d7cc-e73f-4763-a437-433fef9db5b1)
![image](https://github.com/user-attachments/assets/68a240ee-ea98-4fac-b187-f9614ffed780)

**Comment by iamrahulmahato** [comment]
someone working on it,Do not get demotivated and raise new issue
