### ISSUE TITLE
Implement Responsive Navbar and Layout Adjustments

### ISSUE THREAD

**Issue by Ek-ta-bharti** [iamrahulmahato/master-web-development#1167]
:red_circle: Title :
Implement Responsive Navbar and Layout Adjustments

:red_circle: Enhancement Aim :
To create a responsive navbar that adapts seamlessly to different screen sizes and enhances user experience across all devices.

:red_circle: Changes :

Implement a hamburger menu for mobile view to improve navigation.
Adjust CSS media queries to ensure proper alignment and stacking of content on smaller screens.
Standardize font sizes and styles across navigation items.
Enhance button styles to improve visibility and interactivity on all devices.
Screenshots 📷
N/A

✅ Details to Include When Taking the Issue:
Name : Ekta Bharti
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSoC'24-Extd Contributor

**Comment by iamrahulmahato** [comment]
someone working on it,Do not get demotivated and raise new issue
