### ISSUE TITLE
🐞 : Home page background image is repeating

### ISSUE THREAD

**Issue by sneha056** [iamrahulmahato/master-web-development#1171]
🔴 Title : 🐞 : Home page background image is repeating
🔴 Bug : repeating image in home page
🔴 Changes : Make changes under home page to set property as no-repeat

### Screenshots 📷
![Screenshot 2024-10-14 100040](https://github.com/user-attachments/assets/d73d2a0e-b04f-4cb1-819a-8467e752039e)

************************************************************

✅ Details to Include When Taking the Issue:
Name : Sneha mahajan
Participant Role GSSOC Extd, Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
someone working on it,Do not get demotivated and raise new issue
