### ISSUE TITLE
🐞 : Card image is not loading 

### ISSUE THREAD

**Issue by sneha056** [iamrahulmahato/master-web-development#1172]
🔴 Title : 🐞 : Card image is not loading ,
🔴 Bug : All card contain image , except the card Stick Hero card's image is not loading.
🔴 Changes : Set the path of image correct

### Screenshots 📷
![Screenshot 2024-10-14 074122](https://github.com/user-attachments/assets/89078215-090d-44f7-915e-1a17acd488e5)

************************************************************

✅ Details to Include When Taking the Issue:
Name : Sneha Mahajan
Participant Role GSSOC Extd, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by ishan657** [comment]
Hy @sneha056 
I would love to solve this issue 
Kindly assign me this issue...

**Comment by iamrahulmahato** [comment]
someone working on it,Do not get demotivated and raise new issue
