### ISSUE TITLE
🧑‍💻 : Enhance the feedback form

### ISSUE THREAD

**Issue by rishika105** [iamrahulmahato/master-web-development#1173]
:red_circle: **Enhancing the feedback form** :
:red_circle: **Enhancement increases attentiveness to that page** :
:red_circle: **Adding cross or back to home button, design the form according to the theme , also add a proper area for keeping a feedback form link in the home page** : 

### Screenshots 📷
![image](https://github.com/user-attachments/assets/118f93f7-f73c-4ecd-8927-c1a5b3710f91)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :Rishika Agarwal
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): Contributor - GSSOC EXT

***********************************************************************

Assign me this issue.

**Comment by coder-pink** [comment]
@rishika105 Hi, can you assign this to me? Name: Pinky Singh, Contributor: Hacktoberfest, GSSOC EXT.

**Comment by ishan657** [comment]
Hy @rishika105 
My name is Ishan Sawai participant in hacktoberfest
I would love to solve this issue 
Kindly assign me this issue...

**Comment by iamrahulmahato** [comment]
someone working on it,Do not get demotivated and raise new issue
