### ISSUE TITLE
🧑‍💻 : Feedback section

### ISSUE THREAD

**Issue by shriyadindi** [iamrahulmahato/master-web-development#1179]
:red_circle: **Title** : Feedback section
:red_circle: **Enhancement Aim** : I would like to enhance the feedback section of the webpage 
:red_circle: **Changes** : Enhancing the UI of the feedback section

### Screenshots 📷

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Shriya D
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by sunidhi3** [comment]
@shriyadindi please assign this to me I will start working on this project as soon as you assign me

**Comment by shriyadindi** [comment]
@iamrahulmahato I've made the modifications on the feedback section, kindly go through the new changes made.
