### ISSUE TITLE
📃: Lights out Game

### ISSUE THREAD

**Issue by haseebzaki-07** [iamrahulmahato/master-web-development#1190]
🔴 Title : I want to add lights out game in the project section
🔴 Tech stack :HTML, CSS , JS
🔴 Objective : The objective of this project is to create an interactive grid-based puzzle game where the player must turn off all the lights by clicking on them. Clicking one light toggles its state and the state of the adjacent lights. The game aims to test logical thinking and problem-solving skills.
🔴 Summary : The Lights Out Game is a logic puzzle built using HTML, CSS, and JavaScript. It features a 5x5 grid of lights that can be toggled on and off. The player's task is to turn off all the lights by figuring out the correct sequence of clicks. Each click affects not only the clicked light but also its neighboring lights, adding complexity to the puzzle. The game offers a randomized starting configuration in each round, ensuring fresh challenges every time the game is played. The project showcases interactive game logic, DOM manipulation, and responsive grid layout design, making it a great addition to any portfolio.
📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Haseeb Zaki
Participant Role : GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by ishan657** [comment]
Hy @haseebzaki-07 
My name is Ishan Sawai participant in hacktoberfest
I would love to solve this issue 
Kindly assign me this issue...
