### ISSUE TITLE
🧑‍💻 : Adding paging support in the home page

### ISSUE THREAD

**Issue by Gauravtb2253** [iamrahulmahato/master-web-development#1191]
:red_circle: **Title** :  Adding paging support in the home page
:red_circle: **Enhancement Aim** : Improving performance of website
:red_circle: **Changes** : 

Hello I would like to add paging support on the home page
Currently all games are listed at once I would like to add pages where we can show 12 games at once and remaining in next pages
This will improve performance of website
Pls assign this to me

### Screenshots 📷
N/A

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Gaurav
Participant Role: Hacktoberfest, Gssoc extd

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Someone is already working on it; do not lose heart and raise new issue.
