### ISSUE TITLE
🐞Guessing game : 

### ISSUE THREAD

**Issue by abhisek247767** [iamrahulmahato/master-web-development#1203]
:red_circle: **Negative Score Allowed in Guessing Game** :
:red_circle: **Currently, the game allows the score to go below zero when incorrect guesses are made continuously. This behavior should be prevented, as a score of zero should be the minimum allowed.** :
:red_circle: **Changes** :  Add a check in the checkGuess() function to ensure the score does not drop below zero. If the score reaches zero, stop decrementing it and display a message saying the player has lost the game.
Update the message for when the player runs out of guesses (i.e., score reaches zero).

### Screenshots 📷
N/A

************************************************************

✅ Details to Include When Taking the Issue:
Name : Abhisek Roy
Participant Role Gssoc extd, Hacktoberfest :

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by sahil2431** [comment]
Hi Abhisek Roy,

I’d like to take on this issue! I will add a check in the checkGuess() function to ensure that the score does not drop below zero and will update the message displayed when the player loses.

Looking forward to contributing!

Mohammad Sahil
kindly add these tags GSSOC (extd), Hacktoberfest .
