### ISSUE TITLE
🐞 :  Othello Game Section Not Properly Aligned

### ISSUE THREAD

**Issue by subin-shk** [iamrahulmahato/master-web-development#1208]
:red_circle: **Title** :  Othello Game Section Not Properly Aligned

:red_circle: **Bug** : 
The Othello game section on the webpage is not aligned properly. The game content appears misaligned, which affects the overall layout and consistency of the page. Specifically, the game board seems displaced compared to other sections.

:red_circle: **Changes** :  
Review the CSS applied to the Othello game section, ensuring proper usage of layout techniques like flexbox or grid to maintain alignment. Check margins and padding to ensure consistent spacing with other elements on the page.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/8a436a12-4c0a-40ea-9013-5fa379763cf4)

************************************************************

✅ Details to Include When Taking the Issue:
Name : Subin
Participant Role : GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by sahil2431** [comment]
Hi ,
Name - Mohammad Sahil
Participant Role : GSSOC, Hacktoberfest

I noticed that the Othello game appears twice (one with all the games and one in footer. Should I fix the CSS to adjust the layout, or would you prefer to remove it from footer?

I am Happy to work on it😊.

**Comment by iamrahulmahato** [comment]
Someone is already working on it; do not lose heart and raise new issue.
