### ISSUE TITLE
📃: Rock Paper Scissor game

### ISSUE THREAD

**Issue by lucifer-990** [iamrahulmahato/master-web-development#1209]
🔴 Title : Rock Paper Scissor Game 
🔴 Tech stack : html, css, javascript
🔴 Objective : beat the computer
🔴 Summary : fun interactive game
📸 Screenshots N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : subhajit shaw
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by lucifer-990** [comment]
can you please assign this to me under gssoc and hacktoberfest tag....it would be my first open source contribution

**Comment by iamrahulmahato** [comment]
the project is already present,do not lose heart and raise new issue.
