### ISSUE TITLE
Hover Effects on Cards

### ISSUE THREAD

**Issue by AkshitGarg24** [iamrahulmahato/master-web-development#121]
The cards lack hover effects which should be needed for a better UI experience.

**Comment by riyarane46** [comment]
hii @iamrahulmahato 
 i believe i can do this task efficiently as i have a strong hold over css styling. could you please assign me this task under GSSoC24 extd.

**Comment by iamrahulmahato** [comment]
Sorry to inform you that I do not want to make any changes to the home page. I want to keep it minimal, so I am closing it.
