### ISSUE TITLE
🐞 : Want to improve that Feedback line in bottom

### ISSUE THREAD

**Issue by Gaurav075** [iamrahulmahato/master-web-development#1215]
I want to improve the feedback line in the bottom of the home page. I will improve its CSS and make it attractive. As of now, it detoriates the beauty of the website. Pls assign this issue to me @iamrahulmahato 

I am a Contributor in GSSOC'24 Extd.

![Screenshot (351)](https://github.com/user-attachments/assets/c6ea213c-0045-46ab-acec-4a1d28c200ae)

**Comment by iamrahulmahato** [comment]
someone already working on it,do not lose heart and raise new issue.
