### ISSUE TITLE
🐞 : fix broken layout in homepage,remove duplicates,and update css

### ISSUE THREAD

**Issue by Anandha-Vihari** [iamrahulmahato/master-web-development#1216]
:red_circle: **Title** :fix broken layout in homepage,remove duplicates,and update css
:red_circle: **Bug** :broken layout at end of page
:red_circle: **Changes** :  removed duplicates and updated css

### Screenshots 📷
![image](https://github.com/user-attachments/assets/2b41e96f-f640-4b4f-af28-c1aa1e5568c7)

************************************************************

✅ Details to Include When Taking the Issue:
Name :Anandha-Vihari
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):ggsoc ext level2

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
someone already working on it,do not lose heart and raise new issue.
