### ISSUE TITLE
📃: BMI Calculator using HTML, CSS and JS

### ISSUE THREAD

**Issue by Mahateaa** [iamrahulmahato/master-web-development#1222]
🔴 Title :BMI Calculator
🔴 Tech stack : HTML, CSS and JS
🔴 Objective :An online tool assisting users in determining their BMI based on their weight and height.
🔴 Summary : creating a project which is takes the weight and height of a person as input and calculates the BMI and return output
📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Mahathi N
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC extd, Hacktoberfest 
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Mahateaa** [comment]
@iamrahulmahato can you please assign this to me?

**Comment by Nandini1071** [comment]
Hi @Mahateaa  can you assign this to me would like to contribute on this.

**Comment by iamrahulmahato** [comment]
the project is already present,do not lose heart and raise new issue.
