### ISSUE TITLE
🧑‍💻 : Add navbar in project

### ISSUE THREAD

**Issue by azhar47-sk** [iamrahulmahato/master-web-development#1237]
:red_circle: **Title** : Adding navbar 
:red_circle: **Enhancement Aim** : To add navbar 
:red_circle: **Changes** : 

### Screenshots 📷

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by rohitmore07** [comment]
Hey @iamrahulmahato  I am very keen to work on this issue . I would be really happy if you could assign this issue to me.
Name : Rohit More
Participant : Hacktoberfest

**Comment by iamrahulmahato** [comment]
someone is already working on it,,do not lose heart and raise new issue.
