### ISSUE TITLE
📃: Create a new N-queen game

### ISSUE THREAD

**Issue by Tamanna225** [iamrahulmahato/master-web-development#1239]
🔴 Title : N-queen Game
🔴 Tech stack :  HTML, CSS, JS
🔴 Objective : Place N queens on an N x N chessboard so that no two queens can attack each other
🔴 Summary : The N-Queens problem is a puzzle where you must place N queens on a chessboard of size N×N, ensuring that none of them threaten each other.  This code will have two options one in which the users can play and check if there queens are placed correctly or not and another providing them with solution by visualizing if they cannot solve it by themselves
📸 Screenshots

![Screenshot 2024-10-15 071618](https://github.com/user-attachments/assets/2aac74be-dd1f-45fe-a774-964fb7301a80)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Tamanna
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): Contributer

Please assign me this issue with gssoc-ext and hactoberfest labels

**Comment by iamrahulmahato** [comment]
someone already working on it,do not lose heart and raise new issue.
