### ISSUE TITLE
📃: Add contribution page to it

### ISSUE THREAD

**Issue by sanikamandale17** [iamrahulmahato/master-web-development#1240]
🔴 Title :Add contribution page 
🔴 Tech stack :html/css/js
🔴 Objective :want to add contributors pages
🔴 Summary :
📸 Screenshots

N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Sanika mandale
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by anu098jaiswal** [comment]
what exactly this issue wants like  a page where all the contributers names are mentioned? can you explain it a lil bit
