### ISSUE TITLE
🧑‍💻 : Improvement in UI of feedback page.

### ISSUE THREAD

**Issue by 2004shweta** [iamrahulmahato/master-web-development#1243]
Feedback page can be more animated colorful.we can also add rating system in it.

**Comment by rohitmore07** [comment]
Hey @iamrahulmahato I am very keen to work on this issue . I would be really happy if you could assign this issue to me.

**Comment by iamrahulmahato** [comment]
someone already working on it,do not lose heart and raise new issue.
