### ISSUE TITLE
🧑‍💻 : Fixe  the image position 

### ISSUE THREAD

**Issue by Nbisht1208** [iamrahulmahato/master-web-development#1244]
:red_circle: fixe image position:
:red_circle:  i will fixe the image position
![Screenshot_2024-10-15-10-35-02-364_com android chrome](https://github.com/user-attachments/assets/6ac89835-7c87-46bd-a0cd-0c31f77ec1be)

:red_circle: **Changes** : 

### Screenshots 📷

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by rohitmore07** [comment]
Hey @iamrahulmahato  I am very keen to work on this issue . I would be really happy if you could assign this issue to me.

**Comment by RahulPrasadYadav** [comment]
can you assign the task

**Comment by shauryaq05** [comment]
Hey @iamrahulmahato I am excited and would be very grateful if you could assign this task to me.

**Comment by anu098jaiswal** [comment]
can i get this assigned
