### ISSUE TITLE
📃: To Adding Password Generator Project

### ISSUE THREAD

**Issue by Sadab-Hussain** [iamrahulmahato/master-web-development#1249]
🔴 Title : Password Generator
🔴 Tech stack : HTML, CSS, Javascript
🔴 Objective : To build a user-friendly and customizable password generator that allows users to generate secure passwords by specifying the desired password length and the inclusion of specific character types (uppercase letters, lowercase letters, numbers, and symbols).
🔴 Summary :The Password Generator project aims to provide users with a tool to easily generate strong and secure passwords. With a focus on flexibility and ease of use, the application allows users to customize password characteristics, ensuring the generated password meets their security needs. The generator is designed with a simple, intuitive interface, enabling users to select:
1) Password length (e.g., from 8 to 20 characters)
2) Inclusion of uppercase letters, lowercase letters, numbers, and symbols.

The JavaScript logic ensures that the generated password contains the requested character types, providing a balance between randomness and security. The CSS ensures the layout is responsive, adapting to various screen sizes and making the generator accessible across devices.

📸 Screenshots:

![image](https://github.com/user-attachments/assets/3199cdb3-ff90-4c9d-91a8-78b265cfbb12)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Sadab-Hussain
Participant Role: Contributor @GSSOC, Hacktoberfest.

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by nancy-gupta123** [comment]
Hello! I'd like to work on this issue. Could you please assign it to me?

**Comment by iamrahulmahato** [comment]
I am closing the project because it already exists.
