### ISSUE TITLE
🧑‍💻 : Adding welcome text and description about website

### ISSUE THREAD

**Issue by keerthana2-005** [iamrahulmahato/master-web-development#1254]
:red_circle: **Title** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : 

### Screenshots 📷
![image](https://github.com/user-attachments/assets/d49a2eb9-cdf5-409d-b1aa-1a5a1c3e1a7d)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):GSSOC24 extended ,hacktoberfest accepted,add level also

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
It is there, but because of alignment problems, it appears to be under maintenance.
