### ISSUE TITLE
🧑‍💻 : Fixing the visibility of Project Names in Dark Mode

### ISSUE THREAD

**Issue by Lokesh11868** [iamrahulmahato/master-web-development#1263]
:red_circle: **Title** :Fixing the visibility of Project Names in Dark Mode.
:red_circle: **Enhancement Aim** : To make Project Names visible clearly in Dark Mode.
:red_circle: **Changes** : The Text of the Project Names can be turned into black in Light mode and white in Dark Mode.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/7bdcf488-6507-4531-8a0b-3224ca1826fd)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Lokesh | Contributor
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): gssoc'24-ext, Hacktoberfest.

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by deven065** [comment]
Name : Deven | Contributor
Program Name : Hacktoberfest

Can you please assign this tak to me. I can solve this issue ASAP! I really want to contribute to this issue

**Comment by deven065** [comment]
@iamrahulmahato can you please guide me about the contribution works?
