### ISSUE TITLE
🧑‍💻 : Styling scrollbar wrt the webpage

### ISSUE THREAD

**Issue by richa-k23** [iamrahulmahato/master-web-development#1277]
:red_circle: **Title** : Styling scrollbar wrt the webpage
:red_circle: **Enhancement Aim** : Giving a new style to the current scrollbar so that it's styling matches with the overall webpage.
:red_circle: **Changes** : 

- changing the color of the scrollbar
- giving it a rounded edge
- adding hover effects to the scrollbar

### Screenshots 📷

Current scrollbar -

https://github.com/user-attachments/assets/ace53256-92b6-45ed-8d38-18acae90bcf1

After changes (not with full styling rn, also not appropriate coloring) -

https://github.com/user-attachments/assets/f51e099b-e437-4e94-984f-a2eb34db61b0

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Richa Kalpande
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

- GSSOC-EXT (label: gssoc-ext)
- Hacktoberfest (label: hacktoberfest-accepted)

(Kindly add the level label also)

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by gargantuadev** [comment]
Hello there!
May you kindly assign the issue to me please?

Name: Andrea Mariotti
Participant Role: Hacktoberfest
hacktoberfest-accepted

Thankss!

**Comment by kitiozz** [comment]
please assign this to me under gssoc
