### ISSUE TITLE
🧑‍💻 :  Lacks Contrast in Dark Mode

### ISSUE THREAD

**Issue by neeru24** [iamrahulmahato/master-web-development#1287]
When switching to the dark theme, the main heading in the cards does not stand out and appears with a subtle, dull look. This makes it difficult to distinguish from the rest of the content, reducing readability and the visual appeal of the project. The heading needs to be more prominent to enhance user experience in dark mode.

### Expected Behavior:

- The main heading in each card should have a clear contrast and remain easily readable when dark mode is activated.
- It should be bold or have a higher brightness to make it stand out against the dark background.

Kindly assign me this issue, I'd love to contribute.

### Screenshots 📷
![Screenshot 2024-10-16 061613](https://github.com/user-attachments/assets/333b04bf-0ac5-4861-ad89-08bfc8465ce9)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Neeru (neeru24)
Participant Role : GSSOC-ext, Hacktoberfest, WoB):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by deven065** [comment]
Name : Deven (deven065) 
Program Name : Hacktoberfest

Can you please assign this issue to me?
