### ISSUE TITLE
📃: Currency Convertor

### ISSUE THREAD

**Issue by lade6501** [iamrahulmahato/master-web-development#1288]
🔴 Title : Currency Convertor
🔴 Tech stack : ReactJs
🔴 Objective : Helps user in converting currency value.
🔴 Summary : Using the currency convertor user will be able to get value of any currency compared to another currency e.g 1 INR === 84 dollar 
📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Vishal Lade
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
The project is already present; please do not lose motivation by bringing up new issues.
