### ISSUE TITLE
📃: CSS Grid & Flexbox Playground

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [iamrahulmahato/master-web-development#1291]
🔴 Title : CSS Grid & Flexbox Playground
🔴 Tech stack : HTML, CSS, js
🔴 Objective :Develop an interactive tool where users can experiment with CSS Grid and Flexbox properties. The tool should allow users to visually adjust layout settings and see the code generated in real-time.
🔴 Summary :NA
📸 Screenshots
NA

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): contributor(gssoc-extd)

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by DarshiniKurasa** [comment]
i would like to work on it please assign me this
