### ISSUE TITLE
🐞 :  Homepage Alignment is Not Right

### ISSUE THREAD

**Issue by 4F24L** [iamrahulmahato/master-web-development#1293]
:red_circle: **Title** : Landing page issue
:red_circle: **Bug** : feedback section in the right side
:red_circle: **Changes** :  Feedback section should be in bottom.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/30b77896-13f0-44ea-98d2-0120dec6fdce)

************************************************************

✅ Details to Include When Taking the Issue:
Name : 4F24L [ GSSoC, hacktoberfest ]
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

### Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by 4F24L** [comment]
@iamrahulmahato LANDING PAGE HAS A BUG !!

**Comment by chartak26** [comment]
@iamrahulmahato Please assign this to me I want to contribute in this and make it better.

**Comment by Vanshika-OFFICIAL** [comment]
Please assign it to me.
#GSSoC24 #hacktoberfest

**Comment by DarshiniKurasa** [comment]
i would like to work on it please assign me this
