### ISSUE TITLE
📃: Add Spotify Clone

### ISSUE THREAD

**Issue by haseebzaki-07** [iamrahulmahato/master-web-development#1297]
🔴 Title : Spotify Clone
🔴 Tech stack : html, css, js
🔴 Objective : The objective of this project is to create a fully functional Spotify-like music streaming web application where users can play, pause, skip songs, and view different albums. The application will feature a responsive design, and allow users to control the playback of songs through a seek bar.
🔴 Summary : The Spotify Clone project replicates key functionalities of the popular music streaming platform Spotify using HTML, CSS, and JavaScript. It features an interactive user interface where users can:

Play and Pause Music: Users can play a song and pause it using play/pause buttons.

Next and Previous Songs: Users can skip to the next song or go back to the previous one.

Albums and Playlists: Users can browse different albums and playlists, and play songs from them.

Seekbar and Playback Control: A seek bar is included to show the current progress of the song, and users can drag it to jump to a specific part of the song.

Responsive Design: The clone adapts to different screen sizes, ensuring a smooth experience across devices.
📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Haseeb Zaki
Participant Role : GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Previously, three was a Spotify clone, but we are not accepting it at this time due to a deployment issue, so I am closing the ticket.
