### ISSUE TITLE
🐞 : URGENT fix the alignment

### ISSUE THREAD

**Issue by iamrahulmahato** [iamrahulmahato/master-web-development#1307]
![Screenshot 2024-10-16 142447](https://github.com/user-attachments/assets/8b99156a-c8e4-4eee-9f0c-7229ca87e9b5)

**Comment by deven065** [comment]
Can you please assign this isuue to me and add tag as Hactoberfest I am actively fixing this issue

**Comment by iamrahulmahato** [comment]
are you familiar with the alignment and seen the previous version of it

**Comment by iamrahulmahato** [comment]
and have to ever contributed in this project

**Comment by deven065** [comment]
Yes I am familiar with the alignment although I don't seen previous version of it neither I contributed on this project before and I am new to GitHub contributions

**Comment by abhisek247767** [comment]
you can simple revert back the PR for priority basis

**Comment by deven065** [comment]
> you can simple revert back the PR for priority basis

What is that ? Can you please guide me ?

**Comment by deven065** [comment]
> and have to ever contributed in this project
##Help
Can you please share photo of exactly how you want it to be?

**Comment by iamrahulmahato** [comment]
![Web capture_16-10-2024_19616_](https://github.com/user-attachments/assets/9c95929b-e44e-496f-b5f3-3fb97d9ba109)

**Comment by iamrahulmahato** [comment]
![Web capture_16-10-2024_19720_](https://github.com/user-attachments/assets/30fdb312-6d46-429b-9f7d-fee4b598f369)

**Comment by deven065** [comment]
Thank you for the reference

**Comment by shivisingh25** [comment]
@iamrahulmahato ,I've fixed this issue.May I create PR for this issue.
![Screenshot 2024-10-16 225028](https://github.com/user-attachments/assets/f2d02e06-df50-4da7-a70d-ee6a5c23b3bc)
![Screenshot 2024-10-16 225041](https://github.com/user-attachments/assets/ef9cf89d-5af8-4ba6-a3e4-b47879f5ec17)
![Screenshot 2024-10-16 225059](https://github.com/user-attachments/assets/cc621ef6-d527-4fd5-967a-48909ffc5d0c)

**Comment by iamrahulmahato** [comment]
okay

**Comment by shivisingh25** [comment]
@iamrahulmahato,Work has been completed.Please review it.

**Comment by shivisingh25** [comment]
@iamrahulmahato ,Watch this video it is working smoothly.
https://github.com/user-attachments/assets/fb14149e-967f-4e6f-9b6f-4c412b73dbb0

**Comment by iamrahulmahato** [comment]
I am closing this issue because it is resolved.
