### ISSUE TITLE
📃: Add new project Random Quote Generator

### ISSUE THREAD

**Issue by Sumanth077s** [iamrahulmahato/master-web-development#1313]
🔴 Title : Random Quote Generator
🔴 Tech stack :HTML,CSS,JS
🔴 Objective : to generate a random quote
🔴 Summary : The Random Quote Generator is a simple web project built with HTML, CSS, and JavaScript. It displays a new quote each time the user clicks a button. The quotes are stored in an array, and JavaScript selects one randomly to display. This project helps practice basic DOM manipulation and event handling while offering opportunities to improve styling with CSS.
📸 Screenshots
![random quote generator](https://github.com/user-attachments/assets/63767f5a-c15d-4979-ac9b-9a9c69d72643)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Sumanth U
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): Contributer at both hacktoberfest and GSSoC24 ext

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Lakshita-Kumawat** [comment]
I would like to work on this project

**Comment by Sumanth077s** [comment]
It's done

**Comment by Lakshita-Kumawat** [comment]
You mean it is already completed?
