### ISSUE TITLE
📃: Flip Card Memory Game

### ISSUE THREAD

**Issue by Kiran-Jadhav200** [iamrahulmahato/master-web-development#1318]
🔴 Title : Flip Card Memory Game
🔴 Tech stack : HTML, CSS, Javascript
🔴 Objective :A memory-matching game where players flip cards to reveal images or symbols, aiming to find matching pairs by remembering the card positions.
🔴 Summary : Assign This issue to me 
📸 Screenshots
![image](https://github.com/user-attachments/assets/f1579528-5937-4a84-bf83-46e2c1be68cc)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Kiran Jadhav
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): gssoc-ext

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
