### ISSUE TITLE
🐞 :  Home page UI not correct

### ISSUE THREAD

**Issue by Gauravtb2253** [iamrahulmahato/master-web-development#1319]
:red_circle: **Title** : Home page UI not correct
:red_circle: **Bug** : The content is not scrollable 
:red_circle: **Changes** :  

The home page UI is not correct I would like to solve it
pls assign me

### Screenshots 📷

![image](https://github.com/user-attachments/assets/e72aa47c-8b1a-469c-8803-5f06bc2976fd)

************************************************************

✅ Details to Include When Taking the Issue:
Name : Gaurav 
Participant Role: Hacktoberfest, gssoc extd

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
![Web capture_16-10-2024_19616_](https://github.com/user-attachments/assets/46a9ae7f-a460-4f49-84e5-33dc559fd01b)
![Web capture_16-10-2024_19720_](https://github.com/user-attachments/assets/679db82b-d04c-4c4a-a8fb-0eff55b3375e)

**Comment by iamrahulmahato** [comment]
for reference, do it as fast as possible

**Comment by iamrahulmahato** [comment]
i am closing the issue as it is solved
