### ISSUE TITLE
📃: Car Rental Website

### ISSUE THREAD

**Issue by RahulScripted** [iamrahulmahato/master-web-development#1326]
🔴 Title : Car Rental website
🔴 Tech stack : HTML< CSS & JavaScript
🔴 Objective : Landing Page of Car Rental website
🔴 Summary :
🔴 Live Preview : https://gilded-kelpie-4a2814.netlify.app/#

📸 Screenshots

![Screenshot 2024-10-16 204222](https://github.com/user-attachments/assets/0200648a-ce6b-48d9-baaf-64de753ec8d5)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Aakarshit07** [comment]
@RahulScripted Can i work on this issue ?
Aakarshit Choudhary
GSSOC, Hacktoberfest
