### ISSUE TITLE
🐞 : URGENT FIX THE USER INTERFACE OF THE MAIN LANDING PAGE

### ISSUE THREAD

**Issue by dnyanesh99borse** [iamrahulmahato/master-web-development#1328]
:red_circle: **Title** : **URGENT FIX THE USER INTERFACE OF THE MAIN LANDING PAGE**
:red_circle: **Bug** : THE USER INTERFACE OF THE WEBSITE'S HOME PAGE IS TOTALLY DISTRUBE 
:red_circle: **Changes** :   I WILL REVIEW THE CODE OF THE WHOLE USER INTERFACE OF TEH WEBSITE AND THEN BY ANALYSIS I WILL REARRANGED THE CODE AND WILL PROVIDE THE INTERACTIVE USER INTERFACE TO THE WEBSITE. 

### Screenshots 📷

![image](https://github.com/user-attachments/assets/ac6e49ad-d271-45c3-b7ab-a2072bcdc668)

************************************************************

✅ Details to Include When Taking the Issue:
Name : Dnyaneshwar Sambhaji Borse
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
fixed
