### ISSUE TITLE
📃: TO do list web application using html , css and js

### ISSUE THREAD

**Issue by shraddhabaghel** [iamrahulmahato/master-web-development#1335]
🔴 Title : TO DO list
🔴 Tech stack : HTML , CSS , jAVASCRIPT
🔴 Objective : To manage daily work schedule 
🔴 Summary :A clean and intuitive layout with an input field for new tasks, a button to add tasks, and a list to display tasks.
📸 Screenshots: 
![to do snap](https://github.com/user-attachments/assets/5e8cb947-426d-441c-aeb5-6d650711b924)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Please mention GSSOC extended, Hacktoberfest
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
