### ISSUE TITLE
Add GitHub icon 

### ISSUE THREAD

**Issue by nilesh-fatfatwale** [iamrahulmahato/master-web-development#134]
Add GitHub icon inside next to view source code

**Comment by Abankita** [comment]
Please assign it to me, and label it under gssoc ext and level 1

**Comment by iamrahulmahato** [comment]
@nilesh-fatfatwale can you show the ui or any preview which you are telling

**Comment by nilesh-fatfatwale** [comment]
![image](https://github.com/user-attachments/assets/a93cf634-f45c-404b-b9d2-cf0b8a686f8b)
 
it will be more informative than just normal text 
either replace all text and place Github icon  or may be both text and icon also good

**Comment by 4F24L** [comment]
Can I work on this ? As I am a beginner to Open-Source !

**Comment by 4F24L** [comment]
As the github icon should be added on the home screen. If the guidelines says, We should not do any change on the home screen then how can we change that div ?

**Comment by sheetalchaurasia21** [comment]
@nilesh-fatfatwale Please assign this to me.

**Comment by DarakshanSaara** [comment]
Please assign this issue to me.

**Comment by 4F24L** [comment]
Can you assign me ? As I already made a PR earlier . @iamrahulmahato

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
