### ISSUE TITLE
📃: Quiz Game with API

### ISSUE THREAD

**Issue by AnanteshG** [iamrahulmahato/master-web-development#1342]
🔴 Title : API Quiz Game
🔴 Tech stack : HTML CSS JS
🔴 Objective : This game gest questions and answers from API and you don't need to manually add questions to it! also you can choose difficulty and category of questions and also number of questions. it also add points to your score depending on time that you answered the question
🔴 Summary :
📸 Screenshots
![screenshot](https://github.com/user-attachments/assets/a9d80990-d6ac-4c5b-b220-d2f7b8f91f7f)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Anantesh G
Participant Role : GSSOC, Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.

**Comment by AnanteshG** [comment]
> Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
> 

No problem!
@iamrahulmahato can I add ReactJS and NextJS projects here?

**Comment by AnanteshG** [comment]
> > Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
> 
> No problem! @iamrahulmahato can I add ReactJS and NextJS projects here?

@iamrahulmahato ?

**Comment by AnanteshG** [comment]
@iamrahulmahato ?
