### ISSUE TITLE
📃:  Create a Fully Functional Chess Game 

### ISSUE THREAD

**Issue by sanikamandale17** [iamrahulmahato/master-web-development#1348]
🔴 Title : Create a Fully Functional Chess 
🔴 Tech stack :
🔴 Objective :develop a fully functional chess game that allows two players to play against each other on a standard chessboard the game should validate piece movements according to chess rules and manage player turns.
🔴 Summary :to build an interactive chess game that follows the official chess rules the game will involve move validation for each piece, alternating player turns, and a visual representation of the board
📸 Screenshots

n/a
***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC
plz assign this task to me @iamrahulmahato 
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
