### ISSUE TITLE
📃: Want to Add to-do-list

### ISSUE THREAD

**Issue by sanikamandale17** [iamrahulmahato/master-web-development#1351]
🔴 Title :Want to Add to-do-list
🔴 Tech stack :
🔴 Objective :A task management app where users can add, edit, and delete tasks. Implement features like deadlines, task categories, and priorities
🔴 Summary : want to add to do list so helps to write down aur tasks and many more
📸 Screenshots

n/a
plz assign me this task @iamrahulmahato 
***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
The project already exist, Do not be demotivated and raise a new issue.
