### ISSUE TITLE
📃: Want to Add calendar

### ISSUE THREAD

**Issue by sanikamandale17** [iamrahulmahato/master-web-development#1352]
🔴 Title :want to add calendar
🔴 Tech stack :
🔴 Objective :Implement a simple, interactive calendar that displays the current month and allows users to navigate between months.
🔴 Summary :the calendar feature will enable users to view the current month, navigate to previous and next months, and see the corresponding dates, all enhanced with interactive colors and hover effects to improve usability and engagement.
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
The project already exist, Do not be demotivated and raise a new issue.
