### ISSUE TITLE
🐞 : Remove duplicate cards

### ISSUE THREAD

**Issue by Abankita** [iamrahulmahato/master-web-development#1363]
:red_circle: **Title** :Remove duplicate project cards
:red_circle: **Bug** : There are multiple cards for some projects in index.html
:red_circle: **Changes** :   I will remove the duplicate ones without breaking any existing functionality.

### Screenshots 📷

![Screenshot_2024-10-17-20-09-40-846_com android chrome (1)](https://github.com/user-attachments/assets/77c62c69-be9c-4716-a195-c0bb1dde4860)

************************************************************

✅ Details to Include When Taking the Issue:
Name : Abankita 
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):GSSoC and Hacktoberfest contributor

***********************************************************************
@iamrahulmahato

**Comment by aastikdas** [comment]
Hi @Abankita 

I’d like to take up this task: Remove Duplicate cards https://github.com/iamrahulmahato/master-web-development/issues/1363#top. I’m confident I can complete it and contribute to the project.

Could you please assign it to me? I’ll make sure to deliver by the deadline and follow the project’s guidelines closely. If there are any specific requirements or preferences, feel free to let me know.

Looking forward to your approval!

Thanks
