### ISSUE TITLE
🧑‍💻 : 

### ISSUE THREAD

**Issue by chamaneth** [iamrahulmahato/master-web-development#1365]
:red_circle: **Astronomy picture of the day** :
:red_circle: **making design more attractive and fixing alignments** :
:red_circle: **Changes** : 

### Screenshots 📷

![image](https://github.com/user-attachments/assets/4ac10ff3-b422-49f9-8057-aa8454bdfe62)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Chamathka Nethmini
Participant Role (Hacktoberfest):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
