### ISSUE TITLE
Add a Drum-Kit game

### ISSUE THREAD

**Issue by Meghana-Poojary** [iamrahulmahato/master-web-development#138]
![image](https://github.com/user-attachments/assets/cf78d7d2-c2d3-4a5f-9bb0-aab56330486a)
This game allows the user to play the drum virtually and they can user either keys on keyboard or mouse to play drum.                  Please assign me this work !!!Please

**Comment by Meghana-Poojary** [comment]
I have added both Simon game and drum kit within the same pull request

**Comment by brewcoder6113** [comment]
assign me under hacktoberfest'24
