### ISSUE TITLE
🧑‍💻 : want to add play button in Brick Breaker game

### ISSUE THREAD

**Issue by Ronnit44** [iamrahulmahato/master-web-development#1386]
:red_circle: **Title** : to add a play button in the Brick Breaker game
:red_circle: **Enhancement Aim** : It will improve the user experience
:red_circle: **Changes** : Game will not directly start and user will have to click on play button to start the game

### Screenshots 📷

N/A

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Ronnit Sagar
Participant Role : GSSOC,Hacktoberfest

***********************************************************************

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
