### ISSUE TITLE
Simple Calender Web App using HTML CSS JS

### ISSUE THREAD

**Issue by MOHAMMED-IQRAMUL** [iamrahulmahato/master-web-development#139]
Hello,

I am interested in contributing to the project by developing a simple calendar web application using HTML, CSS, and JavaScript. 
This calendar app will provide users with a straightforward and user-friendly interface.
It will be a fully responsive web app

Could you please assign this issue to me?

Thank you for considering my request. I look forward to your response.

Also Please add The Hacktoberfest tag

**Comment by Apeksha-22** [comment]
Please assign it to me
