### ISSUE TITLE
📃: Git profile View website using React, Tailwind CSS,and Daisy UI 

### ISSUE THREAD

**Issue by SHRIVISHNU-CM** [iamrahulmahato/master-web-development#1392]
🔴 Title :Git Profile View
🔴 Tech stack : React, Tailwind CSS, Daisy UI 
🔴 Objective: To make dynamic web app for users to search git users.
🔴 Summary :In this web app client can able search git profile of others. This includes number of repos, Location, and so on.

✅ Details to Include When Taking the Issue:
Name : Shri Vishnu C M (GSSOC 2024 Extd,)
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 
@iamrahulmahato PLEASE ASSIGN THIS TASK TO ME.

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
