### ISSUE TITLE
📃: Add a Human Rights Website "Legally You" Built with HTML and CSS

### ISSUE THREAD

**Issue by poojabagodi** [iamrahulmahato/master-web-development#1393]
🔴 Title : Add a Human Rights Website "Legally You" Built with HTML and CSS
🔴 Tech stack :HTML,CSS
🔴 Objective :To create a simple website called "Legally You" that provides information about human rights using only HTML and CSS.

🔴 Summary :The "Legally You" website will offer static content on human rights, designed with basic HTML and CSS for desktop use. The layout includes a navigation bar and informational sections. This contribution is ideal for beginners looking to practice fundamental web design without focusing on responsiveness. Future enhancements can include mobile optimization.

📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :pooja
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):GSSOC

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by poojabagodi** [comment]
i would like to work on it please assign me this

**Comment by DarshiniKurasa** [comment]
i would like to work on it please assign me this
