### ISSUE TITLE
📃: add my mern project "Paisa-Pal" is expense tracking application

### ISSUE THREAD

**Issue by REHAN-18** [iamrahulmahato/master-web-development#1396]
🔴 Title  :Paisa-Pal
🔴 Tech stack :  MERN stack (MongoDB, Express, ReactJS, and Node.js).
🔴 Objective : To provide users with an easy-to-use platform for tracking and managing their daily, weekly, or monthly expenses while offering insightful analysis to help them manage their finances more effectively.
🔴 Summary : Paisa-Pal is a comprehensive expense tracking application designed with the MERN stack. It enables users to seamlessly create, update, and delete expenses while providing visual insights into their spending patterns over time. With a user-friendly interface and analytical tools, it helps individuals gain better control of their finances.
📸 Screenshots: 
<img width="1394" alt="Screenshot 2024-10-18 at 7 19 19 PM" src="https://github.com/user-attachments/assets/37fb264a-12ae-440a-964d-fb8dbd046eb1">

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : MD REHAN
Participant Role :- GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
