### ISSUE TITLE
🧑‍💻 : UI should be improved in Dark Mode

### ISSUE THREAD

**Issue by Sivasaiklu** [iamrahulmahato/master-web-development#1398]
:red_circle: **Title** : UI improvements in dark mode
:red_circle: **Enhancement Aim** : while in dark mode some text is not visible clearly, it should be changed
:red_circle: **Changes** :  colors of the text in dark mode needs to change

### Screenshots 📷
![image](https://github.com/user-attachments/assets/4bc1b595-292d-49b1-a1a9-42fe58ad1cfe)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Sivasai Nukala
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): Contributor 

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Nayanbatman** [comment]
Can you please assign me the issue ?

**Comment by iamrahulmahato** [comment]
it is fixed.Do not be demotivated and raise a new issue.
