### ISSUE TITLE
📃: add Event Planner

### ISSUE THREAD

**Issue by Riyachauhan11** [iamrahulmahato/master-web-development#1400]
🔴 Title :Event Planner
🔴 Tech stack : html, java, css
🔴 Objective : I would like to add a project that allows users to mark important events on a calendar and have them displayed in real-time.
📸 Screenshots

N/A
***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Riya Chauhan
Participant Role  GSSOC, Hacktoberfest, Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
