### ISSUE TITLE
📃: Progress bar while scrolling down 

### ISSUE THREAD

**Issue by Priyanshi0112** [iamrahulmahato/master-web-development#1403]
🔴 Title :Progress bar while scrolling down 

🔴 Tech stack : HTML,CSS ,JS

🔴 Objective :The objective of adding a progress bar while scrolling down a website is to enhance user experience by providing visual feedback on their scrolling progress. This feature allows users to easily gauge how much content they have explored and how much is remaining, improving navigation and engagement, particularly on content-heavy or long-scroll pages.

🔴 Summary :A scroll progress bar visually indicates the user's position on a webpage as they scroll. Typically placed at the top of the page, it adjusts dynamically in response to the user's scrolling behavior. This feature is useful for improving user engagement, reducing bounce rates, and providing a more intuitive navigation experience, especially on longer pages such as blogs, articles, and e-commerce product listings. The progress bar can be styled to fit seamlessly with the design of the website and enhance its functionality.

📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
