### ISSUE TITLE
UI Improvements for Button Visibility, Alignment, and Font Consistency

### ISSUE THREAD

**Issue by Kavish-Paraswar** [iamrahulmahato/master-web-development#1404]
The "Show More" button is not clearly visible, and its alignment is inconsistent.
The alignment of game images requires improvement for a more organized and consistent layout.
![image](https://github.com/user-attachments/assets/44b3b630-aa12-4a68-85c3-783b5bcca6e5)

The "Slide More" text is displayed twice. This duplication needs to be resolved for clarity.

![image](https://github.com/user-attachments/assets/0c8d614e-6f3e-4f08-9e40-7abd792ab1c6)

The overall UI requires updates for better font selection and alignment consistency. Improving these aspects will enhance the visual appeal and usability of the interface.
![image](https://github.com/user-attachments/assets/46e03eea-70af-44d0-8467-cd0151ba559f)

Can see 3 large pictures making UI not visually apealing.
![image](https://github.com/user-attachments/assets/7e7b7c56-138c-4f41-b474-d382a788ed78)

**Comment by sakthijaw** [comment]
can you assign this project to me . I can work on this.

**Comment by Nayanbatman** [comment]
can you assign this project to me . I can work on this.

**Comment by Kavish-Paraswar** [comment]
why did reomove level 2 .please assign level for the amount of work
