### ISSUE TITLE
Implement a "Back" Button for Navigating to the Previous Page

### ISSUE THREAD

**Issue by ManjeshGowda06** [iamrahulmahato/master-web-development#1412]
Hi @iamrahulmahato  To implement a "Back" button on a webpage that allows users to navigate back to the previous page
The current website lacks a "Back" button, which would allow users to easily return to the previous page they were on before being redirected. This feature will enhance user experience, especially in cases where users want to go back without manually using the browser's back button. The "Back" button should function correctly across various pages and devices, including desktop and mobile.

please assign this work to me under Gssoc ext 24 and HACTOBERFEST24 ITS MY KIND REQUEST TO U @iamrahulmahato .

https://www.loom.com/share/71cc8abea8e044bb8bc7d8d283b61391?sid=8ca9cd6a-0ba9-4aa7-a297-7a1ba9d1304e

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
