### ISSUE TITLE
🐞 : Misalignment of Left-Right Icon

### ISSUE THREAD

**Issue by Nayanbatman** [iamrahulmahato/master-web-development#1414]
Hi @iamrahulmahato

🔴 Title : Alignment of Icons
🔴 Bug : The left and right icon is above the text of air ballon
🔴 Changes : The left and the right icon should be alinged properly in order that the overall visual harmony is maintained  

![Screenshot 2024-10-19 011229](https://github.com/user-attachments/assets/6e8f23cd-8566-4a72-99e7-dae9a0596145)

**Comment by Nayanbatman** [comment]
Please Rahul assign me this issue . I can fix it . That's my humble request to you

**Comment by iamrahulmahato** [comment]
it is fixed. Do not be demotivated and raise a new issue.

**Comment by Nayanbatman** [comment]
> @iamrahulmahato can you please assign me any issue that i can fix for you .
