### ISSUE TITLE
📃: 

### ISSUE THREAD

**Issue by meghanakn473** [iamrahulmahato/master-web-development#1416]
🔴 Title : Brick breaker game
🔴 Tech stack : html css javascript
🔴 Objective : A classic arcade game where the player controls a paddle and has to break all bricks by bouncing a ball.
The challenge is to keep the ball in play while breaking all the bricks on the screen.
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Meghana
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): gssoc-extd, hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by meghanakn473** [comment]
@iamrahulmahato please assign this issue to me under level 3, gssoc-extd

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
