### ISSUE TITLE
🧑‍💻 :  Move Feedback Section to Footer & Add Contact Us Form

### ISSUE THREAD

**Issue by Ayan-Khan79** [iamrahulmahato/master-web-development#1421]
:red_circle: **Title** : Move Feedback Section to Footer & Add Contact Us Form
:red_circle: **Enhancement Aim** : 

- Relocate the feedback section from the middle of the games section to the footer.
- Add a new "Contact Us" form to the footer for better user engagement.

:red_circle: **Changes** : 

1.Move Feedback Section:
 - Relocate the existing feedback form to the footer section at the bottom of the page.
 
2.Add Contact Us Form:
 - Add a "Contact Us" form in the footer that collects user name, email, and message. Include a submit button with appropriate form validation.
 
3.Footer Layout Adjustments:
 - Adjust the layout of the footer to ensure the new feedback section and contact form integrate seamlessly, maintaining a clean and responsive design.

4.Enhance Footer Links and Styling:
 - Make minor updates to the footer styling and ensure all social media/contact links are easily accessible.

### Video 📷

https://github.com/user-attachments/assets/3d274ca1-a1ef-47c3-a1eb-aae41f0a3e11

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Ayan Khan
Participant Role : GSSOC, Hacktoberfest

***********************************************************************
@iamrahulmahato Please review this enhancement and assign this  to me , so I can start working on it....

**Comment by iamrahulmahato** [comment]
can you share the footer ui , i dont want to add footer in it

**Comment by Ayan-Khan79** [comment]
This will be the footer which will match the website's UI and if you want I can make other changes also and I will add a short contact us form also for user engagement.
![image](https://github.com/user-attachments/assets/9d6ee924-9cbf-4545-9b48-e71042e03c4a)

And this is the video reference to check the transitions on links and social icons...



https://github.com/user-attachments/assets/3cbf24e2-53f7-4205-aeed-32871431641d

@iamrahulmahato If you liked it, then please assign me this and I can proceed further to implement in the website
