### ISSUE TITLE
🧑‍💻 : adding hacktober gssoc fest logos to the readme

### ISSUE THREAD

**Issue by REHAN-18** [iamrahulmahato/master-web-development#1422]
:red_circle: **Title** :  adding hacktober gssoc fest logos to the readme
:red_circle: **Enhancement Aim** : modified readme will enhance the repo
:red_circle: **Changes** :  adding  hacktober gssoc fest logos  & modified readme

### Screenshots 📷
<img width="989" alt="Screenshot 2024-10-18 at 11 57 18 PM" src="https://github.com/user-attachments/assets/66886c05-9bcf-4e04-83a6-c0e7feadfd86">
LIKE THIS 👆🏻

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : MD REHAN
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):  GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by REHAN-18** [comment]
BRO GIVE GSSOC & Hacktoberfest LABEL.

**Comment by REHAN-18** [comment]
@iamrahulmahato bro done !!☑️

**Comment by iamrahulmahato** [comment]
![Web capture_19-10-2024_151153_github com](https://github.com/user-attachments/assets/ea6bdf8c-5687-41dc-b6c4-890a2ee79c4f)
also fix this issue because i cant give you any level for just adding a img

**Comment by REHAN-18** [comment]
ok !!  I will do it 👍🏻

**Comment by REHAN-18** [comment]
**done this !! THIS THE PR & MERGE ITS**
