### ISSUE TITLE
📃: Adding search filter in search bar

### ISSUE THREAD

**Issue by sayanp607** [iamrahulmahato/master-web-development#1424]
🔴 Title :Adding search filter in search bar to find if the game exits
🔴 Tech stack :HTML,CSS,JS
🔴 Objective :help user finding out the exact game and show suggestions  according to user's search.
🔴 Summary :User don't need to scroll down to find the game, the suggestions will appear and after clicking it, user can redirect to the game page 
📸 Screenshots

https://github.com/user-attachments/assets/3ebe1788-a45b-4651-a193-f467ff112bd2

Here , on typing the game name, if the game exits in the website then it will appear as suggestion.

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest.

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
ok but make sure ui matches with the website

**Comment by sayanp607** [comment]
> ok but make sure ui matches with the website

Sure .

**Comment by Abhijais4896** [comment]
hey @sayanp607 , Assign me this issue i will definitely fix this issue.
