### ISSUE TITLE
📃: Add a sign up and login page.

### ISSUE THREAD

**Issue by sayanp607** [iamrahulmahato/master-web-development#1427]
🔴 Title :Adding a sign up and login page to authenticate the user.
🔴 Tech stack :HTML,CSS,JS
🔴 Objective :create a login and sign up button  in the header that will redirect to respective pages accordingly.
🔴 Summary :Both the pages will be fully functional and responsive also.
📸 Screenshots

![Screenshot 2024-10-19 111343](https://github.com/user-attachments/assets/f548fc9d-fd01-4622-9a7d-772f0400da3f)
![Screenshot 2024-10-19 111349](https://github.com/user-attachments/assets/fa9f0559-55e6-43d5-ba19-94517557eb46)

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

GSSOC, Hacktoberfest

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
i don't want to add sign-up page and login page in home page as i want everyone to visit the website without any restriction
