### ISSUE TITLE
📃: ADD New Project Digital Clock with Dark mode

### ISSUE THREAD

**Issue by Sumanth077s** [iamrahulmahato/master-web-development#1431]
🔴 Title : Digital Clock with Dark Mode
🔴 Tech stack : HTML,CSS,JS
🔴 Objective :Create a digital clock application with a theme switcher that dynamically changes the background and button colors between light and dark modes.
🔴 Summary :N/A
📸 Screenshots
![digital clock](https://github.com/user-attachments/assets/b06337de-7fde-49e8-8421-c52c3eac7d4a)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Sumanth U
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):Contributer at GSSoC and Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
