### ISSUE TITLE
📃: Add wynk music clone

### ISSUE THREAD

**Issue by Aman8471** [iamrahulmahato/master-web-development#1436]
🔴 Title :WYNK MUSIC CLONE
🔴 Tech stack :CSS JAVASCRPT HTML
🔴 Objective :
🔴 Summary :
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :AMAN KUMAR MAURYA

Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
We are currently dealing with some deployment issues, so we are not adding any more website clones. Please do not become discouraged and report any new issues.
