### ISSUE TITLE
📃: Add a New Project Personal Blog Website 

### ISSUE THREAD

**Issue by Sumanth077s** [iamrahulmahato/master-web-development#1445]
🔴 Title : Personal Blog Website 
🔴 Tech stack : Html Css Js
🔴 Objective : a Blog Website 
🔴 Summary :N/A
📸 Screenshots: N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Sumanth U
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): Contributor at gssoc and hacktober fest 

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
