### ISSUE TITLE
Want to add the Picture for "Guess the Shape" Game.

### ISSUE THREAD

**Issue by ShaikHafiza** [iamrahulmahato/master-web-development#1447]
Currently, "Guess the Shape" Game doesn't have a display picture.
The image will serve as a visual clue for players to identify the Game.
![Screenshot 2024-10-19 160021](https://github.com/user-attachments/assets/6498b92f-62b4-43ad-ba3c-a91c1854b5ca)

Please, assign me this issue...

**Comment by iamrahulmahato** [comment]
you have raise the same issue two time closing it
