### ISSUE TITLE
📃: ADD A NEW QUIZ GAME🧠✨

### ISSUE THREAD

**Issue by shriyadindi** [iamrahulmahato/master-web-development#1450]
🔴 Title :QUIZ GAME
🔴 Tech stack :HTML, CSS, JS
🔴 Objective :ADDITION OF NEW GAME
🔴 Summary :I would like to add a new project to the website 
📸 Screenshots

![Screenshot 2024-10-19 174459](https://github.com/user-attachments/assets/315c481f-ce07-463b-8950-37635584346e)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Shriya Dindi
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
