### ISSUE TITLE
📃:words are going on edges away from display and not showing. correctly

### ISSUE THREAD

**Issue by ayushgopal17** [iamrahulmahato/master-web-development#1456]
🔴 Title : small bug
🔴 Tech stack : HTML CSS
🔴 Objective : To make it more clear
🔴 Summary : have to change the pixel size
📸 Screenshots
<
<img width="1440" alt="Screenshot 2024-10-19 at 6 20 28 PM" src="https://github.com/user-attachments/assets/2cb123d0-52bf-4a15-a764-390929554edd">
>

***********************************************************************

✅ Details to Include When Taking the Issue: here. "S" of suduku is not visible it s zoomed more then the requirement
Name : AYUSH GOPAL
Participant Role (Specify the Open Source Program name, GSSOC, Hacktoberfest.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the issue is fixed
