### ISSUE TITLE
🧑‍💻 : SCROLL TOP BUTTON

### ISSUE THREAD

**Issue by shriyadindi** [iamrahulmahato/master-web-development#1460]
:red_circle: **Title** : ADD A SCROLL TO TOP BUTTON
:red_circle: **Enhancement Aim** :ADDING A NEW FEATURE

### Screenshots 📷

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :Shriya dindi
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
it is already there
