### ISSUE TITLE
🧑‍💻 : UI of internet speed checker is not good

### ISSUE THREAD

**Issue by DevROHIT11** [iamrahulmahato/master-web-development#1464]
🔴  **Internet Speed checker** :
🔴  **Enhancing the UI of internet spped checker ** :
🔴 **Changing the font style , backgroung color , making the page more interactive** 

### Screenshots 📷
![Screenshot (43)](https://github.com/user-attachments/assets/746f4cba-4fbe-4fba-b817-3a6c66445b53)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Rohit Lahu Bhalekar
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by DevROHIT11** [comment]
i want to work on this issue plz assign it to me

**Comment by DevROHIT11** [comment]
can u label this issue i want to work on it

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
