### ISSUE TITLE
🐞 : Duplicate Page Rendering

### ISSUE THREAD

**Issue by AnushkaChouhan25** [iamrahulmahato/master-web-development#1469]
:red_circle: **Title** : Duplicate Page
:red_circle: **Bug** : There is a bug in the website where the same page content appears twice. The first instance is located at the top of the page, and the second instance is rendered in between other content, creating a confusing user experience.

:red_circle: **Changes** :  
- Identified a bug causing the same page content to appear twice: once at the top and again in the middle of the page.
- Proposed a solution to investigate the rendering logic and eliminate the duplication to improve user experience.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/1f6f7bef-e5c6-4790-a82b-67800aaeb6b2)

************************************************************

✅ Details to Include When Taking the Issue:
Name : Anushka Chouhan
Participant Role: Gssoc, hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
it is fixed
