### ISSUE TITLE
🧑‍💻 : Implement a Login Page with Secure Authentication, including "Forgot Password" and Third-Party Login Options

### ISSUE THREAD

**Issue by Vishwajeet594** [iamrahulmahato/master-web-development#1476]
Description:

We need to implement a login page to enhance the functionality and user experience of the website. This page will allow users to log into their accounts securely and access personalized content or features.

Current Situation:

Currently, there is no login page or authentication system on the website.
Users are unable to create accounts, log in, or manage their profile settings.
Proposed Solution:

Create a dedicated login page following the design guidelines of the website.
Implement secure user authentication using standard best practices (e.g., OAuth, JWT, etc.).
Include form fields for email/username and password, along with options for "Forgot Password" and "Remember Me" features.
Optionally, add third-party login options (e.g., Google, Facebook).
Design Considerations:

Ensure the login page design is in harmony with the rest of the site, especially in terms of the GlassyUI aesthetic.
Make sure the login form is mobile-responsive and accessible.

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :vishwajeet
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
gssocext-contributer
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
We are not adding any signup and sign in pages for right now. Do not be demotivated and raise a new issue.
