### ISSUE TITLE
🧑‍💻 : Add a bottom To Button for Enhanced User Navigation and Smooth Scrolling on Long Pages

### ISSUE THREAD

**Issue by Vishwajeet594** [iamrahulmahato/master-web-development#1477]
Description:

To improve navigation and user experience on long pages, we need to add a "Scroll to Top" button. This button will allow users to easily scroll back to the top of the page with one click, enhancing convenience, especially on mobile devices.

Current Situation:

No "Scroll to Top" functionality is currently available on the website.
Users need to manually scroll all the way back to the top, which could become cumbersome, especially on longer pages.
Proposed Solution:

Implement a floating "Scroll to Top" button that becomes visible when users scroll down the page.
The button should be styled in a way that aligns with the overall theme (e.g., glassy, transparent effects) and is noticeable but not intrusive.
The button should appear at the bottom-right corner of the screen and smoothly scroll the user back to the top of the page when clicked.

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :vishwajeet
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
gssocext-contributer
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
it is there
