### ISSUE TITLE
🧑‍💻 : Create an FAQ Section with Categorized Questions and Search Functionality to Improve User Experience

### ISSUE THREAD

**Issue by Vishwajeet594** [iamrahulmahato/master-web-development#1478]
Description:

I would like to propose adding a Frequently Asked Questions (FAQ) section to the website. This will help address common user queries, reduce support requests, and improve the overall user experience by providing quick answers to commonly asked questions.

Current Situation:

No FAQ section exists on the website.
Users may struggle to find answers to basic questions, leading to potential frustration or unnecessary support requests.
Proposed Solution:

Create a dedicated FAQ section that is easy to navigate and user-friendly.
Include questions and answers categorized by topics (e.g., General, Account, Features, etc.).
Implement a search or filter function to allow users to quickly find relevant answers.

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :vishwajeet
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
gssocext-contributer
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
it is there search bar and a bot for faq
