### ISSUE TITLE
📃: Add Google Homepage Clone

### ISSUE THREAD

**Issue by Annapoornaaradhya** [iamrahulmahato/master-web-development#1481]
🔴 Title : Google Homepage Clone
🔴 Tech stack : HTML CSS
🔴 Objective : Want to create google landing page clone with advance search page as well
🔴 Summary : You can navigate to other pages from the top right corner links
Then I have our search field where you can search your queries and that links to the google search and show you the result of images matched of your query. You can either just press the enter key or use the Search icon just at the right corner of your query field to find the result.
📸 Screenshots
![image](https://github.com/user-attachments/assets/4bf1fc4e-131d-43ec-9fc0-650218e2adbf)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Annapoorna
Participant GSSOC-ext, Hacktoberfest.
***********************************************************************
@iamrahulmahato please assign me this under gssoc-ext level 2 and hacktoberfest accecpted tag
Thank you

**Comment by iamrahulmahato** [comment]
we are not adding any clone website for right now because we have to face some deployment issues. Do not be demotivated and raise a new issue.
