### ISSUE TITLE
📃: ADDING A NEW PROJECT - MINI CALENDER📅

### ISSUE THREAD

**Issue by shriyadindi** [iamrahulmahato/master-web-development#1483]
🔴 Title :MINI CALENDER
🔴 Tech stack :HTML,CSS,JS
🔴 Objective : ADDING A NEW PROJECT
🔴 Summary :I would like to add a new project for the website.
📸 Screenshots

![Screenshot 2024-10-20 094938](https://github.com/user-attachments/assets/06f23e5a-8115-44a2-9cfd-7b4d164cea4c)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Shriya Dindi
Participant Role: GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
