### ISSUE TITLE
I can add few more Fun games and small projects 

### ISSUE THREAD

**Issue by Vijitverm1234** [iamrahulmahato/master-web-development#150]
- can add **Rock paper scissors**
- can add **Dice game**
- can add a Footer and few more cool functionalities

<img width="458" alt="rock paper" src="https://github.com/user-attachments/assets/bbed1755-c000-4b3e-ba45-8939359c2f06">

**Comment by iamrahulmahato** [comment]
both exist, Do not be demotivated and raise a new issue.
