### ISSUE TITLE
📃: adding a new project random color generator 

### ISSUE THREAD

**Issue by sharath4444** [iamrahulmahato/master-web-development#1502]
🔴 Title :random color generator
🔴 Tech stack :html,css,javascript
🔴 Objective :want to show a random color
🔴 Summary : want to show a random color with hashcode 
📸 Screenshots
![image](https://github.com/user-attachments/assets/2015757c-f09f-466b-8a2d-d29050a23922)

✅ Details to Include When Taking the Issue:
Name :mankala sharathchandra
Participant Role GSSOC,Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
this project is already there so i am closing the issue
