### ISSUE TITLE
📃: Want to improve footer section

### ISSUE THREAD

**Issue by sanikamandale17** [iamrahulmahato/master-web-development#1504]
🔴 Title :Want to improve footer section
🔴 Tech stack :
🔴 Objective :Want to improve footer section
🔴 Summary :Want to improve footer section ,add all things home contact us about us .....
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC as well as hackoctber fest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by singh04ayush** [comment]
I would like to address this issue; I know exactly what to do. Can I proceed?
Name - Ayush Singh
github - singh04ayush
GSSOC as well as Hacktoberfest
