### ISSUE TITLE
📃: ADD cookie popup feature

### ISSUE THREAD

**Issue by sanikamandale17** [iamrahulmahato/master-web-development#1505]
🔴 Title : ADD cookie popup feature
🔴 Tech stack :
🔴 Objective :
🔴 Summary :i like to add a Cookie Pop-up to the website. This pop-up will notify users about the use of cookies to improve their browsing experience and give them the option to accept or decline cookies. The pop-up will be responsive, working well on all devices. It will include a short, simple explanation of what cookies do, plus a button to learn more or adjust cookie settings.
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest
plz assign this to me @iamrahulmahato 
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
I am closing the issue because we are unable to work on it due to some deployment issues.
