### ISSUE TITLE
📃: Want to improve feedback form also add rating feature in it

### ISSUE THREAD

**Issue by sanikamandale17** [iamrahulmahato/master-web-development#1507]
🔴 Title :Want to improve feedback form
🔴 Tech stack :
🔴 Objective :Want to improve feedback form
🔴 Summary :Want to improve feedback form that matches the theme of website also add rating feature in it
📸 Screenshots

N/A
***********************************************************************

✅ Details to Include When Taking the Issue:
Name :sanikamandale17
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest
***********************************************************************
Plz assign this issue to me @iamrahulmahato 

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Manas-Phal** [comment]
Name : manas phal 
Role:-To improve feedback form and add rating features in it.
plz assign me this issue and add suitable labels  GSSOC-ext  , Hacktoberfest, level

**Comment by sanikamandale17** [comment]
plz @ assign this issue to me
