### ISSUE TITLE
📃: Add a Task Manager App

### ISSUE THREAD

**Issue by mehendisil2004** [iamrahulmahato/master-web-development#1511]
🔴 Title : Task Manager
🔴 Tech stack : HTML, CSS, JS
🔴 Objective : To organize task
🔴 Summary : Basic app to add, remove and complete daily tasks
📸 Screenshots
![Screenshot 2024-10-17 215352](https://github.com/user-attachments/assets/b25301e2-7353-4519-8a8e-39822c43c436)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Mehendi Sil
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): gssoc-ext, hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
The project already exist, Do not be demotivated and raise a new issue.
