### ISSUE TITLE
🐞 : Dark mode enhancement

### ISSUE THREAD

**Issue by saumyayadav25** [iamrahulmahato/master-web-development#1516]
:red_circle: **Title** : Dark mode enhancement
:red_circle: **Bug** :
:red_circle: **Changes** : Game Names are not visible clearly. dark mode requires better choices of color-> preferably bright or lighter colors.

### Screenshots 📷
<img width="1199" alt="Screenshot 2024-10-20 at 6 13 52 PM" src="https://github.com/user-attachments/assets/52d2daa7-2b84-43d0-88f1-d89fe36b13cc">

************************************************************

✅ Details to Include When Taking the Issue:
Name : Saumya
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC extended, Hacktoberfest,

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Aditya90456** [comment]
i can do @Iampratyush004
