### ISSUE TITLE
🧑‍💻 : 🧑‍💻 : Challenges  for each topic

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [iamrahulmahato/master-web-development#1527]
:red_circle: **Title** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : 

🧑‍💻 : Challenges  for each topic
### Screenshots 📷

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :
Bhuvaneswari kapuluru gssoc extd
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
can you describe more

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Conduct  challenges with questions and options and show result

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
in this format sir
<img width="950" alt="challenge-1-2" src="https://github.com/user-attachments/assets/b2979dd8-ba52-4c02-91fa-69d84a1d99f4">
<img width="959" alt="challenge1-result" src="https://github.com/user-attachments/assets/224402e6-806f-45a0-aa5c-98b0397319ac">
