### ISSUE TITLE
📃: Add new project Mood based Music Recommendor 

### ISSUE THREAD

**Issue by Sumanth077s** [iamrahulmahato/master-web-development#1528]
🔴 Title : Mood based Music Generator 
🔴 Tech stack : html css js
🔴 Objective : To create an interactive web app that recommends music and dynamically changes its theme based on the user's selected mood.
🔴 Summary : n/a
📸 Screenshots n/a

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Sumanth U
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): Gssoc and hacktober fest Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by pc-daukiya** [comment]
Please assign me for this Add new project Mood based Music Recommendor
