### ISSUE TITLE
Add Hover Effect to Cards for Enhanced UI

### ISSUE THREAD

**Issue by Shiv13jm** [iamrahulmahato/master-web-development#153]
### Description:
Hey @iamrahulmahato !  The current design of the cards on our website is static and lacks interactive elements. To make the UI more attractive and engaging, we need to add a hover effect to the cards. This will improve the user experience by providing visual feedback when users interact with the cards.

### Expected Behavior:
When a user hovers over a card, the card should display a visual effect (e.g., shadow, scale, color change) to indicate interactivity.

### Actual Behavior:
The cards currently do not change appearance when hovered over.

Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24 and hacktoberfest.

**Comment by iamrahulmahato** [comment]
read the guidelines there strictly mention there should not be any changes in home page, Do not be demotivated and raise a new issue.
