### ISSUE TITLE
🧑‍💻 : Add FAQ page 

### ISSUE THREAD

**Issue by govindbairi** [iamrahulmahato/master-web-development#1531]
:red_circle: **Title** :add FAQ functionality
![Screenshot 2024-10-21 125523](https://github.com/user-attachments/assets/22ee7c3a-8eca-4e7c-813c-a4bc8dee8996)

:red_circle: **Enhancement Aim** :user can view faq's
:red_circle: **Changes** : adding faq page

### Screenshots 📷

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :govindbairi
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):gssoc

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by muskiagrwal** [comment]
please assign this to me
