### ISSUE TITLE
📃: ADDING A NEW PROJECT  - WEATHER APP

### ISSUE THREAD

**Issue by shriyadindi** [iamrahulmahato/master-web-development#1532]
🔴 Title :I would like to add a new project named weather app
🔴 Tech stack :HTML, CSS, JS
🔴 Objective : adding a new project named weather app
🔴 Summary : I would like to add a new project named weather app
📸 Screenshots

![Screenshot 2024-10-21 135621](https://github.com/user-attachments/assets/6c6ca394-07d4-4cc9-acc5-ff8cff92c820)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Shriya Dindi
Participant Role : GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
