### ISSUE TITLE
📃: Want To improve Footer Section

### ISSUE THREAD

**Issue by sanikamandale17** [iamrahulmahato/master-web-development#1534]
🔴 Title :Want To improve Footer Section
🔴 Tech stack :
🔴 Objective :Want To improve Footer Section
🔴 Summary :Want To improve Footer Section
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :sanikamandale
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
