### ISSUE TITLE
🧑‍💻 : I want to add Navbar to homepage 

### ISSUE THREAD

**Issue by DevROHIT11** [iamrahulmahato/master-web-development#1544]
🔴 : **Adding Navbar To homepage ** :
🔴  **Enhancement Aim** :
🔴 : **I want to add navbar to homepage by making its UI attractive and user friendly, some elements to navbar** 

### Screenshots 📷
![Screenshot (52)](https://github.com/user-attachments/assets/47d56801-995f-4509-b2ff-9d5e74ffd502)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Rohit Lahu Bhalekar
Participant Role : Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by DevROHIT11** [comment]
I want to work on this Issue plz assign this to me and label the issue also.

**Comment by iamrahulmahato** [comment]
no we are not adding any nav bar,Do not be demotivated and raise a new issue.
