### ISSUE TITLE
📃: RANDOM QUOTE GENERATOR - NEW PROJECT 

### ISSUE THREAD

**Issue by shriyadindi** [iamrahulmahato/master-web-development#1551]
🔴 Title :RANDOM QUOTE GENERATOR - NEW PROJECT 
🔴 Tech stack : HTML, CSS, JS
🔴 Objective : ADDING A NEW PROJECT RANDOM QUOTE GENERATOR
🔴 Summary :
📸 Screenshots

![Screenshot 2024-10-21 191459](https://github.com/user-attachments/assets/b432ed8f-4eaa-41e5-a6e2-b6467e1b9fba)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : SHRIYA DINDI
Participant Role: GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
The project already exist, Do not be demotivated and raise a new issue.
