### ISSUE TITLE
📃: AMAZON CLONE - NEW PROJECT

### ISSUE THREAD

**Issue by shriyadindi** [iamrahulmahato/master-web-development#1552]
🔴 Title : CREATING AN AMAZON CLONE AS ANEW PROJECT
🔴 Tech stack : HTML, CSS, JS

📸 Screenshots

![Screenshot 2024-10-21 202931](https://github.com/user-attachments/assets/3ea50642-908c-41de-bf31-9d4f18d3a808)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Shriya Dindi
Participant Role: GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
we have to face some deployment issues so for right now we are not adding any clone website
