### ISSUE TITLE
📃: Add new project Typing Speed Test

### ISSUE THREAD

**Issue by karthikyandrapu** [iamrahulmahato/master-web-development#1553]
🔴 Title : Typing Speed Test
🔴 Tech stack : HTML, CSS, JavaScript
🔴 Objective : To develop a web application that allows users to test their typing speed by measuring words per minute (WPM) and accuracy over a given time frame.
🔴 Summary : N/A
📸 Screenshots:
![Screenshot (220)](https://github.com/user-attachments/assets/17e5c844-0829-4c99-9c97-6aeaeeaee6c5)

![Screenshot (221)](https://github.com/user-attachments/assets/26679871-9a38-47b4-bbb8-233c29b621d0)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : karthikyandrapu
Participant Role: GSSoC'24-Extd and Hacktoberfest Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
The project already exist, Do not be demotivated and raise a new issue.
