### ISSUE TITLE
🐞 :  Missing Search Button for Search Input Field

### ISSUE THREAD

**Issue by sheezah01** [iamrahulmahato/master-web-development#1562]
:red_circle: **Title** : Missing Search Button for Search Input Field
:red_circle: **Bug** : UI issue 
:red_circle: **Changes** :  
Currently, the search input field lacks a visible search button, which may lead to a suboptimal user experience, especially for users who prefer or expect a button to initiate their search. Additionally, the visual features of the header could be enhanced to create a more cohesive and appealing design.

By adding a visible search button and improving the header's visual elements, we can make the UI more intuitive, accessible, and aesthetically pleasing, catering to a wider range of users.
Steps to Reproduce:
1. Go to the page containing the search input field.
2. Try to search for a term using the input field.
3. Notice that there is no visible "Search" button next to the input field.

Expected Behavior: A visible "Search" button should be present next to the search input field, allowing users to click it to initiate a search.

Actual Behavior: There is no search button, forcing users to press the "Enter" key on their keyboard to execute a search.
### Screenshots 📷

![issue5](https://github.com/user-attachments/assets/7fa73843-374f-4d48-af97-58016b5c8799)

************************************************************

✅ Details to Include When Taking the Issue:
Name :sheezah
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC and Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open-source journey. Enjoy! 😎

**Comment by BaniSinghgithub** [comment]
hello sir @iamrahulmahato ,please assign this task to me.
