### ISSUE TITLE
📃: Task Manager Web App

### ISSUE THREAD

**Issue by rahulbamnuya** [iamrahulmahato/master-web-development#1565]
🔴 Tech stack:

Frontend: HTML, CSS, JavaScript
Backend: Node.js (Express) or Python (Flask)
Database: MongoDB or SQLite
🔴 Objective:
To create a simple task management web application where users can add, edit, delete, and mark tasks as completed.

🔴 Summary:
This app allows users to organize tasks based on categories and due dates. Users can add new tasks, edit them, and mark tasks as completed. The app helps users manage their to-do lists more efficiently and can be extended with features like user authentication and task reminders.

📸 Screenshots:
N/A
✅ Details to Include When Taking the Issue:
Name : Rahul Bamaniya
Participant gssoc-extd GSSOC, Hacktoberfest .

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
The project already exist, Do not be demotivated and raise a new issue.
