### ISSUE TITLE
📃:  Recipe Finder Web App

### ISSUE THREAD

**Issue by rahulbamnuya** [iamrahulmahato/master-web-development#1566]
🔴 Title: Recipe Finder Web App
🔴 Tech stack:

Frontend: HTML, CSS, Bootstrap
Backend: Node.js or Python (Flask)
API: Spoonacular or Edamam API
🔴 Objective:
To create a web app that allows users to search for recipes based on ingredients or cuisine type and view detailed recipe information.

🔴 Summary:
The Recipe Finder allows users to find recipes using ingredients they have on hand or search for recipes based on a specific cuisine. It provides detailed information such as ingredients, cooking instructions, and preparation time. Users can also save their favorite recipes for easy access later.

📸 Screenshots:
N/A
✅ Details to Include When Taking the Issue:
Name : Rahul Bamaniya
Participant gssoc-extd, GSSOC, Hacktoberfest .

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
