### ISSUE TITLE
📃:  Weather Dashboard 

### ISSUE THREAD

**Issue by rahulbamnuya** [iamrahulmahato/master-web-development#1567]
🔴 Title: Weather Dashboard
🔴 Tech stack:

Frontend: HTML, CSS, JavaScript (React optional)
API: OpenWeatherMap API
🔴 Objective:
To create a web-based weather dashboard that displays current weather conditions and a 5-day forecast for a specific location.

🔴 Summary:
The Weather Dashboard fetches real-time weather data using the OpenWeatherMap API and displays current temperature, humidity, and weather conditions. Users can search for weather by city and view a 5-day forecast. The app also includes an option to switch between Celsius and Fahrenheit.

📸 Screenshots:
N/A
✅ Details to Include When Taking the Issue:
Name : Rahul Bamaniya
Participant Role, GSSOC, Hacktoberfest,gssoc-extd

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
