### ISSUE TITLE
🧑‍💻 :  Add Option to Translate Entire Website Text

### ISSUE THREAD

**Issue by Riyachauhan11** [iamrahulmahato/master-web-development#1569]
:red_circle:  Add Option to Translate Entire Website Text
:red_circle: provide users with the ability to translate the entire website's text into different languages, improving accessibility and user experience for non-native speakers.
:red_circle: **Changes** : Implement a user-friendly dropdown or button for selecting the desired language.

### Screenshots 📷

N/A

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Riya Chauhan
Participant Role : GSSOC, Hacktoberfest, Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
