### ISSUE TITLE
Proposal to add "Youtube Clone" using HTML, CSS and JS

### ISSUE THREAD

**Issue by clownfish1805** [iamrahulmahato/master-web-development#157]
I would like to add a simple **YouTube clone application** built with HTML, CSS, and JavaScript. 

This application will feature a basic layout where users can search for videos, view video thumbnails, and play videos. 
It will utilize a static dataset for demonstration purposes, allowing for future integration with a video API for dynamic content.

**The following files will be included:**

**index.html:** The structure of the YouTube clone interface.
**styles.css:** Styling to replicate the look and feel of YouTube.
**script.js:** Functionality to handle video searching and playback.
This feature will enhance the project by providing a practical example of video content display and user interaction.

**Comment by clownfish1805** [comment]
@iamrahulmahato I would be able to create a clone of Youtube. 
Please assign me this issue under **hacktoberfest** and **GSSOC'24 extended**.

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it I will make my best

**Comment by clownfish1805** [comment]
@iamrahulmahato I have raised PR for this issue. Please check.
