### ISSUE TITLE
📃:  ADD New project Pomodoro Timer

### ISSUE THREAD

**Issue by Sumanth077s** [iamrahulmahato/master-web-development#1571]
🔴 Title : Pomodoro Timer
🔴 Tech stack :html css js
🔴 Objective :Develop a Pomodoro Timer that helps users stay productive by following the Pomodoro technique—work sessions followed by short breaks.
🔴 Summary :N/A
📸 Screenshots N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Sumanth U
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): 
Contributor at gssoc and hacktober 
**********************************************************************
Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
The project already exist, Do not be demotivated and raise a new issue.
