### ISSUE TITLE
🧑‍💻 : Improvement Needed for Feedback Form on Homepage

### ISSUE THREAD

**Issue by iarmaanx** [iamrahulmahato/master-web-development#1577]
# Issue Title: Improvement Needed for Feedback Form on Homepage

### Description:
The feedback form on the homepage requires improvements for better user experience and functionality. Currently, the form lacks proper validation, clear input labels, and an optimized layout, which can confuse users and lead to lower form submission rates. Enhancing the form will make it more user-friendly and encourage more feedback submissions.

### Type of Issue:
- UI/UX Enhancement

### Proposed Solution:
I can improve the feedback form by adding clear input labels, implementing proper validation (e.g., email validation, required fields), and redesigning the form layout to ensure it is mobile-responsive and user-friendly. This will result in a more efficient and accessible feedback form.

### Labels Request:
- gssoc
- hacktoberfest
- level: 2
### Screenshot:
![Screenshot (8)](https://github.com/user-attachments/assets/b4c42295-cbfd-47c9-9949-8a3b43d578b0)

**Comment by iarmaanx** [comment]
_I would love to work on this issue. Consider assigning this to me.
_

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
