### ISSUE TITLE
🧑‍💻 : Add Quizes

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [iamrahulmahato/master-web-development#1580]
:red_circle: **Title** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : 

### Screenshots 📷

Add Quizes
**********************************************************************
✅ Details to Include When Taking the Issue:
Name :
Bhuvaneswari gssoc extd
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
