### ISSUE TITLE
📃: TYPING SPEED TEST - NEW PROJECT

### ISSUE THREAD

**Issue by shriyadindi** [iamrahulmahato/master-web-development#1582]
🔴 Title :TYPING SPEED TEST - NEW PROJECT
🔴 Tech stack :HTML, CSS, JS
🔴 Objective :ADDING A NEW PROJECT

📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :SHRIYA DINDI
Participant Role: GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
The project already exist, Do not be demotivated and raise a new issue.
