### ISSUE TITLE
📃: Emoji Search App - new project

### ISSUE THREAD

**Issue by shriyadindi** [iamrahulmahato/master-web-development#1584]
🔴 Title : Emoji Search App - new project
🔴 Tech stack : HTML, CSS,JS
🔴 Objective : Adding a new project

✅ Details to Include When Taking the Issue:
Name : Shriya Dindi
Participant Role: GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
The project already exist, Do not be demotivated and raise a new issue.
