### ISSUE TITLE
📃: 

### ISSUE THREAD

**Issue by sanskaryo** [iamrahulmahato/master-web-development#1606]
🔴 **Title**: Drum Kit - Fun Beginner-Friendly Project

🔴 **Tech stack**: 
- HTML
- CSS
- JavaScript

🔴 **Objective**: 
To create an interactive drum kit web app where pressing specific keys on the keyboard triggers corresponding drum sounds.

🔴 **Summary**: 
This project is designed to be beginner-friendly, focusing on basic DOM manipulation and event handling in JavaScript. Users press keys (e.g., 'W', 'A', 'S', 'D', 'J', 'K', 'L') to hear different drum sounds, providing an engaging way to learn web development while creating a fun and functional app. It also teaches the use of CSS for styling and enhancing the visual appeal of the project.

📸 **Screenshots**: 
![image](https://github.com/user-attachments/assets/3dcb4542-c401-45eb-a036-33fb020cf7be)

***********************************************************************

✅ **Details to Include When Taking the Issue**:
**Name**: [Your Name]  
**Participant Role**: Hacktoberfest , gssoc , gssoc-ext

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

---

Feel free to customize it further!

**Comment by iamrahulmahato** [comment]
The project already exist, Do not be demotivated and raise a new issue.
