### ISSUE TITLE
📃: Clone Amazon website

### ISSUE THREAD

**Issue by JahnavikaGopalbvrith** [iamrahulmahato/master-web-development#1610]
🔴 Title : Amazon Clone
🔴 Tech stack : HTML CSS JS
🔴 Objective :  focusing on delivering a high-quality shopping experience, robust functionality, and user satisfaction
🔴 Summary :Prioritizing user experience and security will be crucial to competing effectively in the e-commerce market
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Jahnavika gopal
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Due to deployment issues we are not adding any clone website right now,Do not be demotivated and raise a new issue.
