### ISSUE TITLE
🧑‍💻 : ADD term of uses page

### ISSUE THREAD

**Issue by Subham1** [iamrahulmahato/master-web-development#1617]
:red_circle: **missing term of us page** :
:red_circle: **adding tem of use page** :

**Objective**
Create a "Terms of Use" page for the website. The page should outline the terms and conditions for using the website. It must be accessible from the footer and follow the website's design and layout guidelines.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/ff165f26-a72f-48de-90ba-ae1099d55644)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :Subham sahu
Participant Role ( GSSOC, Hacktoberfest,):

***********************************************************************

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
