### ISSUE TITLE
🐞 : Dark mode button is not working.

### ISSUE THREAD

**Issue by sayanp607** [iamrahulmahato/master-web-development#1622]
:red_circle: **dark mode button is not working** :
:red_circle: **on clicking the button, the mode does not change itself.** :
:red_circle: **Changes** :  I will fix it javascript and css code so that it will work.
![Screenshot 2024-10-23 001006](https://github.com/user-attachments/assets/fca3da37-7986-4bad-ac67-38884a7ae05c)

### Screenshots 📷

************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest.

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Pranshigupta7275** [comment]
i want to fix this issue please assign me
