### ISSUE TITLE
📃:  Add Multi-Step Budget Planner Project to the Repository

### ISSUE THREAD

**Issue by AdityaJani616** [iamrahulmahato/master-web-development#1633]
🔴 **Title**: Add Multi-Step Budget Planner Project to the Repository

🔴 **Tech Stack**:  
- Next.js  
- React.js  
- Local Storage for data management  
- Exchange Rate API for currency conversion

🔴 **Objective**:  
The objective of this project is to help users create and manage budgets in multiple steps, breaking down financial planning into simpler tasks, with currency conversion features based on live exchange rates.

🔴 **Summary**:  
The Multi-Step Budget Planner is a responsive web application that allows users to plan their budget by dividing it into several steps. Users can categorize their income, expenses, and savings, while also utilizing live exchange rates to manage their budget in different currencies. The app stores user data in local storage, ensuring persistence across sessions without the need for backend storage. Built using Next.js and React.js, the app offers smooth navigation and state management.

✅ **Details to Include When Taking the Issue**:  
- **Name**: Aditya Jani  
- **Participant Role**: GSSoC Extd , Hacktoberfest Contributor
- 
📸 **Screenshots**  
![image](https://github.com/user-attachments/assets/1ab104d0-01bf-491e-88d3-51b1ab11338a)

![image](https://github.com/user-attachments/assets/34e6ac03-b23f-47af-ab30-113250c32967)

![image](https://github.com/user-attachments/assets/5914769a-6ee4-4da6-82e0-1da1be63b2ff)

![image](https://github.com/user-attachments/assets/6b19838e-0987-429a-a73d-c1d97075b56c)

![image](https://github.com/user-attachments/assets/3d6f9420-40f1-40ce-b905-59ec92cc73a6)

***********************************************************************

**Comment by iamrahulmahato** [comment]
someone already working on the issue, do not demotivate; please make a new issue
