### ISSUE TITLE
 Amazon Lite: Simplified E-Commerce Experience

### ISSUE THREAD

**Issue by greeshma275** [iamrahulmahato/master-web-development#1646]
🔴 Title:
Amazon Lite: Simplified E-Commerce Experience

🔴 Tech Stack:
Frontend: HTML, CSS, JavaScript

🔴 Objective:
To build a simplified version of an e-commerce web application that enables users to browse and add products to their cart, mimicking basic Amazon features.

🔴 Summary:
Amazon Lite is a minimalistic e-commerce platform that offers users a simple, clean shopping experience. The application allows users to:

Browse a list of products.
View product details.
Add items to their shopping cart.
The app focuses on user-friendly design and responsive functionality using HTML, CSS, and JavaScript. It demonstrates basic shopping cart functionality and product listing, making it a great introductory project for e-commerce solutions.

📸 Screenshots:
N/A

✅ Details to Include When Taking the Issue:
Name: Greeshma G
Participant Role: Contributor, GirlScript Summer of Code (GSSoC) Extended 2024

**Comment by iamrahulmahato** [comment]
there are some deployment issue that way we are not adding any clone website for right now. Do not demotivate raise a new issue
