### ISSUE TITLE
📃: ADD New Project Virtual Drum Kit Using Face Gestures

### ISSUE THREAD

**Issue by Sumanth077s** [iamrahulmahato/master-web-development#1653]
🔴 Title :Virtual Drum Kit Using Face Gestures
🔴 Tech stack : html,css,js
🔴 Objective :N/A
🔴 Summary :The current version of the Virtual Drum Kit supports only two gestures: mouth open and blink, mapped to basic drum sounds (snare and crash). To make the app more engaging, additional gestures and sound mappings are needed.
📸 Screenshots N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Sumanth U
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): Contributor at gssoc and hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already have
