### ISSUE TITLE
🐞 : The feedback form is in the middle of nowhere

### ISSUE THREAD

**Issue by avogadroB** [iamrahulmahato/master-web-development#1666]
:red_circle: **Title** : The feedback form is not easy to locate
:red_circle: **Bug** : The feedback link and write a feedback button are in the middle of the games.
:red_circle: **Changes** :  Locate a new button to the top of the main page for feedback 

### Screenshots 📷
![image](https://github.com/user-attachments/assets/8ba8d50a-0665-4318-bd10-d48af95639b4)

************************************************************

✅ Details to Include When Taking the Issue:
Name : avogadroB
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC-ext, Hacktoberfest contributor

### Would like to work on this issue.
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
it is fixed
