### ISSUE TITLE
🐞 : The feedback form containers are not aligned to the center

### ISSUE THREAD

**Issue by avogadroB** [iamrahulmahato/master-web-development#1667]
:red_circle: **Title** :  The form is misaligned
:red_circle: **Bug** :  The padding is off and not aligned to the center
:red_circle: **Changes** :  Improve CSS sheet to center the form and make it look better

### Screenshots 📷
![image](https://github.com/user-attachments/assets/1bc1adae-c693-4598-9a3f-ba6f0102fbfb)

************************************************************

✅ Details to Include When Taking the Issue:
Name : avogadroB
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC-xtended and hacktoberfest contributor

Would like to work on this issue.
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by arpit74170** [comment]
please assign this task to me , i have done with making 3 websites for client ,so i am best for it

**Comment by avogadroB** [comment]
hey @arpit74170 please take note that I already specified that I would like to work on this issue.

**Comment by iamrahulmahato** [comment]
it is fixed
