### ISSUE TITLE
📃: Add new project Response Flipkart Clone Website

### ISSUE THREAD

**Issue by karthikyandrapu** [iamrahulmahato/master-web-development#1670]
🔴 Title : Response Flipkart Clone Website
🔴 Tech stack : HTML, CSS, JavaScript
🔴 Objective : Developing a fully functional Flipkart clone with a focus on front-end technologies like HTML, CSS, and JavaScript to replicate core e-commerce functionalities. This project aims to deliver a responsive and visually engaging shopping experience, with features such as navigation, product listings, search functionality, etc.
🔴 Summary : N/A
📸 Screenshots:
![Screenshot (228)](https://github.com/user-attachments/assets/23e5cd78-7179-4301-bec3-872f608e928a)
![Screenshot (227)](https://github.com/user-attachments/assets/f13fe647-03b9-48a9-9ae8-2c256c463c77)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name: karthikyandrapu
Participant Role: GSSoC'24-Extd and Hacktoberfest Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by karthikyandrapu** [comment]
### @iamrahulmahato Pls kindly assign me and label it under gssoc-ext level 2 because it is a Response Flipkart Clone Frontend Website

**Comment by iamrahulmahato** [comment]
there are some deployment issue that way we are not adding any clone website for right now. Do not demotivate raise a new issue
