### ISSUE TITLE
🐞 : Adding feedback section at relevant position

### ISSUE THREAD

**Issue by Pragati1466** [iamrahulmahato/master-web-development#1676]
:red_circle: **Title** :
:red_circle: **Bug** :
:red_circle: **Changes** :  

### Screenshots 📷

<img width="1782" alt="Screen Shot 2024-10-24 at 2 23 06 AM" src="https://github.com/user-attachments/assets/905b7821-8e8b-47a2-b5cb-bb84bfe72592">
@iamrahulmahato 

************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Pragati1466** [comment]
gssoc,hacktoberfest both

**Comment by Pragati1466** [comment]
And also improving the ui/ux design of feddback section @iamrahulmahato

**Comment by iamrahulmahato** [comment]
it is fixed
