### ISSUE TITLE
📃: Personal Finance Tracker

### ISSUE THREAD

**Issue by shriyadindi** [iamrahulmahato/master-web-development#1685]
🔴 Title :Personal Finance Tracker
🔴 Tech stack : HTML, CSS, JS
🔴 Objective : Adding a new project

✅ Details to Include When Taking the Issue:
Name :Shriya Dindi
Participant Role: GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project is already present, Do not demotivate raise a new issue
