### ISSUE TITLE
 Add 'Star ⭐ Us on GitHub' Button on Homepage

### ISSUE THREAD

**Issue by SCR01** [iamrahulmahato/master-web-development#169]
#### Description:
We need to add a **' Star Us on GitHub'** button to the homepage of the website.

#### Why is this important?
- It encourages visitors and contributors to **"⭐"** the repository directly from the homepage.
- Helps increase visibility and build community support for the project.

#### Comment:
- The button should be placed prominently on the homepage.
- It should be styled to match the existing design of the website.

**Comment by iamrahulmahato** [comment]
read the guidelines There is a strict mention there should not be any changes in the home page. Do not be demotivated and raise a new issue.
