### ISSUE TITLE
 Add Hover Effect to Project Cards

### ISSUE THREAD

**Issue by shivamv003** [iamrahulmahato/master-web-development#171]
To improve the visual appeal and interactivity of the project cards displayed on the project grid, I propose adding hover effects. Currently, the cards lack dynamic feedback when users hover over them, which can make the interface feel static and less engaging.

![image](https://github.com/user-attachments/assets/e1bda315-52d6-4174-b9a1-1fe4fbde3bd9)

please assign this me under gssoc 2024

**Comment by brewcoder6113** [comment]
pls assign

**Comment by iamrahulmahato** [comment]
read the guidelines There is a strict mention there should not be any changes in the home page. Do not be demotivated and raise a new issue.
