### ISSUE TITLE
Implement New Navbar 

### ISSUE THREAD

**Issue by Rehan0016** [iamrahulmahato/master-web-development#172]
Description:

We need to create a new navbar that enhances navigation, improves user experience, and aligns with the overall design of the application. This issue outlines the requirements and proposed features for the new navbar.

Proposed Features:

Design:

Create a visually appealing navbar that matches the application’s theme.
Ensure the navbar is responsive, adapting well to various screen sizes (mobile, tablet, desktop).
Navigation Links:

Include essential navigation links (e.g., Home, About, Services, Contact).
Add dropdown menus for subcategories where necessary to streamline navigation.
Search Functionality:

Integrate a search bar within the navbar to allow users to quickly find content.
User Account Section:

Implement user account links (e.g., Login, Sign Up, Profile) if applicable.
Accessibility:

Ensure the navbar is accessible, with appropriate ARIA roles and keyboard navigation.
Include visual indicators for active links and focus states for better usability.
Performance:

Optimize the navbar for fast loading and minimal impact on performance.
Acceptance Criteria:

The new navbar should be visually appealing and consistent with the overall application design.
All proposed features should be functional and responsive across devices.
Accessibility standards (WCAG 2.1) should be met.
Additional Notes: Please provide any additional suggestions or features you believe would enhance the navbar.

![image](https://github.com/user-attachments/assets/1d80c8ee-9dd5-48fc-946b-2c2d8d003712)

**Comment by iamrahulmahato** [comment]
read the guidelines There is a strict mention there should not be any changes in the home page. Do not be demotivated and raise a new issue.
