### ISSUE TITLE
🧑‍💻 : Enhancing the Footer

### ISSUE THREAD

**Issue by byteom** [iamrahulmahato/master-web-development#1722]
🔴Title: **Enhancing the Footer** :
🔴 **Changes** : 

### Screenshots 📷
NA

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Om singh
Participant Role :- GSSOC Extd , Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by byteom** [comment]
/ i am resolving this issue

**Comment by iamrahulmahato** [comment]
Someone already working on it, Do not demotivate raise a new issue
