### ISSUE TITLE
Feature: add Simon say Game 

### ISSUE THREAD

**Issue by ishakatiyar06** [iamrahulmahato/master-web-development#173]
**Simon Says Game Description:**

Simon Says is a classic memory and reflex game that challenges players to follow a sequence of commands. The game involves a leader, "Simon," who gives verbal instructions, but players must only follow the commands if they begin with the phrase "Simon says." If a player acts without hearing "Simon says," they are eliminated from the round. The game tests attention, quick thinking, and listening skills, making it a fun and interactive activity for players of all ages. Perfect for parties, classrooms, or group gatherings, Simon Says encourages focus and sharpens concentration in an engaging way.

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
