### ISSUE TITLE
🧑‍💻 : Refactoring the footer of Home Page

### ISSUE THREAD

**Issue by VanshGarg06** [iamrahulmahato/master-web-development#1764]
:red_circle: **Title** :  Styling the Footer of the Home Page
:red_circle: **Enhancement Aim** : The footer will be enhanced to better the user experience
:red_circle: **Changes** : Styling of footer

### Screenshots 📷
![rahulmahtowebdeve footer](https://github.com/user-attachments/assets/6c98cedd-5b65-499a-86ef-649086652b4d)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Vansh Garg(Github username: @VanshGarg06)
Participant Role: GSSOC_EXT, HACKTOBERFEST, LEVEL 1 .

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
it  is solved
