### ISSUE TITLE
🧑‍💻 : Refactoring the header of the Home Page

### ISSUE THREAD

**Issue by VanshGarg06** [iamrahulmahato/master-web-development#1765]
:red_circle: **Title** : Styling the Header of the Home Page
:red_circle: **Enhancement Aim** : To enhance the styling of Home Page to better user experience
:red_circle: **Changes** :  Enhancement of the Header Page

### Screenshots 📷
![iamrahulmhto header](https://github.com/user-attachments/assets/ed49a720-0c26-49e1-8252-823356d2cd20)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Vansh Garg (Github username: @VanshGarg06)
Participant Role GGSOC-EXT, Hacktoberfest, level 2
***********************************************************************

Please assign this issue to me @iamrahulmahato as soon as possible under hacktoberfest and gssoc-ext with necessary labels.

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Someone is already working on it, so do not demotivate raise a new issue
