### ISSUE TITLE
📃: Countdown Timer 

### ISSUE THREAD

**Issue by haseebzaki-07** [iamrahulmahato/master-web-development#1768]
🔴 Title: Countdown Timer

🔴 Tech stack:

HTML
CSS
JavaScript
🔴 Objective:

To create a dynamic countdown timer that counts down to a specified event or date and time, displaying the remaining days, hours, minutes, and seconds.
🔴 Summary:

The countdown timer is a basic web project that provides a visual timer counting down to a specific date or event. When the page loads, JavaScript calculates the time difference between the current time and the target time, updating the display every second. It shows a real-time countdown with intuitive design, and optionally, additional features like notifications or celebratory messages can be displayed when the countdown completes. This project helps to practice JavaScript’s setInterval function, date manipulation, and DOM manipulation skills.

📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Haseeb Zaki
Participant Role: GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Someone is already working on it, so do not demotivate raise a new issue
