### ISSUE TITLE
[URGENT]🐞 : Invalid File Paths Causing Clone Errors

### ISSUE THREAD

**Issue by amitb0ra** [iamrahulmahato/master-web-development#1769]
:red_circle: **Title** : Unable to Clone Repository Due to Invalid Path in File Names

:red_circle: **Bug** : Cloning this repository leads to an error due to invalid file paths. Specific filenames or directory names contain whitespace or other special characters, causing issues in environments like Windows, which struggle with checkout for such paths.

:red_circle: **Changes** :  Rename directories and files with spaces or special characters to improve cross-platform compatibility. Use underscores or hyphens to replace spaces.  
   - **Example**: Rename `Voice-Controlled Flashcards Quiz` to `Voice-Controlled_Flashcards_Quiz`.
   -  ADD BETTER CONTRIBUTING GUIDELINES

### Screenshots 📷
N/A

************************************************************

✅ Details to Include When Taking the Issue:
Name : Amit Singh Bora
Participant Role : GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by amitb0ra** [comment]
@Sumanth077s @iamrahulmahato please look into this.

**Comment by amitb0ra** [comment]
i can't change folder names, as i am unable to clone the repo. can you add me as contributor from team or tell owners to change names or do it yourself.

also i can add contributing guidelines to follow and to check it a bot. so please add level 3 to it
@iamrahulmahato

**Comment by iamrahulmahato** [comment]
I believe the issue has been resolved; please update the fork, try again, and let me know.

**Comment by amitb0ra** [comment]
> I believe the issue has been resolved; please update the fork, try again, and let me know.

yeah clone working now. but project folder don't follow recommended naming guidelines.
So, can i add guidelines and pr checker for that? also i can change folder structure of current folders too

**Comment by iamrahulmahato** [comment]
Okay then go for it

**Comment by amitb0ra** [comment]
> So, can i add guidelines and pr checker for that? also i can change folder structure of current folders too

can you assign level 3 for that, also for my pr: #1776

**Comment by iamrahulmahato** [comment]
Due to restrictions in this repository, I am unable to assign you level three. However, I can grant you level 2, and I will do so based on your code.

**Comment by amitb0ra** [comment]
> Due to restrictions in this repository, I am unable to assign you level three. However, I can grant you level 2, and I will do so based on your code.

okay then assign level 2 please, check out #1776 code
