### ISSUE TITLE
📃: Personal Budget Tracker

### ISSUE THREAD

**Issue by haseebzaki-07** [iamrahulmahato/master-web-development#1770]
🔴 Title: Personal Budget Tracker

🔴 Tech stack:

HTML
CSS
JavaScript
🔴 Objective:

To create an interactive web application that allows users to manage their finances by tracking income, expenses, and savings. Users can add, edit, or delete financial entries to monitor their budget effectively.
🔴 Summary:

The Personal Budget Tracker is a basic web development project designed to help users manage their finances. The app interface includes input fields to enter income and expense details, along with their categories. Each entry dynamically updates the total balance, income, and expense amounts. JavaScript manages the data, performing calculations on each update, and displays categorized expenses to show where the user's money is going. This project helps develop skills in DOM manipulation, event handling, and local storage, allowing users to save data even after the page reloads.

📸 Screenshots
 N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : HASEEB ZAKI
Participant Role : GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Someone is already working on it, so do not demotivate raise a new issue
