### ISSUE TITLE
📃: added sudoku game

### ISSUE THREAD

**Issue by Aasthaa10** [iamrahulmahato/master-web-development#1775]
🔴 Title : update image

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :added new game called sudoku in the image section
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

GSSOC,Hacktoberfest***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Someone is already working on it, so do not demotivate raise a new issue
