### ISSUE TITLE
Add Weather Dashboard with API Integration

### ISSUE THREAD

**Issue by madhura-ingole** [iamrahulmahato/master-web-development#178]
**Description:**
- Build a Weather Dashboard to display real-time weather information.
- Use the OpenWeather API for fetching weather data.

**Requirements:**
- Create a search bar for city input.
- Fetch and display:
  1. Current temperature
  2. Weather conditions (e.g., sunny, rainy)
  3. Humidity and wind speed
  4. Weather icon
- Handle errors for invalid inputs and API failures.
- Ensure responsive design.

**Acceptance Criteria:**
- Users can search by city name.
- Display current weather data accurately.
- Show error messages for invalid inputs.

**Comment by Kameshnic** [comment]
assign this task to me i will do it sir

**Comment by madhura-ingole** [comment]
Resolved in #231
