### ISSUE TITLE
🧑‍💻 : Center the Project thumbnail

### ISSUE THREAD

**Issue by skstanwar** [iamrahulmahato/master-web-development#1789]
:red_circle: **Title** : Center the Project thumbnail
:red_circle: **Enhancement Aim** :  Center the all the project's thumbnail which are not aligned
:red_circle: **Changes** :CSS, HTML

### Screenshots 📷
![git_contri](https://github.com/user-attachments/assets/6752699d-eb52-43d6-9ed7-6bc04e334329)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Sanjay 
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by skstanwar** [comment]
Kindly assign to me @iamrahulmahato

**Comment by iamrahulmahato** [comment]
Someone is already working on it, so do not demotivate raise a new issue
