### ISSUE TITLE
📃: Adding Dice Game

### ISSUE THREAD

**Issue by shivhere007** [iamrahulmahato/master-web-development#1790]
🔴 Title : Dice Game
🔴 Tech stack : Html , CSS, JavaScript
🔴 Objective : Adding a new fun game project for beginners.
🔴 Summary :  The project typically includes HTML to display the game interface, CSS for styling, and JavaScript for game logic. The JavaScript code generates random numbers for each dice roll, updates the dice images accordingly. This project is great for beginners to practice DOM manipulation, event handling, and basic logic in JavaScript.

📸 Screenshots
![image](https://github.com/user-attachments/assets/424b87fc-d178-4617-a52c-10725993165c)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Shivam Prasad Singh
Participant Role : GSSoC 2024 Extd Contributor, Hacktoberfest

***********************************************************************

Kindly assign it to me asap @iamrahulmahato .

**Comment by iamrahulmahato** [comment]
Someone is already working on it, so do not demotivate raise a new issue
