### ISSUE TITLE
📃: Addition of Whack a Mole 

### ISSUE THREAD

**Issue by pratheekv39** [iamrahulmahato/master-web-development#1803]
🔴 Title: Whac-A-Mole
🔴 Tech stack:
            1) HTML
            2) CSS
            3) JavaScript

🔴 Objective:
The objective of the Whac-A-Mole game is to test the player's reaction speed and hand-eye coordination. The player must quickly click on the moles as they randomly appear from holes to earn points within a given time limit.

🔴 Summary:
Whac-A-Mole is a classic arcade-style game implemented using HTML, CSS, and JavaScript. The game features a grid of holes where moles randomly pop up. The player's goal is to whack the moles by clicking on them as quickly as possible. Each successful hit earns the player a point. The game has a set time limit, and the player aims to achieve the highest score within that time. The HTML file structures the game layout, the CSS file styles the game elements, and the JavaScript file handles the game logic, including mole activation, score tracking, and game timer. The game provides an entertaining and interactive experience for players to test their skills and reflexes.

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : V Pratheek
Participant Role : Contributor at GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎
@iamrahulmahato  Kindly assign this issue ASAP . Thanks :)

**Comment by iamrahulmahato** [comment]
Someone is already working on it, so do not demotivate raise a new issue
