### ISSUE TITLE
Add a separate section for FAQs

### ISSUE THREAD

**Issue by shivenyadavs** [iamrahulmahato/master-web-development#1825]
# Description:
We need a dedicated FAQ page to provide users with answers to common questions about contributing to open-source projects and mastering web development. This page should improve user experience by offering easily accessible information.

# Features:
A list of frequently asked questions categorized by topics (e.g., contributions, project guidelines, learning resources).
Clear, concise answers to help users navigate the platform.
A search bar or filter to quickly find relevant FAQs.
# Task List:

 Design the layout for the FAQ page.
 Add categories for FAQs.
 Implement a search/filter function for ease of use.
 Ensure responsiveness and accessibility.

**Comment by iamrahulmahato** [comment]
someone is already working on it
