### ISSUE TITLE
📃: Adding Algorith Visualizers

### ISSUE THREAD

**Issue by Ananyashetty7** [iamrahulmahato/master-web-development#1827]
🔴 Title :
🔴 Tech stack :
🔴 Objective :
🔴 Summary :
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
you have already raised the same issue before
