### ISSUE TITLE
🧑‍💻 : 

### ISSUE THREAD

**Issue by saksham-1304** [iamrahulmahato/master-web-development#1852]
:red_circle: **Added Media Queries To Make The Website Respnsive** :

### Screenshots 📷

![image](https://github.com/user-attachments/assets/c6061b1c-b42e-4d41-9917-04857c5d299b)

**********************************************************************
✅ Details to Include When Taking the Issue:
Please Assign this issue under Gssoc and hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
@saksham-1304 Someone is already working on it, so do not demotivate raise a new issue
