### ISSUE TITLE
📃: Rock-Paper-Scissor Game

### ISSUE THREAD

**Issue by Ananyashetty7** [iamrahulmahato/master-web-development#1904]
🔴 Title :Rock-Paper-Scissor Game
🔴 Tech stack :HTML, CSS, JavaScript
🔴 Objective :To implement a Rock Paper Scissors game where users can play against the computer. The game will include a scoreboard to track the user's and computer's scores and pop-up messages to announce the winner and other messages of each round. The UI will be designed to be user-friendly and engaging.
🔴 Summary :This feature will add an interactive Rock Paper Scissors game to the project, allowing users to play a classic game against the computer. 
Key features include:

Scoreboard: Displays the user’s and computer’s current scores.
Game Play: Players can choose "Rock," "Paper," or "Scissors," and the computer randomly selects one as well.
Winner Messages: Pop-up messages show the result of each round (win, lose, or draw).
User-Friendly Interface: The UI will be visually appealing and intuitive, enhancing the overall user experience.
📸 Screenshots

N/A
***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Ananya G Shetty
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project is already exist
