### ISSUE TITLE
🧑‍💻 : Changing of header with adding some buttons as Home, Games, Newsletter and others

### ISSUE THREAD

**Issue by Jitendrarajputt** [iamrahulmahato/master-web-development#1974]
:red_circle: **Title** : Changing of Header
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : Want to add buttons in header with animation and as when we click on them we'll be reaching to that page directly

### Screenshots 📷
![Screenshot 2024-10-30 092237](https://github.com/user-attachments/assets/544f37fd-be72-42f4-8099-31a0c5d6f51a)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Jitendra Rajput
GSSOC Extd. Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Jitendrarajputt** [comment]
I would like to work on this kindly assign me this

**Comment by iamrahulmahato** [comment]
no  we are not adding that
