### ISSUE TITLE
Add Crypto Currenct Tracking Website

### ISSUE THREAD

**Issue by Prajyot05** [iamrahulmahato/master-web-development#198]
I want to add a frontend reactjs website that uses an API to fetch the latest data about crypto prices and showcases them in a visually appealing manner

**Comment by Prajyot05** [comment]
@iamrahulmahato Can you assign this to me?

**Comment by iamrahulmahato** [comment]
already someone added, Do not be demotivated and raise a new issue.

**Comment by Prajyot05** [comment]
@iamrahulmahato Are you sure? I Cannot find it on the website link
