### ISSUE TITLE
🐞 : Text is not Visible in feedback form 

### ISSUE THREAD

**Issue by anjali5Xcode** [iamrahulmahato/master-web-development#1990]
:red_circle: **Title** : Feedback form issue
:red_circle: **Bug** :  Text is not Visible in feedback form and there is no confirmation after submitting the form 
:red_circle: **Changes** :   will change the color of the text and add confirmation message on submitting the form 

### Screenshots 📷

![Screenshot (185)](https://github.com/user-attachments/assets/55b7ce6f-1aa2-49cd-94bd-226c75c233e3)

************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):  GSSOC and Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Vaishnavibussa** [comment]
Can I work on this issue..I'm good at styling and making the UI eye catching!
