### ISSUE TITLE
📃: Add new project YouTube Homepage Clone

### ISSUE THREAD

**Issue by karthikyandrapu** [iamrahulmahato/master-web-development#1998]
🔴 Title : YouTube Homepage Clone
🔴 Tech stack : HTML, CSS, JavaScript
🔴 Objective : Developing a functional clone of the YouTube homepage using HTML, CSS, and JavaScript. This project focuses on recreating the core front-end elements, including a responsive layout, search functionality, sidebar navigation, and video listings. The goal is to deliver a user-friendly and visually engaging interface resembling YouTube’s design.
🔴 Summary :
📸 Screenshots:
![Screenshot (237)](https://github.com/user-attachments/assets/c6a290a7-8868-4664-b5c3-617f026221f3)

Dark Mode:
![Screenshot (236)](https://github.com/user-attachments/assets/526fe0dc-d24e-4716-aef0-3485e6a6a12a)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name: karthikyandrapu
Participant Role: GSSoC'24-Extd and Hacktoberfest Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
we are not adding any clone website due to deployment issue
