### ISSUE TITLE
Improve color of toggle theme icon

### ISSUE THREAD

**Issue by shivamy009** [iamrahulmahato/master-web-development#200]
![Screenshot 2024-10-02 214531](https://github.com/user-attachments/assets/05e25081-d820-452f-9d7b-dc68023316da)
Improve color of this icon

Please assign me to solve this issue

**Comment by HafsaIffath** [comment]
Please assign this issue to me, I can work on it. @iamrahulmahato

**Comment by iamrahulmahato** [comment]
The guidelines state that there should be no changes to the home page.
