### ISSUE TITLE
📃: Adding DisneyHotstar Clone Project

### ISSUE THREAD

**Issue by shivhere007** [iamrahulmahato/master-web-development#2000]
🔴 Title :
🔴 Tech stack : Html, CSS and javaScript
🔴 Objective : Add a new project
🔴 Summary : The Disney+ Hotstar clone project helps the beginners to learn and practice making responsive clone projects.
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Shivam Prasad Singh
Participant Role :  GSSOC'24 Extd Contributor, Hacktoberfest 2024 Contribuor
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
we are not adding any clone website due to deployment issue
