### ISSUE TITLE
🧑‍💻 : adding spotify frontend clone project

### ISSUE THREAD

**Issue by vibhorgupta09** [iamrahulmahato/master-web-development#2003]
🔴 Title :adding spotify frontend clone project
🔴 Tech stack : Html, CSS and javaScript
🔴 Objective : Add a new project
🔴 Summary : The spotify clone project helps the beginners to learn and practice making responsive clone projects.
📸 Screenshots

✅ Details to Include When Taking the Issue:
Name : Vibhor Gupta
<img width="1512" alt="Screenshot 2024-10-31 at 1 30 10 PM" src="https://github.com/user-attachments/assets/86462e3b-e54d-4b2d-88ce-6762208dcd74">

Participant Role : GSSOC'24 Extd Contributor, Hacktoberfest 2024 Contributor

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
we are not adding any clone website due to deployment issue
