### ISSUE TITLE
📃: dding JS simon says game 

### ISSUE THREAD

**Issue by vibhorgupta09** [iamrahulmahato/master-web-development#2004]
🔴 Title :adding JS simon says game 
🔴 Tech stack : Html, CSS and javaScript
🔴 Objective : Add a new project
🔴 Summary : This 
<img width="1512" alt="Screenshot 2024-10-31 at 1 37 20 PM" src="https://github.com/user-attachments/assets/40523a4e-7c06-4336-b9dc-a1be65fdba3b">
project helps the beginners to learn and practice javascript fundamentals.
📸 Screenshots

✅ Details to Include When Taking the Issue:
Name : Vibhor Gupta
Screenshot 2024-10-31 at 1 30 10 PM

Participant Role : GSSOC'24 Extd Contributor, Hacktoberfest 2024 Contributor

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
it is already there
