### ISSUE TITLE
📃: 

### ISSUE THREAD

**Issue by vibhorgupta09** [iamrahulmahato/master-web-development#2005]
🔴 Title :adding a weather app project built using react.
🔴 Tech stack : Html, CSS,javaScript, React
🔴 Objective : Add a new project
🔴 Summary : The weather app project helps the beginners to learn and practice react. it is fully fucntional and uses geocoding apis too
📸 Screenshots

✅ Details to Include When Taking the Issue:
Name : Vibhor Gupta
Screenshot 2024-10-31 at 1 30 10 PM

Participant Role : GSSOC'24 Extd Contributor, Hacktoberfest 2024 Contributor

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
it is already there
