### ISSUE TITLE
🐞 : Improving the UI of buttons !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [iamrahulmahato/master-web-development#2006]
:red_circle: **Title** : Improving the UI of buttons !!
:red_circle: **Bug** : Buttons appear inconsistent or outdated in style.
:red_circle: **Changes** :  Update button styling to enhance visual consistency and align with the overall UI theme.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/7d8a0ab4-6e58-4b19-9d9e-c5d18db9fe01)

************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC 24 , Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by BhavikaPachauri** [comment]
assign me the task under GSSOC AND HACKTOBERFEST .
