### ISSUE TITLE
📃: Creating a new chatbot !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [iamrahulmahato/master-web-development#2007]
🔴 Title : Chatbot
🔴 Tech stack : Chatbase
🔴 Objective : Develop an interactive chatbot to assist users with queries and enhance user engagement.
🔴 Summary : This chatbot will leverage AI and NLP to understand user inputs and provide relevant responses, integrating smoothly within the platform.
📸 Screenshots

### The present chatbot is not working properly i will make sure to create an new chatbot acc to the UI , and add a pop up option at the right down corner of the website !!
![image](https://github.com/user-attachments/assets/de114d42-cb8b-40ab-bf96-aea5df9a4d99)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : SrijaVuppala
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC , Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by BhavikaPachauri** [comment]
assign me the task under GSSOC AND HACKTOBERFEST .
