### ISSUE TITLE
🧑‍💻 : Removing Duplicate items, fixing UI

### ISSUE THREAD

**Issue by ishicodz** [iamrahulmahato/master-web-development#2010]
:red_circle: **Title** :Removing Duplicate items, fixing UI
:red_circle: **Enhancement Aim** :improving user interface
:red_circle: **Changes** :  
- remove duplicate icons and buttons
- fix overlapping items
- improve UI to make the text more readable

@iamrahulmahato please assign this issue to me under the gssoc-ext, hacktoberfest-accepted, and level label.

### Screenshots 📷
<img width="890" alt="Screenshot 2024-10-31 163408" src="https://github.com/user-attachments/assets/82577141-89a8-47a3-9d62-c20f73400be6">

<img width="763" alt="Screenshot 2024-10-31 163512" src="https://github.com/user-attachments/assets/0979545c-65c6-462e-b7c3-a181e9979dc8">

<img width="272" alt="Screenshot 2024-10-31 163626" src="https://github.com/user-attachments/assets/0c3cc3b4-5cc4-443e-9db0-d70edeff6a0f">

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :Ishita Gupta
Participant Role: GSSOC contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by BhavikaPachauri** [comment]
assign me the task under GSSOC AND HACKTOBERFEST .
