### ISSUE TITLE
🧑‍💻 :  Duplication of Search Bar

### ISSUE THREAD

**Issue by VanshGarg06** [iamrahulmahato/master-web-development#2028]
:red_circle: **Title** : Duplication Of Search Bar
:red_circle: **Enhancement Aim** : Search Bar for the Games are duplicated on the Home Page
:red_circle: **Changes** : Removal of the Duplication of Search Bar

### Screenshots 📷
![image](https://github.com/user-attachments/assets/fab8d967-abbd-4fa9-bf91-c95ac670ce66)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Vansh Garg(Github username: @VanshGarg06)
Participant Role: GSSOC-EXT, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by LithikkaDharmaraj** [comment]
i would like to work on this issue
