### ISSUE TITLE
🧑‍💻 : Create an Accounts Page with login and signup page and 3rd Party authentication using Aouth

### ISSUE THREAD

**Issue by sania-2912** [iamrahulmahato/master-web-development#2037]
:red_circle: **Title** :Create an Accounts Page with login and signup page and 3rd Party authentication using Aouth
:red_circle: **Enhancement Aim** : Currently in the footer section there is an accounts page button. However it is not responsive yet. Thus the website requires a login and a signup page
:red_circle: **Changes** : Create a login + signup page along with signin, login buttons using google account

### Screenshots 📷
![Screenshot 2024-11-02 170434](https://github.com/user-attachments/assets/f508328c-a64a-404f-9488-4748bfbfd77d)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Sania Golhar
Participant Role: GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
no we are not adding that
