### ISSUE TITLE
Improve light and dark mode UI

### ISSUE THREAD

**Issue by prasoonk1204** [iamrahulmahato/master-web-development#205]
#### The light-dark mode toggle would be like a sun in dark mode
![Screenshot 2024-10-02 233011](https://github.com/user-attachments/assets/e6f3bbcc-43be-4c63-b4a8-552fb5c28d6f)

### also in light mode, the difference between the background and cards colors is really narrow, there i want to create a good visual separation between the two
![Screenshot 2024-10-02 233138](https://github.com/user-attachments/assets/313178fa-0c4f-48d2-8e35-690f5cdaaa93)

## It's my first issue. please assign it to me :)

**Comment by iamrahulmahato** [comment]
In the guidelines, it is already mentioned there should not be any changes in the home page, Do not be demotivated and raise a new issue.
