### ISSUE TITLE
📃: Want to add contribution page in footer section

### ISSUE THREAD

**Issue by sanikamandale17** [iamrahulmahato/master-web-development#2051]
🔴 Title :Want to add contribution page in footer section (link)
🔴 Tech stack :want to add contribution page plz assign this ti me @iamrahulmahato 
🔴 Objective :
🔴 Summary :
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
we are not adding that because already it is added
