### ISSUE TITLE
🧑‍💻 : Dark Mode is not performing fine

### ISSUE THREAD

**Issue by VanshGarg06** [iamrahulmahato/master-web-development#2054]
:red_circle: **Title** :  Under Dark Mode Things are not appropriate
:red_circle: **Enhancement Aim** : The Styling will be done for the Elements under Dark Mode
:red_circle: **Changes** : 
1. Improve the font style of text
2. Improve the elements under Dark Mode
3. Improve the Alignment of Elements

### Screenshots 📷
![image](https://github.com/user-attachments/assets/cd1dd873-66c5-4507-9166-82dc096de131)
![image](https://github.com/user-attachments/assets/1d54b5dc-5744-4834-8f57-3045edf402c5)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Vansh Garg(Github username: @VanshGarg06)
Participant Role: GSSOC-EXT , Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Agent123f** [comment]
can you please tell me the directory where is the html document and other file of this is prensent
