### ISSUE TITLE
🐞 : CARDS ALIGNMENT ISSUE

### ISSUE THREAD

**Issue by Meetpidev** [iamrahulmahato/master-web-development#2063]
:red_circle: **CARDS ARE DISPLAY VERTICALY** :
:red_circle: **Bug** :
:red_circle: **NEED TO DISPLAY IT HORIZONTALY** :  

### Screenshots 📷
![image](https://github.com/user-attachments/assets/95e4a93d-0efd-41f4-bb3b-e45c68e87567)

************************************************************

✅ Details to Include When Taking the Issue:
Name : MEET SHAH
Participant Role: CONTRIBUTER ( GSSOC, Hacktoberfest )

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
someone already working on it
