### ISSUE TITLE
Add Hover descriptions for each card

### ISSUE THREAD

**Issue by Varshitha713** [iamrahulmahato/master-web-development#207]
Hi @iamrahulmahato 
noticed that user may find it difficult to understand few games like what it actually does . I was thinking of adding brief description over each project title, for a quick overview. 
(from a user pov I didn't understand the 8 puzzle  game rules and it's functionalities thought i can improve that)

**Comment by iamrahulmahato** [comment]
In the guidelines, it is already mentioned there should not be any changes in the home page, Do not be demotivated and raise a new issue.
