### ISSUE TITLE
📃: TIC TAC DOOM game

### ISSUE THREAD

**Issue by AE-Hertz** [iamrahulmahato/master-web-development#2078]
🔴 Title :TIC TAC DOOM game
🔴 Tech stack : html,css,js
🔴 Objective : feat
🔴 Summary :
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :AE_hertz
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

Assign me this issue pls. @iamrahulmahato

**Comment by iamrahulmahato** [comment]
already there
