### ISSUE TITLE
Add smooth fade-in and out animation

### ISSUE THREAD

**Issue by prasoonk1204** [iamrahulmahato/master-web-development#208]
Currently the website is clean and simple which look really good, but a subtle animation on the elements upon scrolling will make it more visually appealing.

I have done the same in my portfolio, you can take a look at it: https://prasoonk.vercel.app

Please assign it to me :)

**Comment by iamrahulmahato** [comment]
In the guidelines, it is already mentioned there should not be any changes in the home page, Do not be demotivated and raise a new issue.

**Comment by prasoonk1204** [comment]
Ohh i may have missed that
