### ISSUE TITLE
📃: the great simon game

### ISSUE THREAD

**Issue by AE-Hertz** [iamrahulmahato/master-web-development#2080]
🔴 Title :the great simon game
🔴 Tech stack :html,css,js
🔴 Objective :
🔴 Summary :
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

Assign me this issue.

**Comment by iamrahulmahato** [comment]
already there
