### ISSUE TITLE
📃: Adding Whack a mole game

### ISSUE THREAD

**Issue by AbhijitMotekar99** [iamrahulmahato/master-web-development#2090]
🔴 Title :Whack-a-Mole Game
🔴 Tech stack : HTML, CSS, JavaScript
🔴 Objective : To create an interactive browser-based Whack-a-Mole game that helps users improve reaction speed and coordination while providing a fun gaming experience. This project serves as a practical introduction to basic DOM manipulation, event handling, and time-based animations in web development.

🔴 Summary : The Whack-a-Mole game is a classic arcade-style game where the objective is to "whack" or click on randomly appearing moles in a grid within a given time frame. Each successful whack scores points, with the moles disappearing shortly after appearing to increase the challenge.
The project demonstrates essential concepts like event listeners, intervals for timed mole appearances, score tracking, and basic CSS styling to create an engaging user experience.
Potential additional features could include difficulty levels, sound effects for whacks, and animations to enhance gameplay. The game is an excellent way to strengthen JavaScript skills and understand core concepts of interactivity in web applications.

📸 Screenshots

![whack a mole](https://github.com/user-attachments/assets/93b9aaf6-114d-4d62-bd10-0c3735f7e37c)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Abhijit Motekar
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.) : `gssoc-ext` `Hacktoberfest`

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already added
