### ISSUE TITLE
📃: Want to add web application of RockPaperScissor game 

### ISSUE THREAD

**Issue by Jivanjamadar** [iamrahulmahato/master-web-development#2096]
🔴 Title : RockPaperScissor
🔴 Tech stack : HTML, CSS and JS
🔴 Objective : 
A simple & interactive  web-application Rock-Paper-Scissors game  built with HTML, CSS, and JavaScript. 

🔴 Summary :
A simple and interactive Rock-Paper-Scissors game built with HTML, CSS, and JavaScript. This web application features a modern design, animations, and a user-friendly interface.

📸 Screenshots
![image](https://github.com/user-attachments/assets/7ff5bc9e-9686-4b02-9016-c9957c2a83d0)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Jivan Jamdar
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Jivanjamadar** [comment]
@iamrahulmahato assign this issue to me

**Comment by iamrahulmahato** [comment]
already added
