### ISSUE TITLE
📃: adding drum kit game

### ISSUE THREAD

**Issue by priyashuu** [iamrahulmahato/master-web-development#2109]
🔴 Title :Drum kit game
🔴 Tech stack :html ,css , javascript
🔴 Objective :The Drum Kit is an interactive web application that allows users to play various drum sounds using both mouse clicks and keyboard inputs. It features seven different types of drum sounds, each associated with a unique button on the screen and a corresponding key on the keyboard.
🔴 Summary :
📸 Screenshots

![Screenshot 2024-07-05 234955](https://github.com/user-attachments/assets/d8c336e1-6ee9-4bb0-ad28-e3e1fb4c33d8)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Priya Rani
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):GSSOC, Hacktoberfest,

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already available
