### ISSUE TITLE
🐞 : 

### ISSUE THREAD

**Issue by GitWizzz** [iamrahulmahato/master-web-development#2115]
:red_circle: **Footer Styling Overlap Issue** :
:red_circle: **Footer sections overlap, causing unreadable text and misalignment** :
:red_circle: **Changes** :  Adjust the footer container height and fix the alignment of the links. Modify the background color to ensure all text is visible.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/718736ba-041f-4805-9bef-2e0d6e2fd70f)

************************************************************

✅ Details to Include When Taking the Issue:
Name : Shivam Kumar
Participant Role ( GSSOC):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
corrected
