### ISSUE TITLE
📃: Add EMI Calculator to the Website

### ISSUE THREAD

**Issue by VanshGarg06** [iamrahulmahato/master-web-development#2154]
🔴 Title : Add EMI Calculator
🔴 Tech stack : HTML,CSS, Javascript
🔴 Objective : Add EMI Calculator to the Website
🔴 Summary :
EMI Calculator is one of the major tool to calculate EMI for a loan taken with stipulated time. This tool needs to be on the website.

📸 Screenshots
![image](https://github.com/user-attachments/assets/9fc5ceca-731f-4a62-8ee2-2029ea2472c0)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Vansh Garg(Github username: @VanshGarg06 )
Participant Role: GSSOC-EXT, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by VanshGarg06** [comment]
@iamrahulmahato Please assign this task to me under Hacktoberfest and gssoc-ext with necessary labels level 2. Please assign this task to me @VanshGarg06 as soon as possible.

**Comment by iamrahulmahato** [comment]
already available
