### ISSUE TITLE
Adding a Custom effect in Cursor .

### ISSUE THREAD

**Issue by AnujShrivastava01** [iamrahulmahato/master-web-development#218]
Step 1: CSS for Custom Cursor
Step 2: HTML Structure
Step 3: JavaScript for Additional Effects

https://github.com/user-attachments/assets/ad3f586a-ae88-4f2e-9986-5e8c6fd3ab23

We can also change its color as per our choice.

Please Assign this to me.
Thankyou!

**Comment by iamrahulmahato** [comment]
In the guidelines, it is already mentioned there should not be any changes in the home page, Do not be demotivated and raise a new issue.
