### ISSUE TITLE
📃: Spotify Clone add

### ISSUE THREAD

**Issue by imsudiptaa** [iamrahulmahato/master-web-development#2185]
🔴 Title : Spotify Clone
🔴 Tech stack : HTML, CSS
🔴 Objective : Adding Spotify Clone in main page under Websites Section
📸 Screenshots

N/A
***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Sudipta Mandal (GitHub Username: @imsudiptaa)
Participant Role ( GSSOC-EXTD):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by imsudiptaa** [comment]
@iamrahulmahato Assign this to me

**Comment by iamrahulmahato** [comment]
Because of a deployment issue, we are not adding any clone websites.
