### ISSUE TITLE
Add Famous Simon Game

### ISSUE THREAD

**Issue by RiteshS1** [iamrahulmahato/master-web-development#220]
I would like to contribute to this project by adding yet another one of my game the famous Simon Game; previously I worked upon the Snake Game on this repo!

My Simon Game would look like 
![Screenshot 2024-09-22 003915](https://github.com/user-attachments/assets/2e758104-e929-4f1e-80cd-178bf1f417f9)

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
