### ISSUE TITLE
Add TODO List with Vue

### ISSUE THREAD

**Issue by JCarlosR** [iamrahulmahato/master-web-development#221]
There is already a TODO List app built with **vanilla js**.

Would like to add a **Vue** version to showcase the differences for newcomers.

Please assign to me and add the corresponding labels.

**Comment by Tapabrata-Goswami** [comment]
@JCarlosR can you try with another tech stack

**Comment by JCarlosR** [comment]
> @JCarlosR can you try with another tech stack

Oh, I believe Vue has a good learning curve, but which one would you like? Maybe React or Svelte?

**Comment by iamrahulmahato** [comment]
The project already exist, Do not be demotivated and raise a new issue.
