### ISSUE TITLE
Stick hero with canvas

### ISSUE THREAD

**Issue by DiwareNamrata23** [iamrahulmahato/master-web-development#223]
the game consists of how long you can take jump

**Comment by Tapabrata-Goswami** [comment]
@DiwareNamrata23 have you demo? Can you elaborate in a summary?

**Comment by Tapabrata-Goswami** [comment]
@DiwareNamrata23  Any mouse button activity present in that or does this work on hover?

**Comment by DiwareNamrata23** [comment]
Yes we have to hold the mouse to enlarge the stick so that the length of stick should be efficient to get cross the road

**Comment by DiwareNamrata23** [comment]
And score depends on how many times sticks used to cross the road

**Comment by Tapabrata-Goswami** [comment]
> <img alt="Screenshot 2024-10-03 at 10 55 09 AM" width="1440" src="https://private-user-images.githubusercontent.com/142529986/373127942-beb41cbb-7b04-4065-a2ff-7c62ae38585c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5Mzc1MjcsIm5iZiI6MTcyNzkzNzIyNywicGF0aCI6Ii8xNDI1Mjk5ODYvMzczMTI3OTQyLWJlYjQxY2JiLTdiMDQtNDA2NS1hMmZmLTdjNjJhZTM4NTg1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QwNjMzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDZmOGE0M2Y0YWQ3MzFlNjliZGU4MmU3NDhmZGEyMzIzZTc5ZjY0OTVkMDlmMGQwNjUxOGZkYTZlZmU0Y2Q2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.59y7jb24CvfrlQ-hrYa3oCloJnTmwCcZ48H6VGMfHMY"> some what like this We have to hold the mouse to get enlarge the stick after the stick gets enlarge the hero could go and cross the gaps in his roads.

@DiwareNamrata23 Is this the design of this game?

**Comment by DiwareNamrata23** [comment]
Yes

**Comment by Tapabrata-Goswami** [comment]
@DiwareNamrata23 Ok, cool you can.
