### ISSUE TITLE
🧑‍💻 : Add bottom to top scrolling feature 

### ISSUE THREAD

**Issue by Ashmitha2606** [iamrahulmahato/master-web-development#2239]
:red_circle: **Title** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : 

### Screenshots 📷

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already have
