### ISSUE TITLE
📃: Drum-kit (music game)

### ISSUE THREAD

**Issue by Ashmitha2606** [iamrahulmahato/master-web-development#2240]
🔴 Title :
🔴 Tech stack :
🔴 Objective :
🔴 Summary :
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already have
