### ISSUE TITLE
📃: Random Meal Generator

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [iamrahulmahato/master-web-development#2246]
🔴 Title : Random Meal Generator
🔴 Tech stack : HTML CSS js
🔴 Objective : Generates a random meal idea from a list when users click a button, showing ingredients and instructions
🔴 Summary : NA
📸 Screenshots
na

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : sanika bhalerao
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already have
