### ISSUE TITLE
Add "Back to Top" Button

### ISSUE THREAD

**Issue by prachi-kurmi** [iamrahulmahato/master-web-development#225]
Description:

I noticed that there is no button on the website to quickly go back to the top of the page. This feature would be helpful for users, especially when they scroll down a lot.

Suggested Changes:
  1) Add a "Back to Top" button that appears when the user scrolls down.
  2) The button should smoothly scroll the user back to the top when clicked.

This change will improve the user experience by making navigation easier.

![Screenshot 2024-10-03 105917](https://github.com/user-attachments/assets/87a3c0bc-250e-41f0-889d-706ca18bb85f)

Please assign this issue to me under GSSoC-Extd so I can start working on it.
Thank you!

**Comment by Tapabrata-Goswami** [comment]
@prachi-kurmi maintains the **theme color.**
