### ISSUE TITLE
📃: Quiz App

### ISSUE THREAD

**Issue by viv2005ek** [iamrahulmahato/master-web-development#2257]
🔴 Title : Quiz App
🔴 Tech stack : Html, css,js
🔴 Objective :  quiz game that lets users answer multiple-choice questions and get instant feedback
🔴 Summary : Scoring, timer, feedback, and question randomization
📸 Screenshots
N/A
***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Vivek Kumar Garg
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already have
