### ISSUE TITLE
📃: Currency Converter

### ISSUE THREAD

**Issue by viv2005ek** [iamrahulmahato/master-web-development#2258]
🔴 Title : Currency Converter
🔴 Tech stack : Html,css,js
🔴 Objective : Real-time data fetching, input handling, conversion calculations
🔴 Summary : an interactive gallery that displays images in a grid layout, with options for filters, sorting, and image preview
📸 Screenshots
N/A
***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Vivek Kumar Garg
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already have
