### ISSUE TITLE
Add Medicine Prediction System

### ISSUE THREAD

**Issue by ishakatiyar06** [iamrahulmahato/master-web-development#226]
The **Medicine Prediction System** is a healthcare application designed to assist doctors and patients in identifying appropriate medications based on symptoms and medical history. The system leverages data to predict and suggest possible prescriptions, improving the accuracy and speed of diagnosis. Key functionalities include symptom input, real-time medicine recommendations, personalized treatment plans, and secure storage of medical records. It aims to streamline the prescription process, enhance patient care, and reduce errors in medication by providing reliable and data-driven predictions.

**Comment by Tapabrata-Goswami** [comment]
@ishakatiyar06 elaborate on the **tech stack & architecture**. How does this system fit for our repo?

**Comment by ishakatiyar06** [comment]
It is a web application which have both frontend and backend. Login/Signup module using Flask framework and frontend using html, css and js which predicts the disease, precautions and medicines based on the user input. It predicts disease using machine learning algorithm.

**Comment by ishakatiyar06** [comment]
Hey can you guide me how do I add my application? I have forked this repository, then what should i do next?
