### ISSUE TITLE
📃: ShopSphere: Full-Stack E-commerce Platform

### ISSUE THREAD

**Issue by priyanshinegi07** [iamrahulmahato/master-web-development#2260]
🔴 Title :ShopSphere: Full-Stack E-commerce Platform
🔴 Tech stack : HTML, CSS, JavaScript, node.js, express.js, bootstrap
🔴 Objective : The objective is to provide a user-friendly and secure platform where consumers can easily purchase products and retailers can list and manage their products.
🔴 Summary : The project would have cart and wishlist functionalities, authentication, reviews of products, visually appealing ui.
📸 Screenshots 
![image](https://github.com/user-attachments/assets/8ee75164-ac25-4b48-9fdf-25039fdf385d)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Priyanshi Negi
Participant Role: GSSOC Extd Contributer, Hacktoberfest Contributor

***********************************************************************
I want to work on it.
@iamrahulmahato can you please assign me this issue?
Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by priyanshinegi07** [comment]
@serenagomez060203 @Tapabrata-Goswami @twinkle-tripti7 can you please assign this to me?

**Comment by iamrahulmahato** [comment]
@priyanshinegi07 We will not be adding this because of deployment problems.
