### ISSUE TITLE
Weather Forecasting Web Application

### ISSUE THREAD

**Issue by priyanshinegi07** [iamrahulmahato/master-web-development#2268]
I want to create a weather application which will give weather details of a particular location(temperature, precipitation, humidity etc) along with icons. There will also be a feature to compare the weather of two different places.

Technologies used: HTML, CSS, JavaScript, API integration

@iamrahulmahato I want to work on this. Can you please assign me this issue?

**Comment by iamrahulmahato** [comment]
@priyanshinegi07 someone already working on it
