### ISSUE TITLE
📃: Expense Splitter for Friends

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [iamrahulmahato/master-web-development#2297]
🔴 Title : Expense Splitter for Friends
🔴 Tech stack : HTML CSS js
🔴 Objective : A tool where users enter amounts spent and split costs evenly among friends, showing individual shares
🔴 Summary : NA
📸 Screenshots
 NA

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Sanika Bhalerao
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already have
