### ISSUE TITLE
📃: Ping Pong Game

### ISSUE THREAD

**Issue by rajnil9** [iamrahulmahato/master-web-development#2319]
🔴 Title : PING PONG GAME
🔴 Tech stack : HTML , CSS , JAVASCRIPT
🔴 Objective : To make a ping pong game
🔴 Summary : to make a ping pong game where we play against computer by using tiles to hit back the ball towards the opponent
📸 Screenshots : N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Rajnil Saha
Participant Role : GSSOC Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already have
