### ISSUE TITLE
[BUG] Counter app icons(+/-) should response when clicked

### ISSUE THREAD

**Issue by 4F24L** [iamrahulmahato/master-web-development#232]
## Changes to be made
- The plus and minus key should response when clicked
- Responses like - color changes / scaling a bit / make a sound / can be anything else

## Screenshot :
![image](https://github.com/user-attachments/assets/7c7c84e9-ab97-4376-a1c4-db174c6e306c)

Please add hactoberfest and GSSoC24 tag. You can assign me for this issue @iamrahulmahato

**Comment by Tapabrata-Goswami** [comment]
Hi, @4F24L can you check now, I think It's solved in issue #230

**Comment by 4F24L** [comment]
Hello, @Tapabrata-Goswami

I checked that issue and PR. But this issue is different.

I talked about CSS improvement, the plus minus icon should give a response when clicked. Responses like - color changes / scaling a bit / make a sound / can be anything else.

**Comment by Tapabrata-Goswami** [comment]
@4F24L ok, you can start work on this.
