### ISSUE TITLE
📃: RANDOM IMAGE GENERATOR 

### ISSUE THREAD

**Issue by rajnil9** [iamrahulmahato/master-web-development#2320]
🔴 Title : Random Image Generator 
🔴 Tech stack : Html , Css , Javascript
🔴 Objective : to make an image generative application
🔴 Summary : When pressed on generate it generates a random image 
📸 Screenshots :  N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Rajnil Saha
Participant Role  : GSSOC Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already have
