### ISSUE TITLE
📃: BUBBLE SHOT GAME

### ISSUE THREAD

**Issue by rajnil9** [iamrahulmahato/master-web-development#2321]
🔴 Title :  BUBBLE SHOT GAME
🔴 Tech stack : Html , Css , Javascript
🔴 Objective : to make a game that shoots bubbles
🔴 Summary : shoots bubbles using a launcher and collects score 
📸 Screenshots : N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Rajnil Saha
Participant Role : GSSOC Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
We can not add this since we already have this project.
