### ISSUE TITLE
Typing Speed Test Path Issue - any one to fix

### ISSUE THREAD

**Issue by Tapabrata-Goswami** [iamrahulmahato/master-web-development#233]
Issue in this code. The image path is wrong, the game thumbnail not showing.
![image](https://github.com/user-attachments/assets/c8f907e2-7168-4821-be3a-2a9e9fc59ee8)
This is the game

![image](https://github.com/user-attachments/assets/6352e704-7762-492c-b6c3-51804b37f124)

when we open this game CSS not working 
output
![image](https://github.com/user-attachments/assets/37fff39a-f454-4a29-8527-513a626cfb8d)

Help to fix this issue.

**Comment by Japneet001** [comment]
Which Image do I have to add
Could you send that Image?

**Comment by Japneet001** [comment]
Pls assign this issue to me

**Comment by Tapabrata-Goswami** [comment]
@Japneet001 you can use any image that fits nicely on this game.

**Comment by Japneet001** [comment]
Ohk

**Comment by souvikpramanikgit** [comment]
I will do it can you assign me. I did it you can check and assign me in this issue.


![image](https://github.com/user-attachments/assets/38b5709a-4f1b-4b78-b34f-e70da96d383e)

**Comment by souvikpramanikgit** [comment]
Also i add some styling 

![image](https://github.com/user-attachments/assets/f27aa2ea-3dc7-4ea0-839f-8f57b0220b5e)

**Comment by souvikpramanikgit** [comment]
If you assign me i will do as soon as possible
