### ISSUE TITLE
📃: Habit Tracker

### ISSUE THREAD

**Issue by viv2005ek** [iamrahulmahato/master-web-development#2332]
🔴 Title :Habit Tracker
🔴 Tech stack : Html,css,js
🔴 Objective : Track daily habits and visualize progress over time.
🔴 Summary : Set daily goals for habits,Calendar view to mark completion and track streaks, Weekly/monthly progress charts using a library like Chart.js.
📸 Screenshots
N/A
***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Vivek Kumar Garg
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
@viv2005ek We can not add this since we already have this project.
