### ISSUE TITLE
📃:Guess_The_Country 

### ISSUE THREAD

**Issue by from13** [iamrahulmahato/master-web-development#2334]
🔴 Title :Guess_The_Country
🔴 Tech stack :
🔴 Objective :
🔴 Summary :  Guess the Country Game
Purpose:
The "Guess the Country" game is an interactive web application that challenges players to guess a country based on a series of hints provided. As the player guesses, they can reveal additional hints to help them arrive at the correct answer. The game provides immediate feedback on whether the guess is correct or incorrect.

Components:
HTML Structure (index.html):

A web page containing the basic structure with a title, hint sections, input field for the user's guess, and buttons for submitting the guess and revealing hints.

CSS Styling (styles.css):

Styling rules to enhance the visual appeal of the game, making it user-friendly and aesthetically pleasing. It includes styles for the container, buttons, text input, and hint display.

JavaScript Logic (script.js):

The logic for the game, including functions to check the user's guess, reveal additional hints, and display the result. It dynamically updates the web page based on user interactions.

Features:
Hints: The game provides a series of hints to help the player guess the country. Hints are revealed one at a time.

User Input: Players can enter their guess into an input field.

Feedback: The game provides immediate feedback, indicating whether the guess is correct or incorrect.

Interactivity: Players can reveal additional hints if they are stuck.

How It Works:
The player starts with the first hint displayed.

They enter their guess into the input field and submit it.

If the guess is incorrect, the game allows the player to reveal the next hint.

The process repeats until the player guesses correctly or all hints are revealed.

This simple yet engaging game can be expanded with more countries, additional hints, and improved user interactions. It's a fun way to test and expand geographical knowledge! 🌍✨

Feel free to implement the code provided earlier and enjoy playing the game! If you have any other questions or need further assistance, just let me know! 😊✨

 
📸 Screenshots

N/A
***********************************************************************

✅ Details to Include When Taking the Issue:
Name :from13
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):GSSOC-Contributor

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
@from13 We can not add this since we already have this project.
