### ISSUE TITLE
add some more project

### ISSUE THREAD

**Issue by adityalaxkar123** [iamrahulmahato/master-web-development#234]
#i want to add the github profile search engine to find the github profile and see their repos,following and follower

**Comment by adityalaxkar123** [comment]
me a gssoc contributor can you assign it to me

**Comment by Tapabrata-Goswami** [comment]
@adityalaxkar123 you can start work on it

**Comment by adityalaxkar123** [comment]
yes but it is lengthy can you assign me level-2 for this

**Comment by adityalaxkar123** [comment]
![Screenshot (964)](https://github.com/user-attachments/assets/b6500805-1d4b-4e23-9f3f-19900b57b5c3)
this is sample

**Comment by Tapabrata-Goswami** [comment]
@adityalaxkar123 ok cool

**Comment by adityalaxkar123** [comment]
@Tapabrata-Goswami see my pull request

**Comment by adityalaxkar123** [comment]
#247
