### ISSUE TITLE
Add New Project - Mindset Matcher: Number Quest

### ISSUE THREAD

**Issue by Japneet001** [iamrahulmahato/master-web-development#236]
**Mindset Matcher: Number Quest** is a classic guessing game where the player tries to guess a randomly generated number between 1 and 100. The game provides feedback on each guess and keeps track of the player's score and high score. The objective is to guess the correct number with the fewest attempts possible to achieve the highest score.

**Comment by Tapabrata-Goswami** [comment]
@Japneet001 check https://master-web-development.netlify.app/projects/number%20guessing/

**Comment by Japneet001** [comment]
Ohk
