### ISSUE TITLE
Add a weather showing project

### ISSUE THREAD

**Issue by iamrahulmahato** [iamrahulmahato/master-web-development#24]

**Comment by Aniumbott** [comment]
I've already built a weather-showing chrome extension check out [here.](https://github.com/Aniumbott/BySun)
I used WeatherBit API, which works best for me even with a free subscription.
I would be happy to work on this. 🙌

**Comment by dushyantkanav** [comment]
assign me this issue

**Comment by Codewithmeowmeow** [comment]
Kindly assign me this issue. I would like to work on it.

**Comment by Pujitha254** [comment]
Hey Rahul!! just checked your project its pretty good .I like the css part in your project. And we can improve it by adding features like weather and i wanted to work upon it if it is ok for you.So could you please assign this to me.

**Comment by himanchal08** [comment]
Could you please assign this issue to me? I believe I can provide a solution

**Comment by devarsheecodess** [comment]
Please assign this issue to me with gssoc-extd label. i can do this for you as i have already worked on a weather app project.
