### ISSUE TITLE
Add New Project - Rolling Triumph

### ISSUE THREAD

**Issue by Japneet001** [iamrahulmahato/master-web-development#241]
**Rolling Triumph** is a web-based game built with HTML, CSS, and JavaScript. It simulates a competitive dice game where players roll dice to accumulate points strategically. The goal is to be the first to reach a specified score threshold and achieve victory.

**Comment by Tapabrata-Goswami** [comment]
@Japneet001 you can start to work on it.

**Comment by Japneet001** [comment]
yes but it is lengthy can you assign me level-2 for this

**Comment by Japneet001** [comment]
This is the Sample
![image](https://github.com/user-attachments/assets/e301e169-ef7d-4f85-a01f-228ccf2ade5d)
![image](https://github.com/user-attachments/assets/0da1d924-7bb7-49d1-b438-e30001dabe09)
