### ISSUE TITLE
Adding Weather App and Movie Recommending App

### ISSUE THREAD

**Issue by Archisman141** [iamrahulmahato/master-web-development#249]
Adding weather app would be a great to detect the present weather situations and movie recommending app would be very helpful especially help us to get top rated movies and it's reviews.

I want to do this work. Please add gssoc label and assign this to me under hackoctoberfest'24.

**Comment by iamrahulmahato** [comment]
work on Movie Recommending App Someone is already working on weather, and when you make an issue, mention the technology stack.

**Comment by Niraj1608** [comment]
@iamrahulmahato can you assign me this issue
