### ISSUE TITLE
the word per minute calculator has no ui 

### ISSUE THREAD

**Issue by HS202022** [iamrahulmahato/master-web-development#256]
![image](https://github.com/user-attachments/assets/19d28b98-2e98-4a12-b289-45238d69a55e)

I can do the ui better

**Comment by HS202022** [comment]
also it doesnt work i can make it working

**Comment by HS202022** [comment]
![Screenshot 2024-10-03 163137](https://github.com/user-attachments/assets/add9917f-2270-43f1-b485-a4817bd3e37f)
![image](https://github.com/user-attachments/assets/6c8d959a-fe58-40f7-990b-498589f8001c)
i made it

**Comment by iamrahulmahato** [comment]
someone already working on it
