### ISSUE TITLE
proposing a more beautiful ui/ux for tic tac toe game

### ISSUE THREAD

**Issue by ROHAN7051** [iamrahulmahato/master-web-development#267]
i would really like to work on this issue

**Comment by iamrahulmahato** [comment]
Can you provide a sample UI or image for it?

**Comment by ROHAN7051** [comment]
Sure

**Comment by ROHAN7051** [comment]
link :https://piggame-rohan7051.netlify.app/ 
![Screenshot (20)](https://github.com/user-attachments/assets/09ebb090-253d-4e45-bab5-9196ed03ad97)
 here is an sample ui that i build for an game i can create the same for your app also
![Screenshot 2024-10-03 211325](https://github.com/user-attachments/assets/fb0ba101-eb88-4504-bf4e-ef1c1bfec628)
