### ISSUE TITLE
Improving UI on home page

### ISSUE THREAD

**Issue by Bhum-ika** [iamrahulmahato/master-web-development#276]
The hover effect can be improved on various listed projects on the UI so that user can notice better the difference when hovering a project.
I can add shadow or scale it (whichever makes it more attractive).

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.

**Comment by Bhum-ika** [comment]
Okay
