### ISSUE TITLE
A Tribute page containing mostly html

### ISSUE THREAD

**Issue by ramana2074** [iamrahulmahato/master-web-development#286]
A tribute page with inline stylings and internal stylings. Best for everyone to start working on web development.

**Comment by iamrahulmahato** [comment]
Can you share the UI and tech stack?

**Comment by ramana2074** [comment]
https://wool-flax-journey.glitch.me
you can refer this link. This is just a basic tribute to help beginners.
I can align the paragraphs to make it look good
