### ISSUE TITLE
No navbar and footer

### ISSUE THREAD

**Issue by shaina123786** [iamrahulmahato/master-web-development#291]
I would like to add navbar and footer in your website then your website more attractive and more user-friendly . So plz assign to me.

**Comment by shaina123786** [comment]
I would like to add navbar and footer in your website then your website more attractive and more user-friendly . So plz assign to me.

**Comment by Abhi0049k** [comment]
@iamrahulmahato I would like to work on this issue

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
