### ISSUE TITLE
ADD Style to Typing Test Project 

### ISSUE THREAD

**Issue by rajatsinghal02** [iamrahulmahato/master-web-development#313]
I want to add styling to typing test project.

![Screenshot_20241004_101521.jpg](https://github.com/user-attachments/assets/34e3f11f-d83f-482d-bc60-5747da20efed)

@iamrahulmahato Please assign this issue to me..

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
