### ISSUE TITLE
I would like to ADD Social media ICONS 

### ISSUE THREAD

**Issue by pankajsaini1** [iamrahulmahato/master-web-development#320]
I would like to ADD Social media ICONS in the website

**Comment by Kavish-Paraswar** [comment]
Given my strong background in HTML, CSS, and JavaScript, I would like to request that this task be assigned to me. I intend to mark this under the GSoC extended projects

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
