### ISSUE TITLE
i want to add footer 

### ISSUE THREAD

**Issue by shakti1590** [iamrahulmahato/master-web-development#33]
assign me this issue

**Comment by shakti1590** [comment]
Tap on below link-
https://drive.google.com/file/d/15vWNDdg60nPKzUZg_4wZsqeaNgJB9qm1/view?usp=sharing

**Comment by shakti1590** [comment]
ok assign me a specific project where the footer is needed.

**Comment by shakti1590** [comment]
i am ready to accept! assign me.

**Comment by shakti1590** [comment]
ok thanks i will add as soon as possible

**Comment by shakti1590** [comment]
check out i add footer 
i edit both HTML & CSS file so check out

**Comment by shakti1590** [comment]
ok sure

**Comment by shakti1590** [comment]
yup its done check out

**Comment by shakti1590** [comment]
done

**Comment by dushyantkanav** [comment]
assign me this issue
