### ISSUE TITLE
UI Improvements and JavaScript Adjustments for Webpage

### ISSUE THREAD

**Issue by Kavish-Paraswar** [iamrahulmahato/master-web-development#345]
I will improve the UI by adding a background image, updating the font, and enhancing the alignment of elements on the webpage.
![image](https://github.com/user-attachments/assets/24eeca4b-37bc-48e2-978b-2aa1819a6deb)

I will check the JavaScript code to replace "null" with the found username to ensure proper functionality.
![image](https://github.com/user-attachments/assets/a1e74c09-e401-4a24-ba1a-1266cd1e0c3c)

The background image is currently not fitting correctly; I will adjust it to ensure it fits the screen appropriately.
![image](https://github.com/user-attachments/assets/1661e32d-d79d-4e4e-8a30-d55c68e10a60)

Given my strong background in HTML, CSS, and JavaScript, I would like to request that this task be assigned to me. I intend to mark this under the GSoC extended projects and level 2 atleast .

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
