### ISSUE TITLE
Improvement: Enhance the UI of the Typing Speed Test Game

### ISSUE THREAD

**Issue by Rohit-Gupta-126** [iamrahulmahato/master-web-development#346]
UI seems to have no CSS, just baisc html. I want to make it look like a proper typing speed test game by enhancing the UI using CSS.
![image](https://github.com/user-attachments/assets/7a45629e-453f-4b43-9cca-f79f356a499d)

**Comment by Rohit-Gupta-126** [comment]
@iamrahulmahato please assign this issue to me and kindly label it as  good first issue and gssoc.

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
