### ISSUE TITLE
Improvment: To improve the UI and 'Calculate' button hover effect of the BMI Calculator

### ISSUE THREAD

**Issue by Rohit-Gupta-126** [iamrahulmahato/master-web-development#349]
Hover effect on the Calculate button is bad.
Background picture loads too slow and doesn't fit properly to the website. It has a very basic look. The Guide color is not suited for the background picture. It looks odd there.

@iamrahulmahato please assign this issue to me labeled under good first issue and gssoc.

![image](https://github.com/user-attachments/assets/db866f14-8c1e-427d-897d-d2011a8f10c8)

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
