### ISSUE TITLE
Add text to speech converter project

### ISSUE THREAD

**Issue by nishtha-902** [iamrahulmahato/master-web-development#351]
@iamrahulmahato please assign me this issue I will add text to speech converter project in the list.

**Comment by komalnalage** [comment]
Hi @iamrahulmahato .I would like to work on this issue. Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags?

Thanks so much!

**Comment by Niraj1608** [comment]
@iamrahulmahato assign me this issue i already work on it this project :)
will raise a pr within a day
