### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by souvikpramanikgit** [iamrahulmahato/master-web-development#376]
In the website, there is many issue like

1. When i click on an project , it can't open a new page(i want to add the target=blank,which can open in other tab)

2. Here some bugs are running like unreasonable text are showing here

![image](https://github.com/user-attachments/assets/95294a4c-20c3-405f-99ed-9dbbde934270)

**Comment by anmol2710** [comment]
Generate gradient page issue already mentioned and solved in issue #370

**Comment by souvikpramanikgit** [comment]
Ok i will remove it.

**Comment by souvikpramanikgit** [comment]
I update the issue

**Comment by souvikpramanikgit** [comment]
Another (2nd) issue is already solved.
