### ISSUE TITLE
Feat: Every app should be opened in another tab

### ISSUE THREAD

**Issue by SatyamThakur0** [iamrahulmahato/master-web-development#381]
Feature - Every app in homepage should be opened in **another tab** so user can **easily navigate** and open another game or app without **losing** opened game or app.

I want you to assign me this issue so i can fix it.

And also please add **hectoberfest** tag also.

**Comment by souvikpramanikgit** [comment]
It is already issued 

https://github.com/iamrahulmahato/master-web-development/issues/376

**Comment by iamrahulmahato** [comment]
Already Assigned

**Comment by SatyamThakur0** [comment]
Ok @iamrahulmahato
