### ISSUE TITLE
Add Chess game

### ISSUE THREAD

**Issue by souvikpramanikgit** [iamrahulmahato/master-web-development#387]
I want to add chess game, which can be look like this

![image](https://github.com/user-attachments/assets/8c42494f-7731-4d99-ae2c-c32a4ca55fa7)

Technoogy used ->

1. Html
2. Css
3. Javascript

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
