### ISSUE TITLE
addition of the footer in the website

### ISSUE THREAD

**Issue by Vishal1078** [iamrahulmahato/master-web-development#394]
So there is no **footer** for this project as you can see below in the attachment and the addition of the footer in the website will make it more attractive from user end view 
![Screenshot_11](https://github.com/user-attachments/assets/40329a5e-97b8-48dc-9038-d82b6056c3ca)

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
