### ISSUE TITLE
add game: Whac-A-Mole

### ISSUE THREAD

**Issue by Ishika-Gupta06** [iamrahulmahato/master-web-development#402]
I want to add this another game .Please assign me this task under GSsoc-ext, hacktoberfest and level-1,2,3 .
I've worked on it and its almost done. @iamrahulmahato 
![Screenshot 2024-10-05 143749](https://github.com/user-attachments/assets/7b7e4bd8-102a-439a-b9e2-1a02693b92a6)

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
