### ISSUE TITLE
Add Currency Converter app

### ISSUE THREAD

**Issue by amanver45** [iamrahulmahato/master-web-development#406]
convert currency of different countries

![Screenshot 2024-10-05 153713](https://github.com/user-attachments/assets/ba5d2104-d534-4a6a-9960-07972f3909a9)

**Comment by Seema-Anjum** [comment]
I want to work on it. Please assign it to me under GSsoc-ext, hacktoberfest, and add level-1,2,3

**Comment by Pushpa472** [comment]
@iamrahulmahato Enhance the UI design of the currency converter to improve its visual appeal and user experience. This includes updating the layout, color scheme, and overall aesthetics to create a more modern and intuitive interface.
