### ISSUE TITLE
Buggy Contact Us Button

### ISSUE THREAD

**Issue by somil0701** [iamrahulmahato/master-web-development#431]
The Contact Us button looks quite buggy. On light mode the text is not visible where as on the dark mode a thick border appears which is not aesthetically pleasing.
![image](https://github.com/user-attachments/assets/c529e62b-5bc3-4b4e-9a78-3da33afd5505)
![image](https://github.com/user-attachments/assets/3090532f-88d1-4b9d-b91a-073424bb7649)

Please assign this issue to me, I'll handle this level-1 issue.

**Comment by Tapabrata-Goswami** [comment]
@somil0701 what is the benefit of this button?

**Comment by somil0701** [comment]
> @somil0701 what is the benefit of this button?

The button is already implemented, I am just stating that it glitches on Light Mode.
Text Color seems inappropriate for the light theme

**Comment by Tapabrata-Goswami** [comment]
@somil0701 are you sure ?
![image](https://github.com/user-attachments/assets/8442aec8-d7b8-43d8-ac61-0e8cdafed078)

**Comment by somil0701** [comment]
> @somil0701 are you sure ?
> ![image](https://github.com/user-attachments/assets/8442aec8-d7b8-43d8-ac61-0e8cdafed078)
> 

I was talking about the contact us button which is not visible in the ss you attached above. Please refer to the ss I sent above.

**Comment by Tapabrata-Goswami** [comment]
@somil0701 can you share your domain where you check we have a contact us button? because we don't have a Contact Us button on our page.

**Comment by iamrahulmahato** [comment]
Contact us. The button is not on the website, so I am closing this issue.
