### ISSUE TITLE
ADD PASSWORD MANAGER

### ISSUE THREAD

**Issue by amanver45** [iamrahulmahato/master-web-development#433]
password manager  using html css js

**Comment by amanver45** [comment]
pls label as level 2 @Tapabrata-Goswami @iamrahulmahato

**Comment by amanver45** [comment]
Here’s a description of your Password Manager Project using HTML, CSS, and Java and how it can be categorized as Level 2 based on complexity

The Password Manager is a secure, user-friendly application developed using HTML, CSS, and Java. It enables users to store, manage, and retrieve their passwords safely for multiple accounts. This project focuses on providing a simple interface for users while ensuring that passwords are securely stored and encrypted using Java-based algorithms.

Technology Stack:

1. Frontend:

HTML: Used for creating the structure of the user interface. It contains forms for user registration, login, and password management. The layout includes fields for usernames, passwords, and account details.

CSS: Used for styling the application’s user interface. CSS provides a responsive and visually appealing layout with various styles for buttons, forms, and alerts.

JavaScript: Provides frontend validation (e.g., password strength checking, form validation) and interactive features such as showing/hiding passwords.


Change the label to level 1 to level 2 @Tapabrata-Goswami @iamrahulmahato

**Comment by Bhavya445** [comment]
could u pls assign this issue to me

**Comment by bhaviya18** [comment]
Hello sir I would like to solve this issue, can you kindly assign this task to me?
