### ISSUE TITLE
Add Mini Calender

### ISSUE THREAD

**Issue by amanver45** [iamrahulmahato/master-web-development#435]

**Comment by Tapabrata-Goswami** [comment]
@amanver45 elaborate your idea with us.

**Comment by amanver45** [comment]
A "mini calendar" typically refers to a small, compact version of a calendar that displays a quick overview of dates, usually for a single month. It is commonly used in web applications, productivity tools, or desktop widgets to allow users to quickly view dates, select a day, or navigate between months. Here are some common functions of a mini calendar:

Date Display: Shows the current month with all days listed in a grid.
Day Highlighting: The current day is often highlighted, making it easier to see today’s date.
Navigation: Arrows or buttons allow users to move to the previous or next month.
Date Selection: Users can click on a date to select it, which is useful for picking dates in forms, scheduling apps, or booking systems.
Event Indicators: In some cases, days that have events or tasks may be marked with dots or other icons.



to create a mini calendar using HTML, CSS, and JavaScript:

HTML: Structure the calendar with a header for month/year navigation and a grid for days of the week and individual days.
CSS: Style the calendar for layout, colors, and hover effects to enhance the user interface and ensure it's visually appealing.
JavaScript: Add interactivity by handling month navigation, dynamically calculating the number of days in each month, and rendering the days accordingly.
This combination allows for a functional and interactive mini calendar.

**Comment by amanver45** [comment]
@Tapabrata-Goswami @iamrahulmahato  pls assign me
