### ISSUE TITLE
Add email validator

### ISSUE THREAD

**Issue by amanver45** [iamrahulmahato/master-web-development#436]

**Comment by Koushik-Biswas** [comment]
Hi, I'd like to work on this issue. Please assign it to me.

**Comment by Tapabrata-Goswami** [comment]
@amanver45 elaborate your idea with us

**Comment by amanver45** [comment]
@Tapabrata-Goswami @iamrahulmahato 
An email validator is a tool or service used to verify whether an email address is valid and deliverable. It performs various checks to ensure the email address meets certain criteria and can successfully receive emails. Here's what an email validator typically does:

Syntax Check: Ensures that the email address follows the correct format (e.g., username@domain.com).
Domain Check: Verifies if the domain (the part after the @ symbol) exists and is configured to receive emails (e.g., checking DNS records).
MX Record Check: Confirms that the domain has mail exchange (MX) records set up, indicating it can accept emails.
Disposable Email Detection: Identifies if the email is from a temporary or disposable email service.
Role-based Email Detection: Checks if the email address belongs to a role (e.g., admin@, support@), which are typically not used by individuals.
SMTP Verification: Some validators check directly with the email server to see if the email account exists and can receive emails without actually sending one.
The goal of an email validator is to improve the quality of an email list, reduce bounce rates, and prevent issues with undeliverable or invalid emails
![image](https://github.com/user-attachments/assets/8a83b516-a83d-48ef-aab9-fe20cc1f726e)

**Comment by amanver45** [comment]
@Tapabrata-Goswami @iamrahulmahato  pls assign me

**Comment by amanver45** [comment]
@iamrahulmahato this is level 2 issue
