### ISSUE TITLE
Add Instagram Landing Page with HTML and CSS for Beginners!

### ISSUE THREAD

**Issue by Shekhar-Raj** [iamrahulmahato/master-web-development#451]
<h2>Objective:</h2>

<h3>Created an Instagram landing page using only HTML and CSS to help beginners understand fundamental CSS properties. This page will introduce various styling techniques, such as hover effects, transforms, scaling, and more, providing hands-on experience with these essential concepts.</h3>

<h3>Please assign the issue so that i can contribute!</h3>

https://github.com/user-attachments/assets/aa5a0c4e-3247-40f6-b6ed-4e06c5a8a558

<h3>Image</h3>

![image](https://github.com/user-attachments/assets/8055b400-aee2-458c-89c5-ebf576aa335a)

**Comment by Tapabrata-Goswami** [comment]
@Shekhar-Raj when pushing this project on our repo then mention this issue number #451
