### ISSUE TITLE
Add a chatbot🤖

### ISSUE THREAD

**Issue by saurabhsagar99** [iamrahulmahato/master-web-development#460]
A chatbot 🤖  will serve as a good project for the intermediate level web developer. I will create a working chatbot using html,css,js. In this chatbot user can ask any questions and will  receive instant responses also this chatbot will be responsive so you can use it from any device.So please assign this task to me🙂

**Comment by Tapabrata-Goswami** [comment]
@saurabhsagar99 in Home page ?

**Comment by saurabhsagar99** [comment]
![Screenshot_20241006-021645_Chrome](https://github.com/user-attachments/assets/85e059b3-c147-47c9-ac00-9422cfa627be)

What I mean is I will add the chatbot project like rest of the other projects as shown in the image.As this chatbot will respond to user it keeps them engaged
