### ISSUE TITLE
Want to add Digital Clock

### ISSUE THREAD

**Issue by iAmDiksha** [iamrahulmahato/master-web-development#463]
I want to add a Digital Clock.

<img width="321" alt="image" src="https://github.com/user-attachments/assets/c2fac6e9-dad8-4fdf-9f51-e898305270d1">

Tech Stack -
- HTML
- CSS
- JavaScript

**Comment by iamrahulmahato** [comment]
The project already exist, Do not be demotivated and raise a new issue.
