### ISSUE TITLE
[UI Enhancement] Improve Calculator Layout, Responsiveness, and Aesthetics

### ISSUE THREAD

**Issue by pranavmugatkar** [iamrahulmahato/master-web-development#467]
The current calculator UI on [this project](https://master-web-development.netlify.app/projects/calculator/) can be enhanced to provide a more modern and intuitive experience. Here are a few key areas of improvement:

Button Layout and Spacing:

The buttons feel too closely packed, especially on smaller devices. Adding proper padding and adjusting button size for different screen sizes will help make the calculator more user-friendly and accessible.
Color Scheme:

The color scheme can be refreshed to follow a more consistent, visually appealing theme. Consider using soft background colors and distinct button colors to improve readability and interaction.
Responsive Design:

The calculator layout could be improved for smaller screens and mobile devices. Right now, it doesn’t adapt seamlessly, which affects usability. Ensuring that the buttons, display screen, and other elements resize proportionately will provide a better experience across all devices.
Button Hover and Click Effects:

Adding smooth hover effects and animations for button clicks can make the calculator feel more dynamic. Subtle transitions can give users feedback when interacting with the buttons.
Font and Display Screen:

The font for the numbers and operators could be updated for better readability. Additionally, the display screen could be redesigned to accommodate larger numbers more efficiently.
Suggested Enhancements:
Add margin and padding to the buttons.
Implement media queries to improve the layout on mobile devices.
Redesign the color scheme for better aesthetics.
Include smooth button hover and click animations.
Adjust the font and display design for improved clarity and readability.

please assign me this under hacktoberfest and gssoc label

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
