### ISSUE TITLE
Implementing Chess game

### ISSUE THREAD

**Issue by Sourabh782** [iamrahulmahato/master-web-development#478]
Chess is a popular thingking game, pushing your thinking capablities.

I wanted to work on this.

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.

**Comment by Sourabh782** [comment]
@iamrahulmahato can you tell me issue no.? actually i checked all issues but didnt find chess implementation
