### ISSUE TITLE
Adding Rock Paper Scissors Game

### ISSUE THREAD

**Issue by t1nt1n-s0lv3r** [iamrahulmahato/master-web-development#48]
Rock Paper Scissors is a very famous game and is played very often by young people

Can you please assign me this task as this is my first time in Open Source Contributions 
Please assign it under gssoc'24 and hacktoberfest @iamrahulmahato

**Comment by PREM-A261** [comment]
@PREM-A261 Can I Work on it 
I promise  I will never disappoint you.

**Comment by amanver45** [comment]
hey @iamrahulmahato , I'd like to contribute in this. Can you assigned me this
