### ISSUE TITLE
Add Bubble Hit Game to Main Website

### ISSUE THREAD

**Issue by prachi-kurmi** [iamrahulmahato/master-web-development#481]
**Description**
I’ve added the Bubble Hit Game, but it hasn’t been integrated into the main website yet. The game is fully functional and should be featured on main website.

**Proposed Solution:** 
I want to integrate the game into the main website and ensure it is responsive across all devices.

Thank you!

**Comment by iamrahulmahato** [comment]
Make a separate project and include it in the project section.

**Comment by prachi-kurmi** [comment]
Do I need to make the project again, or is the project already present, and I just need to make the entry?
