### ISSUE TITLE
Inconsistent Layout and Distracting Color Scheme in Calculator UI

### ISSUE THREAD

**Issue by Lonwwolf14** [iamrahulmahato/master-web-development#483]
🔴 Issue Title: Inconsistent Layout and Distracting Color Scheme in Calculator UI

🔴 Objective: Enhance the layout and color scheme to improve the usability and visual appeal of the calculator interface.

🔴 Summary:
The current layout and color choices in the calculator are not user-friendly and can make it challenging to use. The arrangement of buttons lacks intuitive placement, and the bright blue and red colors are overly distracting. A more conventional layout and a subtler color palette would greatly enhance the overall user experience.

📸 Screenshots
![image](https://github.com/user-attachments/assets/42e29a33-a668-49bd-a951-7b29d1c57785)

✅ Details to Include When Taking the Issue:
Full Name: Lonwwolf14
Participant Role: GSSOC

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
