### ISSUE TITLE
[NEW BEGINNER PROJECT]: Random Dad Jokes Generator Using Fetch API

### ISSUE THREAD

**Issue by Harshitha-Annam** [iamrahulmahato/master-web-development#489]
🔴 Title : Dad Jokes Generator
🔴 Tech stack : HTML, CSS, JS
🔴 Objective : a more beginner friendly project to get started with APIs
🔴 Summary : The project Uses Fetch API to fetch random Dad jokes from icanhazdadjokes.com. This project introduces APIs in a more beginner friendly way than most. It is also a great project to understand how Fetch API Works.
📸 Screenshots
![new1](https://github.com/user-attachments/assets/07124933-a103-4dae-9879-dfc191353c6a)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Harshitha Annam | Contributor | GSSOC Extd | Hacktoberfest

Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Harshitha-Annam** [comment]
Thank you. I will start working on this.

**Comment by Magent4** [comment]
hi, can i help?
