### ISSUE TITLE
📃: [NEW GAME]: Rock Paper Scissors Game

### ISSUE THREAD

**Issue by ishita-1305** [iamrahulmahato/master-web-development#491]
I want to add a rock paper scissors game using tech stacks html, css and javascript.
![Screenshot 2024-10-06 113010](https://github.com/user-attachments/assets/114f7ee6-5493-441e-b80d-4f87c641f947) I would like to request the assignment of GSSOC-EXT tag and LEVEL3 for this project.

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
