### ISSUE TITLE
Change complete UI and Add feature in exsisting project - gradient colour generator

### ISSUE THREAD

**Issue by ananyag309** [iamrahulmahato/master-web-development#50]
As you can see the existing project ui is not that worthy I am willing to redesign it along with adding some features please assign this issue to me under gssoc ext and hactoberfest

![ui](https://github.com/user-attachments/assets/50998bf4-1a77-4566-b031-b89ade992974)

**Comment by iamrahulmahato** [comment]
@ananyag309 Can you mention the particular project that you want to redesign?

**Comment by ananyag309** [comment]
this https://github.com/iamrahulmahato/master-web-development/tree/main/projects/GenerateGradientColor
