### ISSUE TITLE
📃: Add Maze Game

### ISSUE THREAD

**Issue by amanver45** [iamrahulmahato/master-web-development#501]
🔴 Title : Maze Game
🔴 Tech stack : HTML, CSS, JavaScript
🔴 Objective :The objective of the Maze Game is to navigate through a complex maze from a starting point to a designated endpoint while avoiding obstacles and traps.
🔴 Summary :The Maze Game is an interactive web-based game that allows players to explore a visually appealing maze created with HTML for structure, CSS for styling, and JavaScript for game logic. Players can use keyboard controls to move through the maze, with real-time collision detection to prevent them from running into walls or obstacles. The game features various difficulty levels, random maze generation, and a timer to challenge players. It serves as an engaging way to improve problem-solving skills and hand-eye coordination while providing an entertaining gaming experience

**Comment by 13Sharad** [comment]
i want to work in the issue
