### ISSUE TITLE
📃: Add Mini Calender

### ISSUE THREAD

**Issue by amanver45** [iamrahulmahato/master-web-development#503]
🔴 Title :Add Mini Calender
🔴 Tech stack :HTML: Structure the calendar with a header for month/year navigation and a grid for days of the week and individual days.
CSS: Style the calendar for layout, colors, and hover effects to enhance the user interface and ensure it's visually appealing.
JavaScript: Add interactivity by handling month navigation, dynamically calculating the number of days in each month, and rendering the days accordingly.
This combination allows for a functional and interactive mini calendar.
🔴 Objective : A  "mini calendar" typically refers to a small, compact version of a calendar that displays a quick overview of dates, usually for a single month. It is commonly used in web applications, productivity tools, or desktop widgets to allow users to quickly view dates, select a day, or navigate between months. Here are some common functions of a mini calendar
🔴 Summary :Date Display: Shows the current month with all days listed in a grid.
Day Highlighting: The current day is often highlighted, making it easier to see today’s date.
Navigation: Arrows or buttons allow users to move to the previous or next month.
Date Selection: Users can click on a date to select it, which is useful for picking dates in forms, scheduling apps, or booking systems.

**Comment by harish08102004** [comment]
Hey @amanver45 I can work on this.
Please add labels (gssoc-extd , level , hacktoberfest) and assign this to me

**Comment by harshitkumargupta** [comment]
Hi @iamrahulmahato ,
please assign me this..

**Comment by amanver45** [comment]
@iamrahulmahato  duplicate nhi h wo issue bhi maine raise kiya tha lekin bad m close kar diya tha
