### ISSUE TITLE
🧑‍💻 : Add Github logo before "view source code" button

### ISSUE THREAD

**Issue by Hamza1821** [iamrahulmahato/master-web-development#507]
:red_circle: **Add Github logo before "view source code" button** :
:red_circle: **Aim is to improve interactiveness of  SOURCE CODE button** :
:red_circle: **Changes** :  **Adding a Github logo  before source code button**

### Screenshots 📷
![Screenshot 2024-10-06 at 12-49-29 Master web development](https://github.com/user-attachments/assets/45f540de-dce2-454b-8c3c-17539432a31c)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Hamza Mubin
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC-Extd, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
