### ISSUE TITLE
🧑‍💻 : Can make a footer that can you your contactable modes and a copyright statement

### ISSUE THREAD

**Issue by Vijitverm1234** [iamrahulmahato/master-web-development#509]
:red_circle: **Title** : Modification 
:red_circle: **Enhancement Aim** : To make the UI , user friendly 
:red_circle: **Changes** : Making footer , Adding animations and hovering effect

i can add te footer which the owner can add its credentials , moreover scroll down animations and user friendly hover effect
**********************************************************************
✅ Details to Include When Taking the Issue:
Name : some modifications
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
