### ISSUE TITLE
🧑‍💻 :  Create a home page and a navbar

### ISSUE THREAD

**Issue by Priyanshi231** [iamrahulmahato/master-web-development#517]
:red_circle: **Title** : Create a home page and a navbar
:red_circle: **Enhancement Aim** : Add the home page to make it more attractive 
:red_circle: **Changes** : add home page and a navbar

### Screenshots 📷N/A

**********************************************************************
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
Hacktoberfest, GSSOC-exd

I would like to create a well-designed and responsive Home/Landing Page for the website. This page will provide a comprehensive overview of the site.

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
