### ISSUE TITLE
📃: Dot Box Game

### ISSUE THREAD

**Issue by souvikpramanikgit** [iamrahulmahato/master-web-development#537]
🔴 Title : Dot Box Game
🔴 Tech stack : Html,Css,Javascript

📸 Screenshots

![image](https://github.com/user-attachments/assets/2cfb10d7-c75c-4f1f-a536-551d693a2c11)

***********************************************************************

✅ Details to Include When Taking the Issue:

Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Varsha567** [comment]
hii @iamrahulmahato could you please assign this to me?
