### ISSUE TITLE
Add Survey Form web page 

### ISSUE THREAD

**Issue by srajangupta144** [iamrahulmahato/master-web-development#54]
I will add a survey form web page for the other participants to add their thoughts and ideas for this website and make it responsive

**Comment by Swadeeppatil** [comment]
i would like to add survey from in webpeg
@iamrahulmahato  plz assign me this task under hacktomberfest2024

**Comment by Ishajain0** [comment]
@iamrahulmahato please assign this task to me I would like to work on it...

**Comment by AyutheCoder** [comment]
I would like to add survey form in webpage .
@iamrahulmahato ,please assign this tak to me.
