### ISSUE TITLE
📃: Tower of Hanoi

### ISSUE THREAD

**Issue by TBorundia** [iamrahulmahato/master-web-development#542]
🔴 Title : Tower of Hanoi
🔴 Tech stack : Html, Css, Js

✅ Details to Include When Taking the Issue:
Name : Tina Borundia
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
 GSSOC, Hacktoberfest

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by sarthakjalan05** [comment]
@iamrahulmahato I would love to work on this under the hacktoberfest tag.Do assign me!!
