### ISSUE TITLE
📃:  Guess random shapes

### ISSUE THREAD

**Issue by TBorundia** [iamrahulmahato/master-web-development#543]
🔴 Title : Guess random shapes
🔴 Tech stack : Html, Css, Js

✅ Details to Include When Taking the Issue:
Name : Tina Borundia
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by 05kaavya** [comment]
I kindly request you to assign this issue to me.
