### ISSUE TITLE
Create Different Sections for Categorizing Games Based on Types

### ISSUE THREAD

**Issue by Abbas7120** [iamrahulmahato/master-web-development#549]
All games can't be categorized under the same section as each game has distinct features, objectives, and audiences. To improve user experience and organization, we need to create different sections for various types of games. This will allow users to easily navigate and explore games based on their preferences.

Example :
![image](https://github.com/user-attachments/assets/7586ae47-d26a-412a-a49d-d1e31e75e6f1)

**Comment by Abbas7120** [comment]
Assign me this issue with gssoc-ext hacktoberfest hacktoberfest-accepted labels

**Comment by iamrahulmahato** [comment]
can you share the ui

**Comment by Abbas7120** [comment]
Yes I want this on home page

**Comment by iamrahulmahato** [comment]
Sorry,In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
