### ISSUE TITLE
SIMPLE TO SCIENTIFIC CALCULATOR 

### ISSUE THREAD

**Issue by PREM-A261** [iamrahulmahato/master-web-development#56]
As Title says we need to make our calculator more scientific
and functional.
For eg. sin, cos, tan, exponential (^), Pi ,root, etc..

**Comment by PREM-A261** [comment]
**@PREM-A261** Please Assist me this Problem

**Comment by iamrahulmahato** [comment]
@t1nt1n-s0lv3r already working on this issue

**Comment by PREM-A261** [comment]
if He/She will unfortunately fail then please assign me

**Comment by iamrahulmahato** [comment]
@PREM-A261 ok then i will reopen it
