### ISSUE TITLE
🧑‍💻 : Add search functionality

### ISSUE THREAD

**Issue by ShivanshPlays** [iamrahulmahato/master-web-development#564]
:red_circle: **Title** :We can add a search functionality in the landing page 
:red_circle: **Enhancement Aim** : to let users search for games
:red_circle: **Changes** : add searching

### Screenshots 📷
![Screenshot 2024-10-06 175855](https://github.com/user-attachments/assets/e1a4283b-7581-40dc-a2fd-540ba87c8272)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :Shivansh Saxena
Participant Role :GSSOC, Hacktoberfest

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
