### ISSUE TITLE
Classic Dino Game from Google Chrome

### ISSUE THREAD

**Issue by Lonwwolf14** [iamrahulmahato/master-web-development#573]
### Issue: Classic Dino Game from Google Chrome

**Description:**

Replicate the Classic Dino Game from Google Chrome, which appears when there is no internet connection. The game involves:

- A pixelated dinosaur that automatically runs across the screen.
- Obstacles like cacti and birds that appear randomly.
- The dinosaur should be able to jump when the spacebar is pressed.

**Expected Features:**

- Implement smooth running and jumping mechanics using HTML, CSS, and JavaScript.
- Randomly generate obstacles at increasing difficulty.

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
