### ISSUE TITLE
📃: Typing test

### ISSUE THREAD

**Issue by itsmeAYUSH** [iamrahulmahato/master-web-development#576]
🔴 Title: Typing Speed Test Game

🔴 Tech stack: JavaScript, HTML, CSS

🔴 Objective: To create a typing speed test application that allows users to measure and improve their typing speed and accuracy by typing random words or sentences within a set time frame.

🔴 Summary: The Typing Speed Test Game provides users with a randomly generated sequence of words or sentences to type as quickly and accurately as possible. The game will track the user’s words per minute (WPM), accuracy, and errors made during the test. Users can improve their typing skills through practice while receiving real-time feedback on their performance. The app will have a clean, minimal design and real-time results.

📸 Screenshots
![image](https://github.com/user-attachments/assets/0c7f6aa8-7dbd-4a5d-adf5-8f8cbeb57fb4)

***********************************************************************

Name : Ayush Kumar Sagar
Participant Role : GSSOC,  Hacktoberfest 2024

***********************************************************************

Note: I would like to request that this task be assigned to me.

Happy Contributing! 🚀

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
