### ISSUE TITLE
Adding expense tracker

### ISSUE THREAD

**Issue by TanushreeBorase** [iamrahulmahato/master-web-development#58]
I want to add an expense tracker project. Please assign me this issue under GSSoC extended 2024.

**Comment by ErNehaSharma** [comment]
[TanushreeBorase](https://github.com/TanushreeBorase) hello Previously I have created Expense Tracker website as a sample project and I would love to make contribution here. If you want You can assign me this issue under the label of hacktoberfest and gssoc ext.

**Comment by ErNehaSharma** [comment]
hello [iamrahulmahato](https://github.com/iamrahulmahato) Previously we have created Expense Tracker website as a sample project and I would love to make contribution here.
I want to add an expense tracker project. Please assign me this issue under GSSoC extended 2024 and hacktoberfest.
