### ISSUE TITLE
📃: Want to add space invaders game

### ISSUE THREAD

**Issue by 17arindam** [iamrahulmahato/master-web-development#582]
🔴 Title :Alien invaders
🔴 Tech stack :html,css
🔴 Objective :shoot the incoming aliens 
🔴 Summary :
a classic game where we have to shoot the incoming aliens
📸 Screenshots

![image](https://github.com/user-attachments/assets/bda9858d-1874-4608-bada-a979bf3ba997)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Arindam Bera
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC , Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by 17arindam** [comment]
@iamrahulmahato please assign me this issue

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
