### ISSUE TITLE
Add Project Categorization to Home Page

### ISSUE THREAD

**Issue by Lonwwolf14** [iamrahulmahato/master-web-development#583]
### Issue Title: Add Project Categorization to Home Page

**Description:**

Currently, all projects are displayed in a clustered manner on the home page without any categorization, making it difficult for users to browse and navigate through the content effectively. To enhance user experience, we need to implement a categorization feature on the home page.
This feature will improve project organization and help users quickly find the relevant projects under appropriate categories.

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
