### ISSUE TITLE
📃: A creative Ping-Pong Game 

### ISSUE THREAD

**Issue by Manish5043** [iamrahulmahato/master-web-development#594]
🔴 Title :A creative Ping-Pong Game 
🔴 Tech stack :python
🔴 Objective : want to add a ping pong game to the repo
![Screenshot 2024-10-06 213133](https://github.com/user-attachments/assets/4b459e74-c6df-4312-a615-c4b9c3a5ca3a)

🔴 Summary :  A creative game that can be played when you are bored
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Manish5043** [comment]
PLease assign me this issue under Gssoc and hactoberfest label

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.

**Comment by Manish5043** [comment]
No problem
