### ISSUE TITLE
📃: Addition of Rock, Paper , Scissors Game

### ISSUE THREAD

**Issue by pratheekv39** [iamrahulmahato/master-web-development#596]
🔴 Title :Rock Paper Scissors Game
🔴 Tech stack :HTML, CSS, JavaScript
🔴 Objective :Create a simple, interactive Rock Paper Scissors game that allows users to play against the computer in a web browser.
🔴 Summary :Develop a web-based Rock Paper Scissors game where players can choose their move (rock, paper, or scissors) by clicking on buttons or images. The computer will randomly select its move, and the game will determine the winner based on the classic Rock Paper Scissors rules. The game should keep track of the score and display the result of each round.

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : pratheekv39 (V Pratheek)
Participant Role : GSSOC and Hacktoberfest participant

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

@iamrahulmahato  Can you please assign me this issue. I would love to work on it

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
