### ISSUE TITLE
Toggling + Ui design 

### ISSUE THREAD

**Issue by Dipeshdahiya** [iamrahulmahato/master-web-development#60]
I seen that the dark light mode toggle is not supporting transition + the design of the project pages are not that good 
I will improve them and resolve these issues 
If you think their is another better issue i should work on , then please justify it to me 
and assign this issues to me

**Comment by Dipeshdahiya** [comment]
https://remoteflow.vercel.app/
this is my current project in which i used the dark mode toggle and also done the whole designing from scratch

**Comment by himanchal08** [comment]
Could you please assign this issue to me? I believe I can provide a solution. I have a similar project in which i have already added dark mode , So I can help you in this . [Dark_Mode_Demo](https://dark-mode-pro.vercel.app/)

**Comment by iamrahulmahato** [comment]
@Dipeshdahiya there is already a dark mode in website what you want to achieve from this

**Comment by Dipeshdahiya** [comment]
Yes i seen it , I want to do a batter transition effect on toggle which create a good user experience and as well as maintain the coloring of the page , In addition hover effects on the buttons in some of the pages

**Comment by himanchal08** [comment]
look to my toggle button it has the desired transition

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
