### ISSUE TITLE
🐞 : The Grid is kinda messed up

### ISSUE THREAD

**Issue by Lonwwolf14** [iamrahulmahato/master-web-development#600]
## :red_circle: Bug
The grid layout in the game selection screen is misaligned, causing visual inconsistencies and potential usability issues.

## :red_circle: Changes
To address this bug, we should:
1. Review and adjust the CSS grid or flexbox properties for the game selection container.
2. Ensure consistent sizing and spacing for all game tiles.
3. Implement responsive design techniques to maintain proper alignment across different screen sizes.
4. Add overflow handling to prevent content from breaking the layout.
5. Test the layout on various devices and browsers to ensure consistent appearance.

## Screenshots 📷
![image](https://github.com/user-attachments/assets/5d611fa4-1888-47e6-897e-b521be6019f9)

---

## ✅ Details to Include When Taking the Issue:
- **Name**: Lonwwolf14
- **Participant Role**: GSSOC

**Comment by iamrahulmahato** [comment]
@Lonwwolf14 work on it

**Comment by iamrahulmahato** [comment]
this issue is important work on it as fast as possible @Lonwwolf14

**Comment by Lonwwolf14** [comment]
Yep Done....!!
