### ISSUE TITLE
🧑‍💻 : ADD A SEARCH BAR FOR SEARCHING GAMES OR TOOLS 

### ISSUE THREAD

**Issue by HS202022** [iamrahulmahato/master-web-development#603]
:red_circle: 🧑‍💻 : ADD A SEARCH BAR FOR SEARCHING GAMES OR TOOLS 

### Screenshots 📷

N/A

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :HIMANGSHU SHARMA
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):CONTRIBUTOR IN GSSOC 24 EXTD,HACKTOBERFEST 2024

***********************************************************************

Happy Contributing! 🚀

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
