### ISSUE TITLE
To Make COUNTER More Effective 

### ISSUE THREAD

**Issue by PREM-A261** [iamrahulmahato/master-web-development#61]
To add Styling to "+", "-" Button
Also want add feature like to take input "+", "-" from Keyboard.

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will do your work

**Comment by manninookala** [comment]
i would want to add a reset button for it, additionally at the bottom, to increase the user experience.
Can you assign this to me under gssoc-ext2024.

**Comment by PREM-A261** [comment]
@PREM-A261 
I complete t
