### ISSUE TITLE
📃: link up game 

### ISSUE THREAD

**Issue by Ketanop321** [iamrahulmahato/master-web-development#610]
🔴 Title : LInk up
🔴 Tech stack :html,css,js
🔴 Objective :In this user user has to match animals to win the game
🔴 Summary : if they matched the animal they will win
📸 Screenshots
 
![image](https://github.com/user-attachments/assets/01888313-15e1-47f2-bf8e-127db5990a2a)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name: ketan kumar
both gssoc and hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Niraj1608** [comment]
@iamrahulmahato assign me the issue
