### ISSUE TITLE
📃: spotify clone

### ISSUE THREAD

**Issue by poojabagodi** [iamrahulmahato/master-web-development#612]
🔴 Title :Spotify clone
🔴 Tech stack :HTML,CSS
🔴 Objective :The objective is to build a pixel-perfect replica of Spotify’s user interface, focusing on responsiveness and aesthetic details. This will involve creating static HTML pages styled with CSS that resemble Spotify’s layout. No back-end functionality or JavaScript will be included; the focus will be purely on the front-end design.
🔴 Summary :The aim of this issue is to create a front-end clone of Spotify using HTML and CSS. This will replicate the visual interface of Spotify, including key components such as the navigation bar, album artwork display, playlists section, and music player controls. The project will serve as a practice for contributors to improve their skills in web design and responsive layouts.
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :poojabagodi
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):GSSOC

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
