### ISSUE TITLE
📃: Speech to Text Converter

### ISSUE THREAD

**Issue by Amanjayswal500** [iamrahulmahato/master-web-development#618]
🔴 Title :Speech to Text Converter
🔴 Tech stack :HTML, CSS and Javascript
🔴 Objective : The objective of SpeechRecognition is to convert spoken language into text using the Web Speech API for user interaction.
🔴 Summary :SpeechRecognition captures spoken input and converts it into text, enabling hands-free control and enhanced accessibility in web applications.
📸 Screenshots

![Screenshot 2024-10-06 231818](https://github.com/user-attachments/assets/415a19e3-6012-4d7c-8c9d-d1c426edbf2c)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Amanjayswal500
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
