### ISSUE TITLE
📃: Want to Add Netflix Clone

### ISSUE THREAD

**Issue by somil0701** [iamrahulmahato/master-web-development#619]
🔴 Title : Netflix Clone UI
🔴 Tech stack : HTML and CSS
🔴 Objective : To create a netflix clone which is UI based on html and css
🔴 Summary :
📸 Screenshots
![image](https://github.com/user-attachments/assets/b098623b-1503-4842-90ec-b0e28ba0b019)
![image](https://github.com/user-attachments/assets/a1d691e3-34b4-4e07-9cbe-281b99c5843e)
![image](https://github.com/user-attachments/assets/38a5216e-9161-42c3-b0b0-5bb6aadab11b)
![image](https://github.com/user-attachments/assets/e410fd0c-5803-495b-a028-cbbb2027faaf)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : somil0701
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC-EXTD

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by somil0701** [comment]
> Can you assign me to add Netflix clone .

Sorry, but I've already made the Pull Request to the main branch succesfully :(

**Comment by nitendra2211** [comment]
okay, no problem
