### ISSUE TITLE
📃: Word Scramble

### ISSUE THREAD

**Issue by Devaki01** [iamrahulmahato/master-web-development#625]
🔴 **Title** : Word Scramble

🔴 **Tech stack** : HTML, CSS, JavaScript  , Bootstrap

🔴 **Objective** : The goal of the Word Scramble game is for players to correctly rearrange a scrambled set of letters to form a valid word. The game tests the player's vocabulary, spelling skills, and quick thinking. Players can earn points based on the speed and accuracy of their answers.

🔴 Summary : Players are presented with a random scrambled word from different categories (e.g., animals, food, geography). Players must rearrange the letters to form the correct word within a specified time limit.

📸 Screenshots
 N/A 

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Devaki Joshi
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): gssoc'24, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by rudrapratap63** [comment]
@Devaki01This issue is already present, and a [PR](https://github.com/iamrahulmahato/master-web-development/pull/659) has already been submitted. Please close this issue.
