### ISSUE TITLE
📃: Add an expense tracker

### ISSUE THREAD

**Issue by devarsheecodess** [iamrahulmahato/master-web-development#637]
🔴 Title: Expense Tracker
🔴 Tech stack: HTML, CSS, JavaScript
🔴 Objective:
The main objective of the Expense Tracker is to help users manage and track their daily expenses efficiently. It enables users to log their income.
🔴 Summary:
The Expense Tracker is a simple web-based application designed to monitor and record daily expenses. Users can add income and expense entries and view a summary of their financial activity. The app provides an easy-to-navigate interface and displays totals for income, expenses, and balance dynamically. It is built with HTML, CSS, and JavaScript

📸 Screenshots
![image](https://github.com/user-attachments/assets/57f15cd2-b098-4e9d-8ee5-9c04d57dbb50)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Devarshee
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC and Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by devarsheecodess** [comment]
@iamrahulmahato plz assign me this issue

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
