### ISSUE TITLE
🧑‍💻 : Adding a very important feature ✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [iamrahulmahato/master-web-development#641]
:red_circle: **Title** : Adding a return to home button
:red_circle: **Enhancement Aim** :  right now you can go to any game/project but there is no return home button , i can make that change and add it  so there is easy transition between pages.

### Screenshots 📷

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : T rahul prabhu
Participant Role :GSSOC and Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by T-Rahul-prabhu-38** [comment]
there are more than 60 projects so it will that a very very long time to fix it , so i have a proposition to make , ill split this into 2 PRs and if you can assign me level3 for both , then 

- i would be motivated to work over all the projects and make sure it works perfect
- it will benefit me aswell as i will be spending lot of time on this.

is this fine with you.

**Comment by iamrahulmahato** [comment]
sorry @T-Rahul-prabhu-38 In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
