### ISSUE TITLE
📃: Custom Emoji Creator

### ISSUE THREAD

**Issue by yeshwanth-ds** [iamrahulmahato/master-web-development#644]
# Custom Emoji Creator

## Project Overview
The Custom Emoji Creator is an interactive web application that allows users to create and customize their own emojis. Users can combine different facial features, accessories, and colors to design unique emojis, which can be downloaded for personal use or shared on messaging platforms.

## Key Features
- **Drag-and-Drop Interface:** Users can easily drag and drop different features (eyes, mouths, accessories) to create their emojis.
- **Export Function:** Allows users to download their custom emojis in PNG format for use in messaging apps or social media.
- **Customizable Features:** A variety of features to choose from, including different shapes, colors, and accessories.
- **Preview Mode:** Users can see a live preview of their emoji as they customize it.
- **Save Designs:** Option to save favorite designs for later use or sharing.

## Tech Stack
- **HTML5:** For the basic structure of the application.
- **CSS3:** To style the user interface, ensuring an appealing and responsive design.
- **JavaScript (ES6):** For the core functionality and interactivity of the application.
  - **Drag-and-Drop Functionality:** Implementing features that can be dragged to the emoji canvas.
  - **Canvas Rendering:** Using the `<canvas>` element to draw and render the customized emojis.
  - **File Download Functionality:** Implementing the ability to download the finished emoji as a PNG image.

## How to Build the App
1. **Set Up the Application Structure (HTML):**
   - Create a main `<div>` for the emoji canvas.
   - Add separate sections for different emoji features (eyes, mouths, accessories).
   - Include a button for exporting the emoji.

2. **Style the Application (CSS):**
   - Design an intuitive layout for the feature selection and canvas area.
   - Ensure responsiveness for different screen sizes and devices.
   - Add visual feedback for drag-and-drop actions.

3. **Implement Application Logic (JavaScript):**
   - Create functions to handle the drag-and-drop functionality for emoji features.
   - Implement logic to draw the selected features on the canvas.
   - Add the export functionality to download the emoji as a PNG image.

## Additional Details
🔴 **Title:** Custom Emoji Creator  
🔴 **Tech Stack:** HTML5, CSS3, JavaScript (ES6)  
🔴 **Objective:** Create an engaging tool that allows users to design and customize their own emojis.  
🔴 **Summary:** The Custom Emoji Creator empowers users to unleash their creativity by providing a platform to design unique emojis, complete with drag-and-drop features and easy exporting options.

## Request for Tags
By presenting the Custom Emoji Creator with this structure and technical depth, I would like to request the assignment of **GCCOC-EXT** and **Level 3** tags for this project.

## Details to Include When Taking the Issue
**Name:** Yeshwanth DS  
**Participant Role:** GSSOC, Hacktoberfest  

By presenting the Custom Emoji Creator with this structure and technical depth, I would like to request the assignment of **GCCOC-EXT** and **Level 3** tags for this project.

**Comment by Niraj1608** [comment]
@iamrahulmahato assign me the issue
