### ISSUE TITLE
📃: Weather Dashboard

### ISSUE THREAD

**Issue by yeshwanth-ds** [iamrahulmahato/master-web-development#645]
# Weather Dashboard

## Project Overview
The **Weather Dashboard** is an interactive web application that allows users to check the current weather conditions for any city around the world. It fetches weather data using the OpenWeather API and displays relevant information such as temperature, humidity, and weather conditions.

## Key Features
- **Fetch Weather Data:** Utilizes the OpenWeather API to get real-time weather information.
- **Display Current Weather:** Shows temperature, humidity, and conditions for the searched city.
- **Search Functionality:** Users can enter any city name to retrieve its weather data.
- **Responsive Design:** Ensures a smooth experience on various devices.
- **Error Handling:** Notifies users when a location is not found.

## Tech Stack
- **HTML5:** For the basic structure of the application.
- **CSS3:** To style the user interface, ensuring a clean and responsive design.
- **JavaScript (ES6):** For core functionality and interactivity, including API calls.

### Set Up the Application Structure (HTML)
1. Create a main `<div>` for the weather display.
2. Add an input field for users to enter the city name.
3. Include a button to initiate the weather search.

### Style the Application (CSS)
- Design an intuitive layout for the input field and weather display area.
- Ensure responsiveness for different screen sizes and devices.
- Add visual feedback for user interactions (e.g., button hover effects).

### Implement Application Logic (JavaScript)
1. Create a function to fetch weather data from the OpenWeather API.
2. Implement error handling to notify users if the location is not found.
3. Display the fetched weather data on the dashboard.

## Additional Details
🔴 **Title:** Weather Dashboard  
🔴 **Tech Stack:** HTML5, CSS3, JavaScript (ES6)  
🔴 **Objective:** Create an engaging tool that allows users to check the weather for any city globally.  
🔴 **Summary:** The Weather Dashboard empowers users to stay informed about current weather conditions through a simple and interactive interface that fetches real-time data from the OpenWeather API.

## Request for Tags
By presenting the Weather Dashboard with this structure and technical depth, I would like to request the assignment of GCCOC-EXT and Level 3 tags for this project.

## Details to Include When Taking the Issue
**Name:** Yeshwanth DS  
**Participant Role:** GSSOC, Hacktoberfest

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
