### ISSUE TITLE
📃: Amazon CLone using HTML,CSS, JavaScript

### ISSUE THREAD

**Issue by Shekhar-Raj** [iamrahulmahato/master-web-development#646]
<h2>I want to add Amazon Clone using HTML, CSS, JavaScript. please assign me the issue so that i can contribute.</h2>

<h3>Demo:</h3>

https://github.com/user-attachments/assets/0c65519b-5e49-45d2-961d-6f89dfdee15a

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
