### ISSUE TITLE
📃: Pac-Man Game

### ISSUE THREAD

**Issue by yeshwanth-ds** [iamrahulmahato/master-web-development#648]
# Pac-Man Game

## Project Overview
The Pac-Man game is a classic arcade-style web application that allows users to navigate a character around a game area, collecting food items while avoiding ghosts. Users can control Pac-Man using the keyboard's arrow keys, with the goal of maximizing their score by eating as many food items as possible.

## Key Features
- **Interactive Gameplay**: Users can control Pac-Man's movement with keyboard inputs to navigate the game area.
- **Scoring System**: Points are awarded for each food item collected, allowing users to track their scores.
- **Dynamic Food Generation**: Food items appear randomly on the game board, providing a different experience each time.
- **Simple User Interface**: A clean layout that focuses on the game experience with real-time score updates.
- **Responsive Design**: Ensures that the game is playable on various devices, from desktops to tablets.

## Tech Stack
- **HTML5**: For the basic structure of the application.
- **CSS3**: To style the game area and characters, ensuring a visually appealing design.
- **JavaScript (ES6)**: For core functionality, including game logic, movement, and scoring.

### Set Up the Application Structure (HTML)
- Create a main `<div>` for the game area.
- Add a score display area to show the current score.
- Include the necessary script references for JavaScript functionality.

### Style the Application (CSS)
- Design an intuitive layout for the game area and score display.
- Ensure the game area is clearly defined and visually engaging.
- Add visual feedback for user interactions, such as highlighting the Pac-Man character.

### Implement Application Logic (JavaScript)
- Create functions to handle Pac-Man's movement based on user input.
- Implement a scoring system that updates when food is collected.
- Use collision detection to manage interactions between Pac-Man and food items.

## Additional Details
🔴 **Title**: Pac-Man Game  
🔴 **Tech Stack**: HTML5, CSS3, JavaScript (ES6)  
🔴 **Objective**: Create an engaging and interactive experience that captures the essence of the classic Pac-Man game.  
🔴 **Summary**: The Pac-Man game invites users to relive the nostalgic arcade experience through an interactive web application, encouraging them to collect food items and achieve high scores.

## Request for Tags
By presenting the Pac-Man game project with this structure and technical depth, I would like to request the assignment of GCCOC-EXT and Level 3 tags for this project.

## Details to Include When Taking the Issue
- **Name**: Yeshwanth DS  
- **Participant Role**: GSSOC, Hacktoberfest

**Comment by Niraj1608** [comment]
@iamrahulmahato assign me this issue too
