### ISSUE TITLE
🧑‍💻 : implement search functionality

### ISSUE THREAD

**Issue by INam1995** [iamrahulmahato/master-web-development#655]
:red_circle: Title: Implement Search Functionality for projects

:red_circle: Enhancement Aim: To allow users to search for specific project using keywords, improving user experience and making it easier to find desired project.

:red_circle: Changes:

Frontend Modifications:

Implement a search function that filters the displayed projects based on the user's input.
Update the state to reflect the filtered list of projects.

Backend Enhancements:

Modify the existing API endpoint to accept search queries and filter projects accordingly.
Ensure that the search is case-insensitive and can handle partial matches.
Test the API for different search inputs to verify functionality.
UI Improvements:

Add a loading indicator while fetching search results.
Provide feedback if no projects match the search criteria.
Screenshots 📷
N/A

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Inam Yadav
 GSSOC-ext contributor 2024

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by 2027Anamika** [comment]
Task Breakdown:

Add Search Input Field:

I will create a search bar at the top of the project list.
The search input will update the search query in the state when a user types.

Filter Projects by Search Query:
1. I will implement a function to filter the projects based on the user's input.
2. Filter the displayed projects in real-time based on the search query (e.g., by project title or description).

Handle Case Sensitivity and Edge Cases:
Handle edge cases where no projects match the search query (show a message like "No projects found").

 I would like to contribute in this issue.
 please assign this to me
 
 Name - Anamika Kumari
 GSSOC-ext contributor 2024
 
 (please add label gssoc-ext24 ,hactoberfest and level 1 ,2 or 3.)

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
