### ISSUE TITLE
📃: React Todo

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [iamrahulmahato/master-web-development#657]
🔴 Title : ToDo app with local storage
🔴 Tech stack : react , CSS
🔴 Objective : 
🔴 Summary : this is a todo list and it has a local storage so even after reload the data is still safe.
📸 Screenshots
<img width="1362" alt="Screenshot 2024-10-07 at 4 21 59 AM" src="https://github.com/user-attachments/assets/b1cc191f-5e7f-439a-ae80-b72657443dfe">

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :T Rahul Prabhu
Participant Role GSSOC

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already present in projects
