### ISSUE TITLE
📃: 2048 Game

### ISSUE THREAD

**Issue by DeshDeepakKushwaha** [iamrahulmahato/master-web-development#665]
🔴 Title :2048 Game
🔴 Tech stack :html,css,js
🔴 Objective :To make a 2048 game which can work on both PC and mobile phone
🔴 Summary :2048 Game is i game where numbers comes in the multiple of 2 and you have to add those numbers till all the grids are not empty
📸 Screenshots NA

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Desh Deepak Kushwaha
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC,Hacktoberfest
***********************************************************************

I would Love to work on this issue.Please assign this to me.
Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.
