### ISSUE TITLE
Issue is Related to Snake Game

### ISSUE THREAD

**Issue by kunalSingh026** [iamrahulmahato/master-web-development#67]
This GitHub issue addresses a specific problem encountered while using Snake Game. The issue pertains to It's difficult for users to understand how to play that Game so could you provide some description about the game and how to play it?
This will Create a Good User Experience
Steps to Reproduce:
 1. Create a help section where users can get details related to the game's problem or provide a description of how to play it in the side area.

**Comment by iamrahulmahato** [comment]
@kunalSingh026 There is already a person working on it
