### ISSUE TITLE
📃: proposal to add the Random Quote Generator project 

### ISSUE THREAD

**Issue by Hamza1821** [iamrahulmahato/master-web-development#673]
📃: Proposal to Add a Random Quote Generator

🔴 Title: QuoteMaster

🔴 Tech Stack: React, CSS, Quote API (e.g., Quotable API or any public Quote API)

🔴 Objective: To create a simple, interactive platform where users can get random quotes from famous personalities, books, or other sources. The application will also allow users to copy and share quotes on social media or save their favorite quotes.

🔴 Summary:
QuoteMaster is a React-based web application designed to generate and display random inspirational, humorous, or philosophical quotes. By leveraging a quote API, the application provides users with a new quote at the click of a button. The design is minimalistic and user-friendly, with features like social media sharing and quote favoriting.
📸 Screenshots

![Screenshot 2024-10-07 at 11-55-02 Random Quote Generator Using HTML CSS and JavaScript](https://github.com/user-attachments/assets/0b7b9301-7293-4913-835e-c9623c1e6af4)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Hamza Mubin
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): **GSSOC-EXTD, Hacktoberfest, Level 3**

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.

**Comment by Hamza1821** [comment]
No problem🙂
