### ISSUE TITLE
📃: ADD RANDOM USER GENERATOR

### ISSUE THREAD

**Issue by amanver45** [iamrahulmahato/master-web-development#677]
🔴 Title:
User Generator:   Creating a Random Users Generator with HTML, CSS, and JavaScript

🔴 Tech stack:
HTML: To structure the layout and display the generated user data.
CSS: For styling the user profiles and making the UI attractive.
JavaScript: To fetch random user data from an API and dynamically display it on the webpage.
🔴 Objective:
The objective of this project is to create a dynamic application that generates random user profiles using JavaScript. The project will showcase how to fetch data from a public API and display it in an organized and visually appealing format.

🔴 Summary:
In this project, you will build a random user generator that displays user information such as name, email, phone, location, and picture. We will use the Random User Generator API to fetch random user data, and JavaScript will dynamically insert this data into the HTML structure.

The project will cover:

Structuring the HTML for the user card layout.
Applying CSS for a clean, modern, and responsive user profile display.
Using JavaScript to fetch data from the Random User Generator API and handle it asynchronously.
Updating the user profiles each time the page is loaded or a "Generate" button is clicked.
This project demonstrates how to integrate external APIs into web development and enhances understanding of fetching and manipulating data, making it a great learning tool for intermediate developers.

**Comment by iamrahulmahato** [comment]
Sorry, someone is already working on this. Do not be demotivated and raise a new issue.

**Comment by amanver45** [comment]
Ok
