### ISSUE TITLE
🧑‍💻 :Adding Footer with social media icons

### ISSUE THREAD

**Issue by RiddhiM170904** [iamrahulmahato/master-web-development#678]
:red_circle: **Title** : Adding Footer
:red_circle: **Enhancement Aim** : Adding footer with social media icons
:red_circle: **Changes** : Adding footer with clickable icons for the social media pages 

### Screenshots 📷
for example this
![WhatsApp Image 2024-10-06 at 21 47 10_21b9d8a2](https://github.com/user-attachments/assets/b7868788-3dbb-4812-9dd5-c80e163b3590)
![image](https://github.com/user-attachments/assets/075bff8d-922c-4ec7-b42e-b9c47d92ec23)

Please Assign me this issue under Gssoc'24 Extd and Hacktoberfest.

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Riddhi Mhadgut
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC'24 EXTD, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
In the guidelines it is already mention there should not be any changes in the home page,Do not be demotivated and raise a new issue.
