### ISSUE TITLE
📃: Tic Tac Toe

### ISSUE THREAD

**Issue by DeshDeepakKushwaha** [iamrahulmahato/master-web-development#683]
🔴 Title: Tic Tac Toe
🔴 Tech stack: HTML, CSS, JavaScript
🔴 Objective: A classic Tic Tac Toe game where two players take turns marking spaces in a 3x3 grid, aiming to be the first to align three of their marks horizontally, vertically, or diagonally. The game is fully responsive and offers an engaging, fun experience.
🔴 Summary: The Tic Tac Toe app is built to provide a simple, enjoyable two-player game experience. Using HTML, CSS, and JavaScript, the app ensures that players can take turns marking the grid while the game logic checks for a winner or a draw. It's fully responsive, offering smooth gameplay across all devices.
📸 Screenshots: N/A

✅ Details to Include When Taking the Issue:
Name: Desh Deepak Kushwaha
Participant Role: GSSoC, Hacktoberfest

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by jyothimanoj12** [comment]
hey can you assign this to me

**Comment by iamrahulmahato** [comment]
the project has already there
