### ISSUE TITLE
📃: Calculator

### ISSUE THREAD

**Issue by DeshDeepakKushwaha** [iamrahulmahato/master-web-development#684]
🔴 Title: Calculator
🔴 Tech stack: HTML, CSS, JavaScript
🔴 Objective: A simple and intuitive calculator application that performs basic arithmetic operations, including addition, subtraction, multiplication, and division. The app is fully responsive and designed for ease of use.
🔴 Summary: The Calculator app provides users with a straightforward interface to perform essential calculations. Built using HTML, CSS, and JavaScript, it allows users to input numbers and operations seamlessly. The responsive design ensures that the calculator works effectively on various devices, making it a handy tool for quick calculations.
📸 Screenshots: N/A

✅ Details to Include When Taking the Issue:
Name: Desh Deepak Kushwaha
Participant Role: GSSoC, Hacktoberfest

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project has already there
