### ISSUE TITLE
📃: Joke Teller Text To Speech

### ISSUE THREAD

**Issue by DeshDeepakKushwaha** [iamrahulmahato/master-web-development#687]
🔴 Title: Joke Teller Text To Speech
🔴 Tech stack: HTML, CSS, JavaScript
🔴 Objective: An interactive application that tells jokes using text-to-speech functionality, providing a fun and engaging way to share humor. Users can click a button to hear a random joke spoken aloud.
🔴 Summary: The Joke Teller app combines humor with technology, allowing users to hear random jokes spoken aloud using text-to-speech capabilities. Built with HTML, CSS, and JavaScript, the app offers a simple interface where users can easily get a new joke at the click of a button. The responsive design ensures that users can enjoy the jokes on any device, making it a delightful tool for sharing laughs.
📸 Screenshots: N/A

✅ Details to Include When Taking the Issue:
Name: Desh Deepak Kushwaha
Participant Role: GSSoC, Hacktoberfest

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by jyothimanoj12** [comment]
hey can you assign this to me under gsoc extended , hacktober fest accepted , level 2 tag
