### ISSUE TITLE
📃: New Project: Drumkit

### ISSUE THREAD

**Issue by Dinkar850** [iamrahulmahato/master-web-development#689]
**Drumkit**

***********************************************************************

- **Tech stack** :
 ![HTML5](https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white) ![CSS3](https://img.shields.io/badge/CSS3-1572B6?style=for-the-badge&logo=css3&logoColor=white) ![JavaScript](https://img.shields.io/badge/JavaScript-F7DF1E?style=for-the-badge&logo=javascript&logoColor=black)
- **Objective** : An interactive drumkit that produces sounds of various components of a drum set when interacted by mouse clicks, key presses or screen touch. 

- **Screenshots**

![Screenshot (1113)](https://github.com/user-attachments/assets/4e0142fd-bca6-412a-bd4d-541ac4454eb7)

***********************************************************************

- **Details to Include When Taking the Issue:**
**Username**: Dinkar850
**Participant Role**: Hacktoberfest

**Comment by iamrahulmahato** [comment]
the project has already there
