### ISSUE TITLE
📃: Amazon Clone

### ISSUE THREAD

**Issue by riyarane46** [iamrahulmahato/master-web-development#696]
🔴 Title : Amazon Clone
🔴 Tech stack : HTML , CSS , JS
🔴 Objective : to create a look alike of amazon website

📸 Screenshots : NA

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Riya Rane
Participant Role : GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project has already there
