### ISSUE TITLE
📃: Portfolio Website

### ISSUE THREAD

**Issue by riyarane46** [iamrahulmahato/master-web-development#698]
🔴 Title : Portfolio Website
🔴 Tech stack : html , css , js
🔴 Objective : Creating a personal website to showcase your projects, skills, and resume

📸 Screenshots : NA

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Riya Rane
Participant Role : GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Jotthecode** [comment]
assign me this work @iamrahulmahato
