### ISSUE TITLE
📃:  Rock-Paper-Scissors

### ISSUE THREAD

**Issue by Amankr200** [iamrahulmahato/master-web-development#705]
🔴 Title :Rock-Paper-Scissors
🔴 Tech stack : html, css
🔴 Objective : to tech basics 
 
📸 Screenshots
 

https://github.com/user-attachments/assets/8d82a21d-5abb-4101-9e69-6aa9404b03dc

✅ Details to Include When Taking the Issue:
Name : Aman Kumar
GSSOC ext, Hacktoberfest,
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by harish08102004** [comment]
Hey @Amankr200 I can work on this.

**Comment by Amankr200** [comment]
assign me first

**Comment by iamrahulmahato** [comment]
there already in the project
