### ISSUE TITLE
🧑‍💻 : Search bar functionality Makes our life better

### ISSUE THREAD

**Issue by Akshithsaai** [iamrahulmahato/master-web-development#725]
:red_circle: **Title** :Search Bar Functionality
:red_circle: **Enhancement Aim** : Add a search to surf through the projects
:red_circle: **Changes** : 
1. Add A search bar
2. Add a functionality to search the games according to user input.
3. Change the display of Games to Alphabetical Order (default)

### Screenshots 📷

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : AkshithSaai
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Akshithsaai** [comment]
@divyasaahithya Hi Divya! I am currently working on this issue.

**Comment by divyasaahithya** [comment]
hello akshith
i am new to open source so i have a quick question,is it ok to work on the
issue even if you are not assigned to it?

**Comment by Akshithsaai** [comment]
@divyasaahithya As it is a small issue, I have started working on basic version of it. 
If you are ok, we can collaborate on the issue if  @iamrahulmahato accepts it.

**Comment by divyasaahithya** [comment]
sure @Akshithsaai

**Comment by iamrahulmahato** [comment]
ok make the search bar ui small make

**Comment by Akshithsaai** [comment]
> ok make the search bar ui small make 

You mean width should be small ? @iamrahulmahato

**Comment by Akshithsaai** [comment]
Version 1

![image](https://github.com/user-attachments/assets/45120770-cd84-4994-a1e2-563795c328be)

Version 2

![image](https://github.com/user-attachments/assets/cd57b20c-bf83-43f8-bf2d-5f7b4a0cad46)

Which One should I finalise @iamrahulmahato .
