### ISSUE TITLE
📃: Restaurant website

### ISSUE THREAD

**Issue by riyarane46** [iamrahulmahato/master-web-development#728]
🔴 Title : Restaurant website
🔴 Tech stack : html , css , js
🔴 Objective : to create a restaurant website which has a sign up page , restaurant cards , filtering option , every restaurant has its own dedicated page , restaurant dining and booking 

📸 Screenshots
NA

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Riya Rane
Participant Role : GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
fix #1440
