### ISSUE TITLE
Adding chess game

### ISSUE THREAD

**Issue by Atishyy27** [iamrahulmahato/master-web-development#73]
This might help a lot of people to contribute as well, also adds up some weightage to the project overall.

**Comment by Pujitha254** [comment]
Hey Rahul!! just checked your project its pretty good .I like the css part in your project. And we can improve it by adding interactive games and i wanted to work upon it if it is ok for you.So could you please assign this issue to me.

**Comment by Sourabh782** [comment]
@iamrahulmahato is this issue free? if @Pujitha254 not working on it can i contribute too?

**Comment by jjf2009** [comment]
@iamrahulmahato if this issue is open can i work on it
