### ISSUE TITLE
Create "Element Mixer" - A Fun Elemental Combination Game

### ISSUE THREAD

**Issue by Lonwwolf14** [iamrahulmahato/master-web-development#744]
### Description
Develop a simple, playful web game where players mix basic elements to discover new ones. Start with four core elements and let players experiment to create quirky combinations!

### Game Features
1. Drag-and-drop interface for mixing elements
2. Animated reactions when elements combine
3. Discovery log to track player's creations
4. Silly descriptions for each new element created

**Comment by manopriyam** [comment]
I would like to work on this. I request you to assign me this under the tags **gssoc-extd** and **hacktoberfest**.
