### ISSUE TITLE
📃: Create a  Weight Converter Project

### ISSUE THREAD

**Issue by amanver45** [iamrahulmahato/master-web-development#756]
🔴 Title:
Weight Converter: A Simple Unit Conversion Web App Using HTML, CSS, and JavaScript

🔴 Tech stack:
HTML: Structure the weight converter form and input fields
CSS: Style the user interface (form, buttons, and input)
JavaScript: Handle the conversion logic and dynamically display results
🔴 Objective:
The objective of this project is to create a simple web-based weight converter that allows users to convert weight between different units, such as kilograms, pounds, and ounces. The project aims to provide an interactive and user-friendly experience to quickly perform weight conversions.

🔴 Summary:
This project involves building a web application that allows users to input a weight in one unit (e.g., kilograms) and convert it into another unit (e.g., pounds or ounces). The app will include a form with a drop-down menu for selecting weight units and an input field for entering the weight. The conversion will be handled in real-time using JavaScript, and the result will be displayed below the form.

Features include:

A simple user interface with an input field, unit selection dropdown, and result display.
A variety of units to choose from, including kilograms (kg), pounds (lbs), and ounces (oz).
Conversion formulas will be applied in JavaScript, updating the result instantly when the user enters a value or changes the selected units.

**Comment by uzefaqureshi06** [comment]
can you please please assign this issue to me i will make my best

**Comment by amanver45** [comment]
@iamrahulmahato assign nhi kiya
