### ISSUE TITLE
Enhance To-Do List Functionality for Website

### ISSUE THREAD

**Issue by ArpitaAgrahari** [iamrahulmahato/master-web-development#77]
I would like to propose an enhancement to the existing to-do list feature on the website. 

- The enhancement would allow users to update or edit their to-do items after they have been added.
-  This functionality can improve the overall user experience by giving users more flexibility to modify tasks without having to delete and recreate them.
- By implementing this, users can easily correct any mistakes or adjust their tasks as needed, making the to-do list more dynamic and user-friendly.

**Comment by iamrahulmahato** [comment]
@ArpitaAgrahari, someone is already working on it
