### ISSUE TITLE
📃: creating a simon says game

### ISSUE THREAD

**Issue by riyarane46** [iamrahulmahato/master-web-development#775]
🔴 Title : simon says game
🔴 Tech stack : HTML, CSS, JavaScript
🔴 Objective : Develop a Simon Says game where users must follow and repeat an increasing sequence of lights and sounds. The game challenges users' memory and reflexes.
🔴 Summary : The Simon Says Game is an interactive memory game in which users must repeat a sequence of flashing lights in the correct order. Each round adds a new light to the sequence, making it progressively harder. The player continues as long as they can accurately follow the sequence. This game will include:

Four colored buttons, each with a corresponding sound.
Flashing animations for each button.
A score tracker that updates as users correctly follow the sequence.
A "Game Over" screen that displays the final score when the user makes a mistake.

📸 Screenshots : NA

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Riya Rane
Participant Role : GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by DivyaJyothi9** [comment]
@riyarane46 this issue was opened before..
