### ISSUE TITLE
📃:Create a  restaurant webpage using only HTML and CSS.

### ISSUE THREAD

**Issue by poojabagodi** [iamrahulmahato/master-web-development#776]
🔴 Title :restaurant website
🔴 Tech stack :HTML,CSS
🔴 Objective :Create a  restaurant webpage using only HTML and CSS.
🔴 Summary :Design a webpage with sections for the restaurant name, menu, location, and contact form. Use CSS for layout, responsiveness, and basic interactive styling (hover effects, form validation).

📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Rahul-Morabiya** [comment]
Please Assign me this issue.
ThankYou
Name : Rahul-Morabiya
Participant Role : GSSOC
