### ISSUE TITLE
📃: Add python code editor

### ISSUE THREAD

**Issue by Aditijainnn** [iamrahulmahato/master-web-development#778]
🔴 Title : Python code editor
🔴 Tech stack : html css js
🔴 Objective : to add python editor web app

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): gssoc ext hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Thejaggeddevil** [comment]
hi @iamrahulmahato could  you please assign it to me i want to work on that for hacktoberfest
