### ISSUE TITLE
📃: Want to add a Tic-Tac-Toe

### ISSUE THREAD

**Issue by rahulbamnuya** [iamrahulmahato/master-web-development#790]
🔴 Title : Tic-Tac-Toe Game with all functionality
🔴 Tech stack :HTML,CSS,JS
🔴 Objective :Want to contribute in open source
🔴 Summary :
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by sanjeev0304** [comment]
I am intrested in resolving the issue please assign the issue to me  thank you!!

**Comment by iamrahulmahato** [comment]
already present in project
