### ISSUE TITLE
📃: Add Price Alert Feature for Crypto Tracker App  

### ISSUE THREAD

**Issue by SCR01** [iamrahulmahato/master-web-development#796]
🔴 **Title**: Add Price Alert Feature for Crypto Tracker App  
🔴 **Tech stack**: [Specify the tech stack used, e.g., React, Node.js, etc.]  
🔴 **Objective**: Allow users to set custom price alerts for cryptocurrencies.  
🔴 **Summary**: Users will receive notifications when the price reaches specified thresholds, enabling timely trading decisions.  
📸 **Screenshots**: N/A  

***********************************************************************

✅ **Details to Include When Taking the Issue:**  
**Name**: [Your Name]  
**Participant Role**: GSSOC'24 contributor  

***********************************************************************

Happy Contributing! 🚀  
Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by SCR01** [comment]
@iamrahulmahato check it, please!

**Comment by iamrahulmahato** [comment]
already added
