### ISSUE TITLE
📃: Catch the Ball Game

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [iamrahulmahato/master-web-development#799]
🔴 Title :Catch the Ball Game
🔴 Tech stack :HTML, CSS, js
🔴 Objective : A game where balls fall from the top of the screen and the player has to "catch" them using a basket controlled by the keyboard or mouse
🔴 Summary :a fun game
📸 Screenshots
NA

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
Sanika Bhalerao(gssoc-extd)

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by SanikaBhalerao1345** [comment]
Hii @iamrahulmahato pls check the issue. I would like to work upon it.
Thankyou

**Comment by uzefaqureshi06** [comment]
can you please please assign this issue to me i will make my best
