### ISSUE TITLE
ADDING DARK MODE AND READING FEATURES TO THE STORIBAZZI AND IMPROVING UI

### ISSUE THREAD

**Issue by dnyanesh99borse** [iamrahulmahato/master-web-development#80]
**### ADDING DARK MODE AND READING FEATURES TO THE STORIBAZZI AND IMPROVING UI**

**I plan to implement dark mode and light mode options for the StoryBazzi application, enhancing the reading experience for users. Given the nature of the application, these modes will cater to users' preferences and improve readability, especially in different lighting conditions.

Additionally, I will incorporate a quick search feature that allows users to search for specific words within documents using their respective browsers. This functionality will facilitate easy access to relevant information, making the reading process more efficient.

Furthermore, I will implement static text highlighting during reading, allowing users to easily identify and follow along with the text. This feature will enhance focus and comprehension, providing a more engaging and user-friendly reading experience.

Overall, these enhancements will significantly improve the usability and enjoyment of the StoryBazzi application for all users.**

**Comment by himanchal08** [comment]
Could you please assign this issue to me? I believe I can provide a solution. I have a similar project in which i have already added dark mode , So I can help you in this . [Dark_Mode_Demo](https://dark-mode-pro.vercel.app/)
