### ISSUE TITLE
📃: Add Google Search Clone

### ISSUE THREAD

**Issue by nksmanya** [iamrahulmahato/master-web-development#800]
🔴 Title: Google Search Clone
🔴 Tech stack: HTML, CSS

A simple Clone of Google Search, Google Advanced Search, and Google Images purely made with HTML and CSS.

To be Mentioned while taking the issue :

Full name : Manya .N
What is your participant role? Gssoc, hacktoberfest contributor
@iamrahulmahato  Please assign me this task, I can assure you to do my best towards this issue.

**Comment by uzefaqureshi06** [comment]
can you please please assign this issue to me i will make my best

**Comment by Kuldeepcoder2006** [comment]
can you please please assign this issue to me i will make my best

**Comment by uzefaqureshi06** [comment]
can you please please assign this issue to me i will make my best
