### ISSUE TITLE
📃: Math quiz game

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [iamrahulmahato/master-web-development#802]
🔴 Title : Math quiz game 
🔴 Tech stack :html,css,js
🔴 Objective :A game where players solve random math problems within a time limit.
🔴 Summary :puzzel games
📸 Screenshots

NA

***********************************************************************

✅ Details to Include When Taking the Issue:Math quiz game
Name :Sanika Bhalerao (gssoc-extd contributor)

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by SanikaBhalerao1345** [comment]
@iamrahulmahato pls check issue created. I would like to work upon it

**Comment by uzefaqureshi06** [comment]
can you please please assign this issue to me i will make my best

**Comment by Kuldeepcoder2006** [comment]
can you please please assign this issue to me i will make my best
