### ISSUE TITLE
📃: QR Code Scanner

### ISSUE THREAD

**Issue by Akshithsaai** [iamrahulmahato/master-web-development#808]
🔴 Title : QR Scanner 
🔴 Tech stack : ReactJS, HTML, CSS,
🔴 Objective : To Scan a QR Code 
🔴 Summary : 
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : AkshithSaai
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC, Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Akshithsaai** [comment]
@iamrahulmahato I would like to contribute this to the repo. Please Assign this to me.

**Comment by iamrahulmahato** [comment]
already added

**Comment by Akshithsaai** [comment]
@iamrahulmahato QR code generator is added but I wanted to add QR Code scanner .
