### ISSUE TITLE
📃: Memory Card Game

### ISSUE THREAD

**Issue by monishkumardvs** [iamrahulmahato/master-web-development#819]
🔴 Title: Memory Card Game

🔴 Tech stack:

Frontend: HTML, CSS, JavaScript
Libraries: None (vanilla JavaScript)
🔴 Objective:
To create an engaging and interactive Memory Card Game where players can test their memory by finding and matching pairs of cards.

🔴 Summary:
The Memory Card Game is a classic matching game implemented using HTML, CSS, and JavaScript. The game consists of a grid of face-down cards that the player must flip over to reveal the images underneath. The objective is to match pairs of cards with the same image. Players take turns flipping over two cards at a time, and if they match, those cards remain face up. If they don’t match, the cards are flipped back over. The game continues until all pairs are matched. This project focuses on enhancing memory skills while providing an enjoyable user experience.

📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Monish kumar
Participant Role :GSSOC, Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by DivyaJyothi9** [comment]
@monishkumardvs this issue was open before..

**Comment by iamrahulmahato** [comment]
already added
