### ISSUE TITLE
ENHANCING THE UI OF LOVE CALCULATOR WITH ADDING THE RELATED VIDEO TO THE BAGROUND AS PER THE LOVE PERCENTEAGE

### ISSUE THREAD

**Issue by dnyanesh99borse** [iamrahulmahato/master-web-development#84]
**ENHANCING THE UI OF LOVE CALCULATOR WITH ADDING THE RELATED VIDEO TO THE BAGROUND AS PER THE LOVE PERCENTEAGE**

**I want to say that we can show the attractive videos in the background as per the love percentage shown by the calculator, rather than the only static single colour.

this will help to maintain the user for the more time on the site as well and will be more interacting to the user.

not only the videos we can also  display the images.

specially this videos and pictures will not harm any one emotionally and all. 

just for the entertainment purpose**

**Comment by dnyanesh99borse** [comment]
PLEASE ASSIGN THIS ISSUE TO ME. I CAN SAY THAT AS A EXPERIENCED FRONTEND DEVELOPER  I CAN MAKE THIS LOVE CALCULATOR SUCH THAT EVERYONE WILL LOVE TO STAY ON THE SITE AND WANT TO ENJOY IT.

**Comment by iamrahulmahato** [comment]
can you send the preview or ui

**Comment by dnyanesh99borse** [comment]
sure sir .. 

I want to say that when anyone will get the result or the output after filling the input in the love calculator then we can show them the respective videos and photos as per their percentage to the background. so that the users will get the next level experience of spending time there. 

**for example:** 

### **THE CURRENT USER INTERFACE IS THIS:**
![image](https://github.com/user-attachments/assets/3dd511f1-76c8-4f13-90c2-32344aadd5b9)

**### THE CHANGES THAT WILL MADE:**
![Screenshot 2024-10-02 112015](https://github.com/user-attachments/assets/b5748e4e-9c58-42ee-9cdd-b0656a57622d)


**### THE PROCESS:**

LET SUPPOSE I ENTERED THE MY NAME AND MY CRUSH NAME SUCCESSFULLY : 
AND THEN I WILL GET SOME PERCENTAGE OF LOVE
AND THEN WHEN THE PERCENTAGE WILL BE DISPLAY THEN THE RESPECTIVE VIDEOS ,IMAGES, OR THE QUOTES WILL DISPLAY ON THE SCREEN BESIDE AND MUCH MORE.
WHICH WILL DEFINATELY INCREASES THE USER EXPERIENCE.

~thanks

**Comment by dnyanesh99borse** [comment]
HOPE YOU GET IT SO PLEASE ASSIGN THIS TASK TO ME TO WORK ON IT AND TAKE IT TO NEXT LEVEL.

**Comment by iamrahulmahato** [comment]
If you add video, the loading speed of the website may be compromised, so please create another issue. I am closing it.
