### ISSUE TITLE
📃: automated greetings bot

### ISSUE THREAD

**Issue by Ketanop321** [iamrahulmahato/master-web-development#846]
Description:
This pull request implements a new GitHub Actions workflow named "Greetings," which automatically greets users who open new issues or pull requests in this repository.
📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :ketan
Participant Role (CONTRIBUTOR):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already added
