### ISSUE TITLE
MAKING LOGIN AND SIGNUP PAGE FOR THE WEBSITE WITH PROVIDING THE LOGIN/SIGNUP BUTTON TO THE HOMEPAGE.

### ISSUE THREAD

**Issue by dnyanesh99borse** [iamrahulmahato/master-web-development#85]
**### MAKING LOGIN AND SIGNUP PAGE FOR THE WEBSITE WITH PROVIDING THE LOGIN/SIGNUP BUTTON TO THE HOMEPAGE.**

**I will provide the login signup toggle button to the home page of the website and then from there anyone can allow to login or signup .
or we can say they will redirect to the login and signup page.**

**Comment by dnyanesh99borse** [comment]
PLEASE ASSIGN THIS ISSUE TO ME. AS A EXPERIENCED FRONTEND DEVELOPER I CAN RESOLVE THIS ISSUE GREATLY

**Comment by iamrahulmahato** [comment]
can you send the ui or preview of it

**Comment by dnyanesh99borse** [comment]
**I WILL PROVIDE THE LOGIN AND SIGNP BUTTON  TO THE LANDING PAGE AND THEREAFTER WILL REDIRECT TO  THE LOGIN AND SIGNUP PAGE AS PER GIVEN BELOW WHICH WILL DEFINATELY HELPFUL.**

![image](https://github.com/user-attachments/assets/62773b83-a501-462f-9d27-59964d1bc641)

**Comment by iamrahulmahato** [comment]
If you create a login page, it will be difficult for other users to access the project, and we need to add the backend, so I am closing the issue. Do not be disappointed, create another issue.
