### ISSUE TITLE
🧑‍💻 : Want to add css properties to make the website more amazing.

### ISSUE THREAD

**Issue by Dipanita45** [iamrahulmahato/master-web-development#850]
:red_circle: **Css Properties** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : 

### Screenshots 📷
![Screenshot 2024-10-10 085451](https://github.com/user-attachments/assets/8f13fe3c-b621-4572-83bc-2c2e3707747a)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name :
Contributor(GOSSOC 2024EXTD)

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
share the ui

**Comment by Dipanita45** [comment]
Please assign me so that I can start working

**Comment by biswajit-sarkar-007** [comment]
Hi  @iamrahulmahato ,

I see that this issue is open and would love to work on it. Could you please assign it to me?

Thank you!
