### ISSUE TITLE
📃: Add Navigation Bar to Improve Site Usability

### ISSUE THREAD

**Issue by Sitambhra02** [iamrahulmahato/master-web-development#851]
🔴 Title : Adding Navigation Bar
🔴 Tech stack :HTML,CSS,JAVASCRIPT
🔴 Objective : I propose adding a responsive navigation bar to improve the website's structure and user experience. The navbar will include essential links (e.g., Home, Features, Contact, About Us) and will be designed to work across various screen sizes
 
 Assign me this, so i can move forward! 
***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Sitambhra
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
sorry I want to keep the website minimal, do not demotivate  raise a new issue
