### ISSUE TITLE
📃: WORD SCRAMBLE GAME

### ISSUE THREAD

**Issue by harshgupta2125** [iamrahulmahato/master-web-development#856]
🔴 Title :word scramble game
🔴 Tech stack : html css js
🔴 Objective : focus to learn new words
🔴 Summary :Word scramble is an easy word game you can create as a beginner. In this game, players must unscramble a set of letters to form a word within a given time limit of 30 seconds. And to make the game a little easier, users also get a hint about the word they are trying to guess.
📸 Screenshots

N/A
***********************************************************************

✅ Details to Include When Taking the Issue:
Name : @iamrahulmahato 
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC ext
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already added
