### ISSUE TITLE
📃: Add a Spotify clone

### ISSUE THREAD

**Issue by Hamza1821** [iamrahulmahato/master-web-development#860]
🔴 Title : Spotify clone
🔴 Tech stack : Html css Js 
🔴 Objective :
🔴 Summary :
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Hamza Mubin
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): gssoc-ext, hactoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by snehaamujri** [comment]
Please assign this to me @Hamza1821 under gssoc-ext,hactoberfest

**Comment by iamrahulmahato** [comment]
already present
