### ISSUE TITLE
📃: Want to add crossy road game

### ISSUE THREAD

**Issue by AbhijitMotekar99** [iamrahulmahato/master-web-development#867]
🔴 Title : Crossy Road game
🔴 Tech stack : HTML, CSS ,JavaScript
🔴 Objective : The goal of this game is to guide a character across roads, avoiding obstacles like vehicles and rivers, while reaching the other side safely
🔴 Summary : Crossy Road is a simple yet engaging arcade game where players control a character trying to cross busy roads and rivers. The player needs to avoid obstacles by moving the character forward, backward, left, and right. The challenge increases as the game progresses, making it a test of quick reflexes and decision-making skills. The project showcases a combination of game logic, event handling, and dynamic rendering using JavaScript.
📸 Screenshots

![Crossy road game](https://github.com/user-attachments/assets/1d46a228-2d48-462a-889d-6e5158fbb66f)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Abhijit Motekar
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): `Gssoc-ext` `Hacktoberfest`

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by AbhijitMotekar99** [comment]
Hey @iamrahulmahato 
This is not level 1 project please give level 2 for this.

**Comment by iamrahulmahato** [comment]
i am closing it as it is duplicate
