### ISSUE TITLE
🐞 : Repository excluded from Hacktoberfest

### ISSUE THREAD

**Issue by Amankr200** [iamrahulmahato/master-web-development#868]
Is this repository excluded from Hacktoberfest?

I want to ensure that contributions made here count towards the Hacktoberfest challenge. Could you please confirm if this project is eligible? @iamrahulmahato 
![Screenshot 2024-10-09 164419](https://github.com/user-attachments/assets/32e68193-c077-49ba-875c-3e368e740451)

Thank you!

**Comment by iamrahulmahato** [comment]
now this repo for gssoc
