### ISSUE TITLE
📃: SQUID GAME

### ISSUE THREAD

**Issue by Ketanop321** [iamrahulmahato/master-web-development#870]
🔴 Title :SQUID GAME(using three.js)
🔴 Tech stack :HTML,CSS ,JS(three.js)
🔴 Objective :Simple game based of on a popular Netfilx seires called "Squid Game".
🔴 Summary :This 3D game incorporates immersive sound effects, The objective is to reach the end of the challenging course as quickly as possible , and the first player to cross the finish line will emerge victorious.
📸 Screenshots
![image](https://github.com/user-attachments/assets/a41ac54a-9d01-4ecb-998a-fa801ed607f5)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :KETAN KUMAR
Participant Role (CONTRIBUTOR)

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already present
