### ISSUE TITLE
📃: Adding Breakout game

### ISSUE THREAD

**Issue by AbhijitMotekar99** [iamrahulmahato/master-web-development#872]
🔴 Title : Breakout Game
🔴 Tech stack : html , css , js
🔴 Objective : The objective is to break all the bricks by bouncing a ball off a paddle while preventing the ball from falling off the screen.

🔴 Summary : Breakout is a classic arcade game where the player controls a paddle to bounce a ball, aiming to destroy all the bricks at the top of the screen. The game becomes more challenging as the ball increases in speed and bricks become harder to hit. This project implements the game using JavaScript for game physics, event listeners for paddle control, and dynamic rendering of bricks, offering an enjoyable experience of one of the most iconic arcade games.

📸 Screenshots

![Breakout game](https://github.com/user-attachments/assets/1902cd0f-a82c-4bca-9fa6-2d7f53ad71ff)

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Abhijit Motekar
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.) : `gssoc-ext` `Hacktoberfest` 

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already present in project
