### ISSUE TITLE
🧑‍💻 : Adding the contributors page to mention all the awersome people who have contributed to the website.

### ISSUE THREAD

**Issue by tarunkumar2005** [iamrahulmahato/master-web-development#875]
Adding the contributors page to mention all the awersome people who have contributed to the website.

### Screenshots 📷
N/A

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Tarun Kumar
Participant Role: GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

@iamrahulmahato Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by iamrahulmahato** [comment]
already present in readme file
