### ISSUE TITLE
📃:  Rock-Paper-Scissors Game

### ISSUE THREAD

**Issue by tarunkumar2005** [iamrahulmahato/master-web-development#877]
🔴 Title : Rock-Paper-Scissors Game
🔴 Tech stack : Html, tailwind and js.
🔴 Objective : Rock paper scissors game creating
🔴 Summary : Rock-Paper-Scissors Game
📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Tarun Kumar
Participant Role: GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

@iamrahulmahato Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this.

**Comment by snehaamujri** [comment]
hey can we collaboarte on this @tarunkumar2005

**Comment by iamrahulmahato** [comment]
the project is already present
