### ISSUE TITLE
📃: Simon Says Game

### ISSUE THREAD

**Issue by tarunkumar2005** [iamrahulmahato/master-web-development#878]
🔴 Title :Simon Says Game
🔴 Tech stack : html, tailwind and js
🔴 Objective : Simon Says Game
🔴 Summary :Simon Says Game
📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Tarun Kumar
Participant Role: GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

@iamrahulmahato Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this.

**Comment by iamrahulmahato** [comment]
the project is already present
