### ISSUE TITLE
📃:  Web based quiz app

### ISSUE THREAD

**Issue by Sourabh782** [iamrahulmahato/master-web-development#882]
🔴 Title : QuizTime
🔴 Tech stack : HTML, CSS, JS
🔴 Objective : An app to test skills of users
🔴 Summary : a simple quiz app used to test users skills
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : sourabh singh rawat
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project is already present
