### ISSUE TITLE
📃: Random quote generator

### ISSUE THREAD

**Issue by Codewithmeowmeow** [iamrahulmahato/master-web-development#888]
🔴 Title :Random quote generator
🔴 Tech stack : html css javascript
🔴 Objective : create a new project
🔴 Summary :
📸 Screenshots
na

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project is already present
