### ISSUE TITLE
🐞 : UI Improvement 

### ISSUE THREAD

**Issue by 17arindam** [iamrahulmahato/master-web-development#890]
:red_circle: Currently the ui is broken:
:red_circle: ui broken:
:red_circle: **Changes** 
- will correct the ui

### Screenshots 📷
![image](https://github.com/user-attachments/assets/d2a21344-baea-4509-9b3b-8f1a88fd3926)

************************************************************

✅ Details to Include When Taking the Issue:
Name :Arindam Bera
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
GSSOC Hacktoberfest
***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by 17arindam** [comment]
@iamrahulmahato please assign me this issue

**Comment by iamrahulmahato** [comment]
someone already working on it
