### ISSUE TITLE
🧑‍💻 :  Improving ui for game container

### ISSUE THREAD

**Issue by neerajsharma897** [iamrahulmahato/master-web-development#893]
:red_circle: **Title** : Improving the ChatBot and Relaxio's ui
:red_circle: **Enhancement Aim** :  Improve website's appeal
:red_circle: **Changes** : Will change the styling to match with rest of the game styling to have uniform styling

### Screenshots 📷
![image](https://github.com/user-attachments/assets/22b2d081-63d0-4d0e-a51a-5ef5fd9dcad7)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Neeraj Sharma
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
someone already working on it

**Comment by neerajsharma897** [comment]
Okay thanks for the reply 😀
