### ISSUE TITLE
📃: Add Typing Speed Test Game

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [iamrahulmahato/master-web-development#900]
🔴 Title : Typing Speed Test
🔴 Tech stack : HTML    CSS   JavaScript
🔴 Objective :  test typing speed with fun
🔴 Summary : A game where users test their typing speed by typing a random passage. It can display the number of words per minute (WPM) and accuracy, with features like countdown timers and progress tracking.

📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Adarsh Chaubey
Role: gssoc-ext,   hectoberfest

***********************************************************************
@iamrahulmahato please assign me this task

**Comment by Adarsh-Chaubey03** [comment]
@iamrahulmahato please assign this task to me

**Comment by iamrahulmahato** [comment]
the project is already present
