### ISSUE TITLE
Improving UI design of currency converter

### ISSUE THREAD

**Issue by Pushpa472** [iamrahulmahato/master-web-development#909]
@iamrahulmahato  Enhance the UI design of the currency converter to improve its visual appeal and user experience. This includes updating the layout, color scheme, and overall aesthetics to create a more modern and intuitive interface.

![image](https://github.com/user-attachments/assets/14168c66-3e74-4d67-8ae1-142032d7138a)

**Comment by Pushpa472** [comment]
@iamrahulmahato I am still working

**Comment by jashwanthbavandlapalli** [comment]
Hi @Pushpa472 , I noticed you’re assigned to this issue. I’m really interested in working on it too. If you’re unable to continue, I’d love to take over or assist you. I believe I can bring some valuable insights to this problem. Let me know what you think!

**Comment by Pushpa472** [comment]
@iamrahulmahato Please add the labels

**Comment by Pushpa472** [comment]
@iamrahulmahato Please assign proper label or level because PR / merged not accepted hacktoberfest
