### ISSUE TITLE
📃: Add TODO Application

### ISSUE THREAD

**Issue by T-Fathima** [iamrahulmahato/master-web-development#913]
🔴 **Title**: Add a To-Do Application

🔴 **Tech Stack**: 
- HTML, CSS, JavaScript
- Git for version control

🔴 **Objective**: 
The objective is to develop a functional and user-friendly To-Do application. The application should allow users to add, edit, delete, and mark tasks as completed. It should feature a clean UI, responsive design, and smooth interactions, ensuring a good user experience.

🔴 **Summary**:
This issue proposes building a To-Do list application where users can manage their daily tasks. The key functionalities will include adding new tasks, deleting existing tasks, and marking tasks as done. The app should provide an easy-to-use interface, featuring categories or tags for task organization, a search function, and a way to prioritize tasks. Additionally, the app will support persistent data storage (e.g., using local storage or backend), and users will be able to filter tasks by completion status.

***********************************************************************

✅ **Details to Include When Taking the Issue**:
- **Name**: Tatheer Fathima
- **Participant Role**: GSSoC-ext, Hacktoberfest

I would to do it 
@iamrahulmahato Please assign it to me under gssoc-ext and hacktoberfest

**Comment by iamrahulmahato** [comment]
the project is already present
