### ISSUE TITLE
add footer in home page

### ISSUE THREAD

**Issue by Anju-Narnolia** [iamrahulmahato/master-web-development#928]
a website is not complete without a footer.
@iamrahulmahato please assign this task to me

**Comment by Iampratyush004** [comment]
@iamrahulmahato please assign this task to me
![Screenshot 2024-10-10 210839](https://github.com/user-attachments/assets/3621329a-8284-48c7-9047-15dd9c675e2a)

**Comment by iamrahulmahato** [comment]
can you share the ui

**Comment by Iampratyush004** [comment]
@iamrahulmahato 
![Screenshot 2024-10-11 171840](https://github.com/user-attachments/assets/201e6b4a-eaed-460e-bf80-426ca231afe4)
expected ui

**Comment by Iampratyush004** [comment]
@iamrahulmahato  PLZ SEE TO THIS REQUEST AND ASSIGN ME
I HAVE A READY CODE NOW 
![Uploading Screenshot 2024-10-11 192441.png…]()

**Comment by Iampratyush004** [comment]
@iamrahulmahato kindly assign me this task and labels as this is not reflecting in my hacktoberfest id.
kindly see to it and do the needed
