### ISSUE TITLE
📃: Coin Toss Game

### ISSUE THREAD

**Issue by tarunkumar2005** [iamrahulmahato/master-web-development#930]
🔴 Title Coin Toss Game
🔴 Tech stack : html, tailwind and js
🔴 Objective : Coin Toss Game
🔴 Summary :Coin Toss Game: in this game people will be able to flip a virtual coin like if two people are deciding on something they can use this.
📸 Screenshots
N/A

✅ Details to Include When Taking the Issue:
Name : Tarun Kumar
Participant Role: GSSOC, Hacktoberfest

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

@iamrahulmahato Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this.

**Comment by byteom** [comment]
please assign this task to me.
