### ISSUE TITLE
📃: Typing Speed Test

### ISSUE THREAD

**Issue by tarunkumar2005** [iamrahulmahato/master-web-development#932]
🔴 Title :Typing Speed Test
🔴 Tech stack : html, css or tailwind, js
🔴 Objective : Typing Speed Test
🔴 Summary : in this game, user will be given a sentence to type and need to type as fast as possible and at the end it will show the speed of the user.
📸 Screenshots
N/A

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Tarun Kumar
Participant Role:  GSSOC, Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

@iamrahulmahato Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by iamrahulmahato** [comment]
the project is already present so I am closing the issue
