### ISSUE TITLE
🐞 :  Broken layout 

### ISSUE THREAD

**Issue by Dinkar850** [iamrahulmahato/master-web-development#941]
:red_circle: **Title** : Correcting broken layout
:red_circle: **Bug** : The layout has been disturbed 

### Screenshots 📷
![image](https://github.com/user-attachments/assets/e21e1c14-88e6-437d-bf15-fed893292f3a)

************************************************************

Name : Dinkar850
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC, Hacktoberfest,

**Comment by Dinkar850** [comment]
@iamrahulmahato I have fixed the issue, as soon as the issue is assigned, I will raise the PR. 

![image](https://github.com/user-attachments/assets/65242ace-6918-41f7-a76a-ed0e1e5d46a6)

**Comment by Dinkar850** [comment]
@iamrahulmahato 
Have made a PR #942 for this issue, please see.

**Comment by Iampratyush004** [comment]
Please assign this task to me . @Dinkar850 has not been assigned this task and has not followed guidelines properly, i request the admin @iamrahulmahato to please look into the matter and kindly assign this task to me . Although i have a ready code but not put PR. 
Whatever may feel right , but kindly add me to this task.
Thanks
