### ISSUE TITLE
🧑‍💻 : Search bar functionality

### ISSUE THREAD

**Issue by meghanakn473** [iamrahulmahato/master-web-development#948]
:red_circle: **Title** : Search Bar
:red_circle: **Enhancement Aim** : To help users find their games easily

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Meghana
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): Gssoc-extd, hacktoberfest

@iamrahulmahato please assign me this issue i want to work on it

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by Iampratyush004** [comment]
@iamrahulmahato  please assign this task to me for a search bar to find the projects easily 

Details to Include When Taking the Issue:
Name : Pratyush
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): Gssoc-extd, hacktoberfest accepted

**Comment by iamrahulmahato** [comment]
someone already working on this issue
