### ISSUE TITLE
🧑‍💻 : improve the styling of ToDo App

### ISSUE THREAD

**Issue by Riyachauhan11** [iamrahulmahato/master-web-development#952]
:red_circle: **Title** :improve the styling of ToDo App
:red_circle: **Enhancement Aim** : increase user interaction and make the list look more appealing to users.
:red_circle: **Changes** : 
-> improve text readability
-> work on the input boxes and buttons
-> remove unnecessary numbering of tasks 
-> adding these features wrt to the bg set currenttly

### Screenshots 📷

![image](https://github.com/user-attachments/assets/22be5c23-8408-4a2b-856d-bbc9ae83a9ed)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Riya Chauhan
Participant Role:  GSSOC, Hacktoberfest, Contributor
please assign me the issue.

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by AdarshThakare** [comment]
Name : Adarsh Thakare
Participant Role: GSSOC, Hacktoberfest, Contributor

I would love to work on this issue. Please assign this to me.

**Comment by VanshGarg06** [comment]
Hi! I am eager to contribute anyhow towards this issue. Kindly assign me this issue to me.
Name : Vansh Garg
Participant Role: GSSOC, Hacktoberfest,Contributor
Please assign me the issue

**Comment by AyushiMaithani** [comment]
Name : Ayushi Maithani
Participant Role: GSSOC-extnd, Hacktoberfest, Contributor
please assign me the issue.

**Comment by byteom** [comment]
please assign this task to me.
