### ISSUE TITLE
🧑‍💻 : add feedback page

### ISSUE THREAD

**Issue by Kajalmehta29** [iamrahulmahato/master-web-development#956]
:red_circle: **Title** : Add feedback page
:red_circle: **Enhancement Aim** : To make website more user friendly.
:red_circle: **Changes** : 
I want to add the feedback/review page which will help the website grow in future.
Please assign this issue to me under gssoc-extd and hacktoberfest.

### Screenshots 📷

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Kajal Mehta
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC-EXTD

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
can you share the ui

**Comment by Kajalmehta29** [comment]
@iamrahulmahato  please if you can make it to level 2. It would be great

**Comment by Kajalmehta29** [comment]
@iamrahulmahato  please merge this.
