### ISSUE TITLE
📃: Want to add a Weather App new project.

### ISSUE THREAD

**Issue by Suvadip-sana** [iamrahulmahato/master-web-development#962]
🔴 Title : Weather app
🔴 Tech stack : HTML, CSS, JS, Openweather free API
🔴 Objective : It's an simple project like others here. It display weather details based on searched city.
🔴 Summary : Project about a API based weather forecasting app using HTML, CSS and JavaScript. Search by city name, display it's 
                         weather status like Temperature, Status, Humidity, Visibility and Wind Speed.
📸 Screenshots

https://github.com/user-attachments/assets/7d0b2e9e-8cc5-40d8-9426-93e289da0ca1

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
1> GSSOC-EXTD
2> Hacktoberfest

***********************************************************************
@iamrahulmahato 

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
the project is already present so I am closing the issue
