### ISSUE TITLE
📃: Want to add a new project - Spotify Clone

### ISSUE THREAD

**Issue by prachichoudhary2004** [iamrahulmahato/master-web-development#964]
🔴 Title : **Spotify Clone**
🔴 Tech stack : HTML , CSS ,JS
🔴 Objective : Contribute towards repo by adding a hi tech frontend project
🔴 Summary : I am a web develop (basically mastered frontened ) and would like to add another project which is a very good frontend project every developer should learn

Name :  **Prachi Choudhary**
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC , HACKTOBERFEST
 _![Screenshot (7)](https://github.com/user-attachments/assets/0078f1ee-8ede-4827-8df1-e280d37391cb)_ 
@iamrahulmahato @sanjay-kv

**Comment by prachichoudhary2004** [comment]
Kindly assign me this issue so that i can work on it

**Comment by iamrahulmahato** [comment]
the project is already present so I am closing the issue
