### ISSUE TITLE
📃: want to add a project -DigitalClock

### ISSUE THREAD

**Issue by prachichoudhary2004** [iamrahulmahato/master-web-development#965]
🔴 Title : DigitalClock
🔴 Tech stack : HTML, CSS,  Javascript
🔴 Objective : To create a digital clock
🔴 Summary :I want to add a project - digital clock which is built using html , css ,js and has features like timezone , mood based background , timer , stopwatch . it also has a unique alarm feature wherein a song plays after alarm rings and also a small game appears for the user to play just to make it more engaging .
📸 Screenshots/Video:
![Uploading Screenshot (8).png…]()

🔴 Title :Screen color Change For testing Display
🔴 Tech stack : HTML, CSS, JavaScript
🔴 Objective : create an web application that helps to test display colors
🔴 Summary : it's an application that will be used to test the display colour by displaying different colours on displays
📸 Screenshots: N/A

✅ Details to Include When Taking the Issue:
Name : @prachichoudhary2004 
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC exted 2024 , Hacktoberfest

 Kindly Assign this issue to me @iamrahulmahato 
Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by prachichoudhary2004** [comment]
kindly assign me this so that i can start working on this and add more features

**Comment by iamrahulmahato** [comment]
the project is already present so I am closing the issue
