### ISSUE TITLE
📃: Add a project to propose your crush

### ISSUE THREAD

**Issue by akhulisumit** [iamrahulmahato/master-web-development#966]
🔴 Title : propose your crush
🔴 Tech stack : CSS, HTML, js
🔴 Objective : to propose your crush
🔴 Summary : this use drag feature and some flattery lines to propose her
📸 Screenshots

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by byteom** [comment]
please assign this task to me
