### ISSUE TITLE
🧑‍💻 : adding a feedback form

### ISSUE THREAD

**Issue by tanishraj7** [iamrahulmahato/master-web-development#968]
:red_circle: **Title** : Feedback
:red_circle: **Enhancement Aim** : Adding a feedback form with styling
:red_circle: **Changes** :  new feedback section

### Screenshots 📷
 N/A

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Tanish Raj
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
can you share the ui

**Comment by iamrahulmahato** [comment]
i am closing as someone already working on it
