### ISSUE TITLE
I want to add  Spotify Clone App using HTML and CSS.

### ISSUE THREAD

**Issue by Shekhar-Raj** [iamrahulmahato/master-web-development#97]
Preview:

![image](https://github.com/user-attachments/assets/6de5f0ff-b8f6-432b-8e66-2d702ef13ae0)

Please assign me this issue so that I can proceed further under GSSOC extd 2024.

**Comment by samikshatrivedi007** [comment]
please assign this issue to me #97.

**Comment by samikshatrivedi007** [comment]
I am able to add spotify clone app  using html and css , and i am good in it . give this task to me .
kindly assign me to do this #97

**Comment by Shekhar-Raj** [comment]
Will you be more happy if you assign the issue to the person who raised it? Therefore Please assign the issue to me so that I can contribute successfully.

**Comment by iamrahulmahato** [comment]
@samikshatrivedi007 Opensource is all about collaboration; you can raise some other issues.
