### ISSUE TITLE
🧑‍💻 : Missing Search Bar on the Website

### ISSUE THREAD

**Issue by sidgureja7803** [iamrahulmahato/master-web-development#987]
:red_circle: Title : Missing Search Bar on the Website

:red_circle: Enhancement Aim: Add a search bar for easy navigation and improved user experience.

:red_circle: Changes:

Implement a functional search bar in the website's header.
Style the search bar to match the existing design.
Ensure that the search functionality is responsive and works seamlessly across different devices.
Add placeholder text like "Search..." within the bar.
Integrate the search bar with the current routing or content for real-time search results

Screenshots 📷
N/A

✅ Details to Include When Taking the Issue:
Name:  Siddhant Gureja
Participant Role: Hacktober-fest

**Comment by sidgureja7803** [comment]
@iamrahulmahato Please assign this issue to me

**Comment by iamrahulmahato** [comment]
someone already working on it
