### ISSUE TITLE
🧑‍💻 : Add Search Functionality for Projects by Name

### ISSUE THREAD

**Issue by istanujbhatia** [iamrahulmahato/master-web-development#992]
🔴 Title : Add Search Functionality for Projects by Name

🔴 Enhancement Aim :
To enhance user experience by allowing users to search for specific projects by name, making it easier to locate a particular project among the many available.

🔴 Changes :  
- Implement a search bar at the top of the project listings page.
- Add JavaScript functionality to filter and display projects dynamically based on the user’s input.
- Ensure the search is responsive and updates the displayed results in real-time as the user types.
- Style the search bar and filtered project results to align with the existing design of the page.

### Screenshots 📷  
N/A

***********************************************************************

✅ **Details to Include When Taking the Issue**:  
Name: Tanuj Bhatia (istanujbhatia)
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.):
Contributor GSSOC -EXTD,Hacktoberfest

***********************************************************************

Happy Contributing! 🚀  

---

This draft provides a clear summary of the feature's purpose and the changes required. Let me know if any adjustments are needed!

**Comment by iamrahulmahato** [comment]
someone working on it
