### ISSUE TITLE
🧑‍💻 : Can try to implement a vs computer mode in TTT

### ISSUE THREAD

**Issue by Nivesh2003** [iamrahulmahato/master-web-development#994]
:red_circle: **Tic tac toe game** :
:red_circle: **Enhancement Aim - Adding a VS computer mode** :
:red_circle: **Changes** :  1. Creating a VS computer logic in tic tac toe game 
2. Will try to create a button to switch modes

### Screenshots 📷
 N/A

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Nivesh Chaudhary
Participant Role : GSSOC , Hacktoberfest

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by iamrahulmahato** [comment]
already present in project
